[glossary]
= Kill Bill Glossary

//https://docs.asciidoctor.org/asciidoc/latest/sections/glossary/
//https://discuss.asciidoctor.org/How-to-link-the-glossary-td4784.html

[glossary]
== A

[[account]]
Account:: A record that contains details about the customer such as name, address, email address, phone number, etc. Also referred to as a "customer account."

[[addon]]
Addon:: A <<product, product>> that that can be bundled with a <<base_product, base product>>. See <<product_category, Product Category>>.

API:: The software intermediary that enables communication between two applications. For more information, see the https://killbill.github.io/slate/[_Kill Bill API Reference_].

//Account Balance:: TODO

Account Credit:: The amount that your business owes to a customer. It is generated when an administrator adds a credit, a subscription is cancelled, etc. It is calculated as the sum of `CBA_ADJ` <<invoice_item, invoice items>>.


== B

[[base_product]]
Base Product:: A <<product, product>> that can have an <<addon,addon>> product. See <<product_category, Product Category>>.

Billing in Advance:: A type of https://docs.killbill.io/latest/catalog-examples.html#_billing_modes[billing mode] in which you can charge for services that are provided at a later date.

Billing in Arrear:: A type of https://docs.killbill.io/latest/catalog-examples.html#_billing_modes[billing mode] in which you can charge for services that are delivered in a previous billing period.

[[billing_start_date]]
Billing Start Date:: The date on which billing starts for a subscription. See also <<entitlement_start_date, Entitlement Date>>.

[[billing_mode]]
Billing Mode:: The method in which you invoice for a recurring subscription. "Billing in advance" and "billing in arrear" are two types of billing modes.

Billing Period:: The frequency in which Kill Bill invoices the account for one or more subscriptions. (_Examples:_ DAILY, WEEKLY, BIWEEKLY, MONTHLY, QUARTERLY, BIANNUAL, ANNUAL, BIENNIAL, and NO_BILLING_PERIOD)

[[bundle]]
Bundle:: A collection of subscriptions associated with a single service instance. For example, a customer might have a base subscription for her phone, plus an add-on subscription for international dialing. Because both subscriptions are associated with the same phone, they are collected into a single bundle. An account may have several bundles, each with one or more subscriptions. Also known as a "subscription bundle."

Bill Cycle Day:: The day of the month the invoice is created for an account. Note that this is applicable only to monthly-based subscriptions (subscriptions that have a `MONTHLY`, `QUARTERLY`, `ANNUAL`, `BIMESTRIAL`, `BIANNUAL`, `BIENNIAL` billing period) as opposed to `DAILY`, `WEEKLY`, etc. subscriptions.

== C

[[catalog]]
Catalog:: A description of the products, plans, phases, price lists, and rules that are available to customers. A catalog lets Kill Bill know what is being offered for sale and how much to charge for it.

[[ctd]]
Charged Through Date(CTD) :: The date up to which the subscription has been invoiced for. Irrespective of whether the billing happens `IN_ADVANCE` or `IN_ARREAR`, each subscription has a date up to which it was invoiced for. This is the CTD. For `IN_ADVANCE` billing mode, the `CTD` is a date in the future while for `IN_ARREAR`, it is a date in the past. 

[[child]]
Child:: An account that is associated with a parent account. Setting up a parent-child associations lets you define which entity is responsible for paying the invoice. See also <<parent, Parent>>.

[[credit_invoice]]
Credit Invoice:: An invoice corresponding to a credit. It is generated when an administrator adds an account credit. It consists of two <<invoice_item, invoice items>>: a negative `CREDIT_ADJ` item and a positive `CBA_ADJ` item.

[[customer]]
Customer:: The person who purchases a product or service from your organization. See also <<account, Account>>.

Custom Field:: An attribute (key-value pair) that may be attached to a resource like an account, bundle, subscription, and so on.

== D

Discount Phase:: A type of <<phase,phase>> that defines a lower price for a set time period (after which the regular price automatically takes effect). A discount phase is specified as part of a <<plan,plan>> within the <<catalog,catalog>>.

[[downgrade]]
Downgrade:: The change of a subscription from one plan to another plan of lesser dollar value.

{A downgrade is a change order or amendment to an existing contract or subscription in which a customer chooses a lower service level. A downgrade can be a less expensive service offering, or a smaller quantity or users or usage levels. Depending on business rules, this change can result in a prorated credit of the original service or a penalty fee associated with the change.}

Dunning:: See <<overdue_system, Overdue System>>.

Duration:: Defines the length of time for a <<phase,phase>>. Kill Bill supports durations of days, months, years or unlimited.

== E

[[entitlement]]
Entitlement:: Represents access to the product/service provided to an end user (customer). It is separate from billing. See <<subscription, Subscription>>.

[[entitlement_start_date]]
Entitlement Start Date (Or "Entitlement Date"):: The date on which a user gains access to the underlying entitlement or product/service . See also <<billing_start_date, Billing Start Date>>.

Evergreen Phase:: A type of <<phase,phase>> in which no end date is specified and Kill Bill continually bills the account for the subscription until the customer cancels it. A evergreen phase is specified as part of a <<plan,plan>> within the <<catalog,catalog>>.

External Key:: An alternative unique ID for an object, which you can use to map the object with an external resource. For example, you could define an external key for a specific customer account, which is the same as the identifier  used in your CRM system.

_Example:_

[cols="1"]
|===

| *CRM Name:* Shirley Skinner

*CRM ID:* #4766gt53321#

| *KILL BILL*:

*Kill Bill Name:* Shirley Skinner

*Kill Bill External Key:* #4766gt53321#

*Kill Bill ID:* 6d468048-a1dc-45ea-87b5-72cf9ec14771

|===

External Payment Method:: A type of payment method that enables you to track payments that occur outside of Kill Bill (_Example:_ check payment). Its functionality is provided as part of the Kill Bill payment system. 

== F

Fixed Term:: A type of <<phase,phase>> that specifies an end date and during which Kill Bill continually bills the account for the subscription. A fixed term phase is specified as part of a <<plan,plan>> within the <<catalog,catalog>>.

== G

== H

== I

[[invoice]]
Invoice:: An invoice is a bill provided to a customer for charges that are payable on the customer's account. A single invoice consolidates charges for all subscriptions held by that customer for a specified time period. Invoices may be set to be paid automatically, or may be paid manually by the customer. An invoice consists of one or more <<invoice_item,invoice items>>.

[[invoice_amount]]
Invoice Amount:: The amount that a customer is charged as part of an invoice. Also known as "Invoice Total",  "Total",  "Charged Amount" or simply "Amount". At a high level, it is calculated by adding the amounts on all the chargeable <<invoice_item,invoice items>> associated with an invoice. See https://docs.killbill.io/latest/invoice_examples.html#_charged_amount[charged amount] for more information.

[[invoice_balance]]
Invoice Balance:: The amount that the customer owes as part of an invoice. It is positive if the customer owes something or zero otherwise. At a high level,  it is calculated by subtracting the paid amount from the <<invoice_amount, invoice amount>>. See https://docs.killbill.io/latest/invoice_examples.html#_invoice_balance[invoice balance] for more information.

[[invoice_item]]
Invoice Item:: Represents a single item charged on an <<invoice,invoice>>. Given an active <<subscription,subscription>>, one could see multiple items for that subscription on a single invoice, including recurring items, usage items, fixed price items, etc. There can also be items for different subscriptions on the same invoice, as well as items that are unrelated to subscriptions, such as adjustments and taxes.

[[invoice_item_type]]
Invoice Item Type:: Specifies the type of <<invoice_item,invoice item>> which can be one of `EXTERNAL_CHARGE`, `FIXED`, `RECURRING`, `REPAIR_ADJ`, `CBA_ADJ`, `ITEM_ADJ`, `USAGE`, `TAX`, `PARENT_SUMMARY`. Refer to the
https://docs.killbill.io/latest/userguide_subscription.html#components-invoicing[_Subscription Billing_] document for more information.

Invoice Original Amount Charged:: The amount that the customer is charged as part of an invoice at the time of invoice creation. At a high level, it is calculated by adding the amounts on all the chargeable <<invoice_item,invoice items>> associated with an invoice at the time of invoice creation.

[[invoice_payment]]
Invoice Payment:: <<payment,Payment>> made against a specific invoice. By default, Kill Bill attempts to make a payment against an invoice using the account's default <<payment_method, payment method>>.

[[invoice_refund]]
Invoice Refund:: Refund amount associated with an <<invoice_payment,invoice payment>>. Kill Bill allows issuing a full or partial refund against an invoice payment.

Invoice Status:: The current state of an invoice, which can be in a `DRAFT`, `COMMITTED` or `VOID` state.

//Invoice Adjustment::


== J

Janitor:: An internal Kill Bill service that helps ensure that payment transactions end up in a terminal state.

== K

[[kaui]]
Kaui:: An acronym for Kill (Bill) Admin User Interface, this browser-based application lets back office staff (in Finance, Marketing, Development, etc.) perform Kill Bill-related tasks, such as creating customer accounts, subscriptions, adding plugins, and so forth.

Kill Bill Administrator (or Kill Bill Admin):: The person responsible for installing or configuring Kill Bill.

Kill Bill Package Manager (kpm or KPM):: A command line tool that facilitates the installation of Kill Bill, its plugins, and Kaui. It also provides utility helpers useful for the day-to-day management of a production system.

== L

== M

== N

== O

[[overdue_system]]
Overdue System (or Dunning):: A Kill Bill module that defines the flow that the system must follow when an account is overdue (that is, has an unpaid balance). It is used in conjunction with the <<payment_retry_mechanism, payment retry module>>.

== P

[[parent]]
Parent:: An account that contains one or more child accounts. Setting up a parent-child associations lets you define which entity is responsible for paying the invoice. See also <<child, Child>>.

[[payment]]
Payment::  A Payment in Kill Bill is an amount paid or payable on a specific <<account,account>> due to an <<invoice,invoice>> or independent of any invoice. A payment may be associated with a series of <<payment_transaction,payment transactions>>.

[[payment_attempt]]
Payment Attempt:: A Payment Attempt is an attempt to perform a <<payment_transaction,payment transaction>>. A payment attempt may succeed or fail, and a payment transaction may have more than one payment attempt.

[[payment_gateway]]
Payment Gateway (or Payment Processor):: An  external entity that processes the payment. Some examples are Stripe, Adyen, Qualpay. 

[[payment_method]]
Payment Method:: A Kill Bill record that represents an abstraction corresponding to a payment scheme like a credit card, debit card, or PayPal. An <<account,account>> can have multiple payment methods corresponding to different payment gateways. For example, an account can have a credit card payment method as well as a PayPal payment method. Each account also has a *default* payment method associated with it. When the account needs to be charged for recurring payments, the system uses the default payment method.

[[payment_retry_mechanism]]
Payment Retry Mechanism:: An internal mechanism by which Kill Bill can retry failed payments as per a configured schedule. 

[[payment_transaction]]
Payment Transaction:: A payment transaction represents a payment operation such as authorization, charge back, refund, etc. A payment transaction takes place using a <<payment_method,payment method>>. The transaction is processed by a plugin, which provides access to the appropriate payment gateway. The payment gateway processes the transaction, using the payment method provided in the request.


//PCI Compliance
//{ PC​I DSS (payment card industry data security standard)}
//{The payment card industry data security standard (PCI DSS) is a set of requirements designed to ensure that all companies that process, store, or transmit credit card information maintain a secure environment. Zuora has compliance in accordance with PCI Service Provider Level1 (PCI DSS SP L1) v1.2. Zuora is listed on the VISA website as an approved provider.}

[[permissions]]
Permissions:: In Kill Bill, a defined action that can be performed in a system (for example, `TAG_CAN_ADD` OR `ACCOUNT_CAN_CREATE`). You can assign one or more permissions to a <<user_role,role>>, which can then be associated with a user. The user can only perform the permissions associated with that role.

For more information, see the Kill Bill https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/security/Permission.java[list of user permissions].

[[phase]]
Phase:: The time periods within a plan. Kill Bill phases can be any of the following types: `TRIAL`, `DISCOUNT`, `FIXEDTERM`, or `EVERGREEN`. Note that a plan has at least one phase (i.e., a plan cannot be "empty" of phases.) A phase is also referred to as a "plan phase." See <<plan, Plan>> below.

[[plan]]
Plan:: Details for the terms of the <<subscription,subscription>> contract. In particular, plans define how much a customer pays for a product and how often they pay it (_Example:_ A Standard product at $100 per month). A plan consists of at least one phase and can have multiple phases (_Example:_ A discount phase followed by a regular price phase).

[[plugin]]
Plugin:: A piece of code written on top of the Kill Bill platform that interacts with the system. It can be called from the Kill Bill platform through plugin APIs or can make API calls to Kill Bill. It can also receive notifications from the Kill Bill platform. See https://docs.killbill.io/latest/plugin_introduction.html[Plugin Introduction].

Price List:: One or more plans that have discount/special pricing. Price lists are defined in the <<catalog,catalog>>.
Along with price lists, you define <<rules,catalog rules>> that specify which price list to use if a customer changes plans.

//Pricing Tiers
//Also known as "tiered pricing" or "price tiers."
//{A common subscription and usage charge model where pricing changes are based on the incremental number of units that are purchased. For example, 1-5 users are charged full price and 5-10 users receive discounted pricing. A customer purchases 7 units. Units 6 and 7 are discounted, and the first 5 units are charged at the full price.}

[[product]]
Product:: A product or service that the customer can purchase (or rent/lease). A product can be associated with multiple <<plan,plans>>, each plan specifying different ways the product can be purchased (e.g., a monthly plan and an annual plan).

[[product_category]]
Product Category:: A type of product. Possible values are <<addon, ADDON>>, <<base_product, BASE>>, and <<standalone_product, STANDALONE>>.

//Proration
//{Adjusting a customer's bill amount to reflect any plan changes made in the middle of a billing cycle.}

== Q

== R

//Refund
//{A refund returns money to a customer - as opposed to a credit, which creates a customer credit balance that may be applied to reduce the amount owed to you. For instance, refunds are used when a customer cancels service and is no longer your customer. Refunds can also represent processed payments that are reversed, such as a chargeback or a direct debit payment reversal.}

[[rules]]
Rules:: The rules that determine how Kill Bill should behave when a subscription is created, cancelled or changed. Also known as "catalog rules."

== S

[[subscription]]
Subscription:: A contract between your organization and a customer to purchase a particular product/service with particular terms. Kill Bill associates a subscription with a <<plan,plan>>, an <<account,account>>, and a start date. In other words, Subscription = <<entitlement, Entitlement>> + Billing Information. 

Subscription Bundle:: See <<bundle>>.

[[standalone_product]]
Standalone Product:: A <<product, product>> that cannot have any <<addon,addon>> products. See <<product_category, Product Category>>. A <<bundle, subscription bundle>> can include multiple standalone <<subscription, subscriptions>>. This is as opposed to a subscription bundle with a <<base_product, base product>> which can have only one base subscription and zero or more addon subscriptions within the same bundle.

== T

Tag:: A property that can be added to objects (such as accounts, bundles or subscriptions). There are two kinds of Tags: system tags and user tags.

** System tags can impact the behavior of the system. Examples include `AUTO_PAY_OFF` or `AUTO_BILLING_OFF`.

** User Tags are informational only, and can be created through <<kaui, Kaui>>, the Kill Bill admin UI. User tags can be used to identify collections of accounts, subscriptions, or bundles so that they can easily be found or reported on later.

Tag Definition:: Specifies a schema or template for creating a tag. Before you can attach a user tag to an object like account or subscription, a tag definition needs to be created corresponding to it. Once a tag definition is created, you can attach the corresponding tag to multiple objects.

[[tenant]]
Tenant:: The division or organization that is using Kill Bill as a group of users. Note that an organization can have more than one tenant, as Kill Bill supports multi-tenancy.

[[trial_phase]]
Trial Phase:: A type of <<phase, phase>> that defines a time period during which the account is not charged (or is heavily discounted). After the trial period, the regular price automatically takes effect. A trial phase is specified as part of a <<plan, plan>> within the <<catalog,catalog>>.

== U

[[upgrade]]
Upgrade:: The change of a subscription from one plan to another plan of higher dollar value.

//{A change order or amendment to an existing contract subscription in which a customer chooses a higher service level, such as a more expensive service offering, or a larger quantity of users.}

Usage Pricing:: Pricing a service or item based on its consumption or usage. Kill Bill supports two types of usage billing modes, `CONSUMABLE` and `CAPACITY`. See https://docs.killbill.io/latest/userguide_subscription.html#components-catalog-usage[_Usage Billing_].
//{Pricing a service or item based on its consumption or usage rather than a flat rate for a given service or period of time.}

User:: A person who logs on to Kaui.

[[user_role]]
User Role:: A group of <<permissions, permissions>> that specify which actions the user is allowed to perform in Kaui. A user can have multiple roles. A role can have multiple permissions.

== V

== W

== X

XML:: Acronym for https://www.w3.org/XML/[eXtensible Markup Language], which is used to define the data within the Kill Bill catalog.

== Y

== Z