= Kill Bill Glossary
(c) 2021 The Billing Project, LLC
:revlevel: 1.0
:revdate: June 2021
:revremarks: first draft
:icons: font

//RESOURCES
//KILL BILL
//https://docs.killbill.io/latest/userguide_subscription.html#components-catalog-overview

//ASCIIDOC
//https://asciidoctor.org/
//https://github.com/asciidoctor/asciidoctor.org/blob/main/docs/asciidoc-writers-guide.adoc
//https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

[glossary]

<<A>> | <<B>> | <<C>> | <<D>> | <<E>> | <<F>> | <<G>> | <<H>> | <<I>> | <<J>> | <<K>> | <<L>> | <<M>> | <<N>> | <<O>> | <<P>> | <<Q>> | <<R>> | <<S>> | <<T>> | <<U>> | <<V>> | <<W>> | <<X>> | <<Y>> | <<Z>>

== A

[[Account]]Account:: A record that contains details about the customer such as name, address, email address, phone number, etc. Also referred to as a "customer account."

API:: The software intermediary that enables communication between two applications. For more information, see the https://killbill.github.io/slate/[_Kill Bill API Reference_].

== B

Billing Period:: The period for which the customer is billed. _Examples:_ `MONTHLY`, `ANNUAL`

[[Bundle]]Bundle:: A collection of subscriptions associated with a single service instance. For example, a customer might have a base subscription for her phone, plus an add-on subscription for international dialing. Because both subscriptions are associated with the same phone, they are collected into a single bundle. An account may have several bundles, each with one or more subscriptions. Also known as a "subscription bundle."

== C

Catalog:: A description of the set of products, plans, price lists, and rules that are available to customers. A catalog lets Kill Bill know what is being offered for sale and how much to charge for it.

[[Child]]Child:: An account that is associated with a parent account. Setting up a parent-child associations lets you define which entity is responsible for paying the invoice. See also <<Parent>>.

Credit


Customer:: The person who purchases a product or service from your organization. See also <<Account>>.

== D

== E

External Key:: An alternative unique ID for an object, which you can use to map the object with an external resource. For example, you could define an external key for a specific customer account, which is the same as the identifier  used in your CRM system.

_Example:_

[cols="1"]
|===

| *CRM Name:* Shirley Skinner

*CRM ID:* #4766gt53321#

| *KILL BILL*:

*Kill Bill Name:* Shirley Skinner

*Kill Bill External Key:* #4766gt53321#

*Kill Bill ID:* 6d468048-a1dc-45ea-87b5-72cf9ec14771

|===

== F

== G

== H

== I

== J

== K

[[Kaui]]Kaui:: An acronym for Kill (Bill) Admin User Interface, this browser-based application lets back office staff (in Finance, Marketing, Development, etc.) perform Kill Bill-related tasks, such as creating customer accounts, subscriptions, adding plugins, and so forth.

Kill Bill Administrator (or Kill Bill Admin):: The person responsible for installing or configuring Kill Bill.

== L

== M

== N

== O

== P

[[Parent]]Parent:: An account that contains one or more child accounts. Setting up a parent-child associations lets you define which entity is responsible for paying the invoice. See also <<Child>>.

Payment Method:: A record of payment details, such as for credit cards, debit cards, PayPal accounts, etc. Each account can have many payment methods and one default payment method. Note that much of the representation of a payment method is plugin-specific and is actually stored by the payment plugin itself.

Phase:: The time periods within a plan. Kill Bill phases can be any of the following types: `TRIAL`, `DISCOUNT`, `FIXEDTERM`, or `EVERGREEN`. Note that a plan has at least one phase (i.e., a plan cannot be "empty" of phases.) A phase is also referred to as a "plan phase." See <<Plan>> below.

[[Plan]]Plan:: Details for the terms of the <<Subscription,subscription>> contract. In particular, plans define how much a customer pays for a product and how often they pay it (_Example:_ A Standard product at $100 per month). A plan consists of at least one phase and can have multiple phases (_Example:_ A discount phase followed by a regular price phase).

Price List:: One or more plans that have discount/special pricing. Price lists are defined in the <<Catalog,catalog>>.
Along with price lists, you define <<Rules,catalog rules>> that specify which price list to use if a customer changes plans.

Pricing Tiers
Also known as "tiered pricing" or "price tiers."
{A common subscription and usage charge model where pricing changes are based on the incremental number of units that are purchased. For example, 1-5 users are charged full price and 5-10 users receive discounted pricing. A customer purchases 7 units. Units 6 and 7 are discounted, and the first 5 units are charged at the full price.}

[[Product]]Product:: A product or service that the customer can purchase (or rent/lease). A product can be associated with multiple <<Plans,plans>>, each plan specifying different ways the product can be purchased (e.g., a monthly plan and an annual plan).

Proration
{Adjusting a customer's bill amount to reflect any plan changes made in the middle of a billing cycle.}

== Q

== R

Refund

{A refund returns money to a customer - as opposed to a credit, which creates a customer credit balance that may be applied to reduce the amount owed to you. For instance, refunds are used when a customer cancels service and is no longer your customer. Refunds can also represent processed payments that are reversed, such as a chargeback or a direct debit payment reversal.}

[[Rules]]Rules:: The rules that determine how Kill Bill should behave when a plan is created, cancelled or changed. Also known as "catalog rules."

== S

[[Subscription]]Subscription:: A contract between your organization and a customer to purchase a particular product/service with particular terms. Kill Bill associates a subscription with a <<Plan,plan>>, an <<Account,account>>, and a start date.

Subscription Bundle:: See <<Bundle>>

== T

Tag:: A property that can be added to objects (such as accounts, bundles or subscriptions). There are two kinds of Tags: system tags and user tags.

** System tags can impact the behavior of the system. Examples include `AUTO_PAY_OFF` or `AUTO_BILLING_OFF`.

** User Tags are informational only, and can be created through <<Kaui>>, the Kill Bill admin UI. User tags can be used to identify collections of accounts, subscriptions, or bundles so that they can easily be found or reported on later.

Tenant:: The division or organization that is using Kill Bill as a group of users. Note that an organization can have more than one tenant, as Kill Bill supports multitenancy.

== U

User:: A person who logs on to Kaui.

== V

== W

== X

== Y

== Z
