=== Overview

Kill Bill is a multi-tenancy system, which means that you can have multiple instances of Kill Bill running on your server(s). This is an excellent method for running both production and test versions of Kill Bill. Another use case could be to use a different tenant for the different regions that make up your business.

[IMPORTANT]
*Important:* If you have already created tenants using the API, you must also add them in Kaui in order for Kaui to recognize them.

=== Before You Begin

Make sure you have on hand the API key and API secret for the tenant you are creating.

[[first-time-login]]
=== First-Time Login &#8211; Create a Tenant

When you log in to Kaui for the first time after installing Kill Bill, you are prompted to create your first tenant:

SCREENSHOT of Add New Tenant screen

. Type in the tenant *Name*, *API Key*, and *API Secret*.
+
 The API key and API secret pair is used in all HTTP requests to ensure that the user issuing the request has the correct permissions to access the tenant.
+
_QST: Where do you get the API Key and Secret? Do we even need to explain this?_
+
. Click the *Save* button.

Kaui displays the Tenant Details page, which is covered in the following section.

=== Tenant Details Page

Tenant Details
Useful Links
Allowed Users
Tabs:
* Catalog Show
* Overdue Show
* Invoice Template
* Invoice Translation
* Catalog Translation
* Plugin Config



=== Additional Resources


=== Add a Tenant

https://docs.killbill.io/latest/stripe_plugin.html#_step_2_add_a_new_tenant

=== Add Users to a Tenant


Tenant configuration (catalog, overdue, internationalization, …​)
