= Kill Bill Administrative UI

== Overview

Kill Bill itself doesn't provide a UI to manage your accounts and subscriptions.
All interactions with the core platform is expected to be done via the REST API and/or the Java APIs (if you decide to embed Kill Bill).

http://github.com/killbill/killbill-admin-ui[Kaui] (the Kill Bill Admin UI) is a rails mountable engine that provides most of the functionality required to manage user accounts and their subscriptions, invoices, payments...
In addition to Kaui, we also provide a https://github.com/killbill/killbill-admin-ui-standalone[self contained war] that can be deployed in a container (tomcat, ..).

== Features

Kaui has been designed to be fully multi-tenant which means you can deploy one UI to access all your tenants.
There is a http://killbill.io/blog/multi-tenancy-authorization/[blog here] which explains in a bit more details on how that works.
Along with the multi-tenancy support, Kaui also leverages the authentication and authorization layer built into Kill Bill to restrict
certain admin with specific permissions to have access to well defined screens and actions (refund a payment, credit an account, ...)


The core features available in Kaui are:

* List on a per tenant basis all the accounts, bundles, invoices, payments, and allow to search based on various fields (account name, external key, email,...)
* Account management

** Show contact info
** Show account balance, available credits, overdue status
** Manage existing payment methods
** List existing subscriptions and allow to create new ones, change plans, cancel subscriptions
** Tag management

* Account Timeline: Visualize all the state (events) through time associated with the account and allow specific filtering (subscription, event type, ...)

== Extensions

As mentioned, Kaui is a Rails mountable engine, which means you can mount it into your existing Rails app; it also means that you can add additional Rails mountable engine in the same app, and for instance
we also offer https://github.com/killbill/killbill-analytics-ui[an analytics Rails mountable engine] which displays analytics graphs when the https://github.com/killbill/killbill-analytics-plugin[analytics plugin] has been deployed.

When you deploy the https://github.com/killbill/killbill-admin-ui-standalone[self contained war], both mountable engines are mounted by default.

== Screenshots

In this section we want to show a few screenshots to give a sense of what Kaui provides (and looks like):
The data that we show is synthetic data that we generated using tests.

== Pagination of all Accounts (Per Tenant)

After the user has logged in and after choosing the tenant, the user can click on the `Accounts` tab to display all known accounts,
and make a search to find a specific account.

image:https://drive.google.com/uc?&id=0Bw8rymjWckBHVzB3eXdPbWxteTQ&w=960&amp;h=480[align=center]
//https://drive.google.com/file/d/0Bw8rymjWckBHVzB3eXdPbWxteTQ/view?usp=sharing


== Account

This shows the known information about a given user account:

image:https://drive.google.com/uc?&id=0Bw8rymjWckBHRV9rNDRwQ1ZNMGc&w=960&amp;h=480[align=center]
//https://drive.google.com/file/d/0Bw8rymjWckBHRV9rNDRwQ1ZNMGc/view?usp=sharing


== Billing Timeline

The billing timeline shows all the events that occurred for a specific user account:

image:https://drive.google.com/uc?&id=0Bw8rymjWckBHSDZNaVBRMVFUVlU&w=960&amp;h=480[align=center]
//https://drive.google.com/file/d/0Bw8rymjWckBHSDZNaVBRMVFUVlU/view?usp=sharing

== Analytics

The `Analytics` screen will only be available when the analytics plugin has been deployed. It allows
to specify a date range and display custom metrics. We provide a few by default, but the analytics framework
allows to add any desired metric. Here we show the invoice balance over time:

image:https://drive.google.com/uc?&id=0Bw8rymjWckBHWDBQOGJZRnk0LWM&w=960&amp;h=480[align=center]
//https://drive.google.com/file/d/0Bw8rymjWckBHWDBQOGJZRnk0LWM/view?usp=sharing