= How to Maintain a Single-Tier System

== Overview

This guide explains how to maintain your single-tier Kill Bill installation on AWS.

== Login

To perform most maintenance tasks you will need to login to your EC2 instance. There are two requirements that must be met before you can do this:

1. You will need the private key for the **key pair** that you set up when the instance was initialized. If you do not have a key pair you will need to redo your installation. You cannot create one now.

2. You will need Port 22 enabled for TCP in your security group.  See `howtos/set-up-a-security-group`. For security we recommend you disable this port when you are not using it.

When these requirements are met, you can login from your computer using the secure shell command:

`ssh -i PRIVATE_KEY.pem ubuntu@INSTANCE_IP`

Here PRIVATE_KEY is the pathname where you have stored your private key, and INSTANCE_IP is the  *public* IPV4 address for your instance. The IPV4 address can be seen by selecting the Instance ID on the AWS *Instances* page.  The private key will not work unless its access controls are set to readable by the owner only.

On Windows versions before Windows 10, you may need to download a program called PuTTY to enable `ssh`. On Windows 10 `ssh` is available but may need to be activated through the Settings screen.

The first time you login, you will see a warning message asking if you want to add this host to your list of hosts. You should answer `yes`.

You will now be able to explore your instance and perform any necessary  maintenance tasks. To exit from your login, type `exit`.




== Troubleshooting

When you launch the EC2 instance, the full stack should come up, with all services enabled and running, including:

* An instance of `nginx` receiving traffic on port `443` and `8443`
* An instance of Kill Bill server listening on `127.0.0.1:8080` (and receiving external traffic through nginx on port `8443`)
* An instance of Kaui listening on `127.0.0.1:3000` (and receiving external traffic through nginx on port `443`)
* A local `mysql` server running on port `3306`


If anything does not seem to be working correctly, it is time for some troubleshooting. In this section, we will provide some tips to verify the operation of the system, and what to do when things are not working.

If a new installation does not seem to work correctly, the first step is to review your installation process carefully, to be sure that everything has been done and checked as described in this document. If problems persist, we will be glad to work with you to identify the problem. To help us to do this, there are several information reports that you may need to gather. These reports are somewhat technical but can be analyzed by Kill Bill personnel. This section explains how to obtain the reports that may be needed.

=== System Health Check

The healthcheck report checks the health of various software components, and determines if any queues are growing improperly over time. To create this report, login to your EC2 instance and issue the following command:

`curl \http://127.0.0.1:8080/1.0/healthcheck`

This will return a series of messages giving the health status of each component. These messages may look like:

```[source,bash]
"com.codahale.metrics.health.jvm.ThreadDeadlockHealthCheck":{"healthy":true},
"main.pool.Connection99Percent":{"healthy":true},
"main.pool.ConnectivityCheck":{"healthy":true},
...
"bus":{"growing":false},
"overdue-service:overdue-check-queue":{"growing":false},
...
```

An unexpected message may indicate a component that is not working properly.

=== System Information

For a detailed system information report, use the following command:

`curl -u ADMIN:INSTANCE_ID \http://127.0.0.1:8080/1.0/kb/nodesInfo`

Here ADMIN is your Kaui administrator username, and INSTANCE_ID is your EC2 instance ID. THe output will look like:

```[source,bash]
"nodeName":"ip 172-31-20-130.ec2.internal",
"bootTime":"2023-01-28T20:30:19.000Z",
"lastUpdatedDate":"2023-01-28T20:30:19.000Z",
"kbVersion":"0.22.26",
"apiVersion":"0.53.17",
"pluginApiVersion":"0.26.4",
"commonVersion":"0.24.15",
"platformVersion":"0.40.8",
"pluginsInfo":
    [{"bundleSymbolicName":"org.kill-bill.billing.killbill-platform-osgi-bundles-kpm",
      "pluginKey":null,
      "pluginName":"org.kill-bill.billing.killbill-platform-osgi-bundles-kpm",
      "version":null,
      "state":"RUNNING",
      "isSelectedForStart":true,
      "services":[]},
    {"bundleSymbolicName":"org.kill-bill.billing.killbill-platform-osgi-bundles-logger",
      "pluginKey":null,
      "pluginName":"org.kill-bill.billing.killbill-platform-osgi-bundles-logger",
      "version":null,
      "state":"RUNNING",
      "isSelectedForStart":true,
      "services":[]}]
```
      

=== Service Statuses

This procedure does not produce a report, but does provide important information about the status of each service.


The Kill Bill single-tier option is composed of four services. The status of each service can be checked by the following commands:

* Kill Bill service: `sudo service killbill status`
* KAUI service: `sudo service kaui status`
* Nginx service: `sudo service nginx status`
* Mysql service: `sudo service mysql status`

For each report there should be a line near the top with the following form:

`Active: active (running) since Sat 2020-10-24 20:13:43 UTC; 1 day 1h ago`


Similarly you can `start` or `stop` the services using similar commands, such as `sudo service kaui stop` to stop KAUI.


=== Log Files

The system maintains a series of logfiles that should be helpful when troubleshooting is needed.

Tomcat logs are under `/var/lib/tomcat/logs/`:

* KAUI logs: `/var/lib/tomcat/logs/kaui.out`
* Kill Bill server logs: `/var/lib/tomcat/logs/catalina.out`

Nginx logs can be found under `/var/log/nginx/`

* Access logs: `/var/log/nginx/access.log`
* Error logs: `/var/log/nginx/error.log`

=== Diagnostic Command

The `diagnostic` option of the `kpm` command creates an extensive report for a given tenant that may be useful for troubleshooting. To run this command:

```
# Login as 'tomcat'
> sudo su - tomcat
#
# Run the command with your access credentials:
#
> kpm  diagnostic \
  --killbill-credentials=ADMIN {EC2 instance ID} \
  --bundles-dir=/var/lib/killbill/bundles \
  --database-name=killbill \
  --database-credentials=DBUSER DBPASS \
  --killbill-api-credentials=KEY SECRET \
  --kaui-web-path=/var/lib/tomcat/webapps2 \
  --killbill-url=http://127.0.0.1:8080 \
  --account-export=ACCOUNT_ID \
  --database-host=127.0.0.1:3306
```

You will need to edit this command to include:

1. Your KAUI username and password (ADMIN {EC2 instance ID})
2. Your database credentials (DBUSER DBPASS)
3. The key and secret key for your tenant (KEY SECRET)
4. The account ID for the report (ACCOUNT_ID)

The last line of the response should look like:

`Diagnostic data is exported under /tmp/killbill-diagnostics-20200213-23204-u93ah5/killbill-diagnostics-02-13-20.zip`

The specified zip file contains several reports of various sizes. This report can be downloaded to your computer using `sftp` and forwarded to Kill Bill for analysis.

=== Databases

To access the mysql (MariaDB) databases, you can use the following command:

`mysql -u root -proot`

This enables interactive access to the database manager. There is one `killbill` and one `kaui` database created and used by the respective applications. To verify the tables in each database, you can type:

```
use killbill
show tables;
```
or

```
use kaui
show tables;
```

Standard SQL commands can be used to explore or manipulate the tables. Be sure you know what you are doing, or the databases may become corrupted!

To exit the mysql interactive mode, type `exit`.


=== Load Balancer

The load balancer `nginx` should normally require little attention. The configuration files are located under `/etc/nginx/`. The configuration file for `nginx` itself is `/etc/nginx/nginx.conf`. Additional configuration files are located under `/etc/nginx/sites-enabled/`. The only file normally present in this directory is `/etc/nginx/sites-enabled/killbill.conf`. This file may need to be edited to enable SSL, as explained above.

== Upgrades

From time to time new versions of the AMI may be released. These versions will continue to contain all of the Kill Bill components in a single package: Kill Bill, Kaui, the database manager, and the load balancer. This section explains how to upgrade to a new version.

First, login to your instance using `ssh`,

Next, switch to the `tomcat` user:

`sudo su - tomcat`

The configuration file `/var/lib/killbill/kpm.yml` specifies the Kill Bill version (and its plugins) to be run on the instance. Once you edit this file to specify the new version number, it will be used automatically. Perform the following steps:

1. Edit the configuration file to update the version number
2. Run the command `$KPM_INSTALL_KB_CMD`
3. Delete the cached directory `/var/lib/tomcat/webapps/ROOT`
4. Restart the instance.

A similar process can be used for KAUI: update `/var/lib/kaui/kpm.yml`, run `$KPM_INSTALL_KAUI_CMD`, delete the cached directory `/var/lib/tomcat/webapps2/ROOT` and restart the instance.

