Your catalog will have to specify the units for the usage section and also define the plan; for the sake of simplicity we omitted other catalog sections, but to see how the pieces fit together you can look at the example provided with the https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/resources/SpyCarAdvanced.xml[source code].


[source,xml]
---
<units>
	<unit name="chocolate-monthly-videos"/>
</units>
<!--...-->
<plan name="chocolate-monthly">
     <product>Chocolate</product>
     <finalPhase type="EVERGREEN">
         <duration>
             <unit>UNLIMITED</unit>
         </duration>
         <recurring>
             <billingPeriod>MONTHLY</billingPeriod>
             <recurringPrice>
                 <price>
                     <currency>USD</currency>
                     <value>30.00</value>
                 </price>
             </recurringPrice>
         </recurring>		 
         <usages>
             <usage name="chocolate-monthly-videos" billingMode="IN_ARREAR" usageType="CONSUMABLE">
                 <billingPeriod>MONTHLY</billingPeriod>
                 <tiers>
                     <tier>
                         <blocks>
                             <tieredBlock>
                                 <unit>chocolate-videos</unit>
                                 <size>1</size>
                                 <prices>
                                     <price>
                                         <currency>USD</currency>
                                         <value>2</value>
                                     </price>
                                 </prices>
                                 <max>5</max>
                             </tieredBlock>
                         </blocks>
                     </tier>
                     <tier>
                         <blocks>
                             <tieredBlock>
                                 <unit>chocolate-videos</unit>
                                 <size>1</size>
                                 <prices>
                                     <price>
                                         <currency>USD</currency>
                                         <value>1</value>
                                     </price>
                                 </prices>
                                 <max>10000</max>
                             </tieredBlock>
                         </blocks>
                     </tier>
                 </tiers>
             </usage>
         </usages>
     </finalPhase>
</plan>
---

The plan description shows the following:
 
* There is a recurring section that specifies that customer should be invoiced (in advance) at the begining of each month for $30
* There is a section usage that defines two tiers, each of them for a unit of `chocolate-videos` with a size of 1 (we pay for each video)
** The first tier specifies that below 5 videos, the price per video (unit) is set to $2.
** The second tier specifies that after 5 videos and below 10000 (arbitrary number large enough that ensures it will not be met), the price per video becomes $1.


 
 