In this tutorial we will look at the Kill Bill *usage billing* feature. In particular we will see how recurring subscriptions and usage can be configured together. The tutorial will focus on a type of usage that we refer to as *consumable in arrear* and that we explained in that http://killbill.io/blog/usage-billing/[blog]; in short, that is the ability to charge the customer for units he consumed at the end of the billing period.


=== Scenario


Let's assume you want to build a online store selling artisanal chocolates, and geared towards the chocolate aficionados. The service you provide is based on a monthly subscription, that includes 1 box of your (organic certified local produced) home made chocolates. In addition, you also provide videos on the topic (the history of chocolate, its fabrication, recipes of chocolate based dishes, the economy of chocolate, chocolate health benefits, ...) that are accessible online from your website. Customers that subscribed to the base service, can also stream your videos and will be invoiced based on their usage at the end of each period:

* The base service is available for $30/month and includes that ecstatic box of chocolate,
* The first 5 videos (streamed during the month) will be invoiced at $2/video
* The next videos (streamed during the month) will be invoiced at $1/video
