
=== Usage and Metering

Kill Bill's usage module provides an API that can be used to record the per customer's usage. For instance, in order to record 1 unit of `chocolate-videos`, one woud use the API `POST /1.0/kb/usages` with the following json body:

[source,json]
---
{"subscriptionId":"365987b2-5443-47e4-a467-c8962fc6995c",
"unitUsageRecords":[
	"unitType": "chocolate-videos",
	"usageRecords": [
		"recordDate": "2014-03-14T04:32:25+00:00",
		"amount": 1
	]
]}
---

The calls to record usage are made per subscription, but they can include multiple unitTypes (if the catalog had defined them), and for each unit they can specify as many records as desired; the records themselves specify a date of when those units were consumed.

In our example, the online store could directly make the call to Kill Bill using that API to record each video as they are consumed. 

Note that in scenarios where the consumption is much higher (for e.g in the case of a telecom company offering cell-phone minutes), one would need to use a *metering system* that would first *aggregate* the units on a dayly granularity before making the call to Kill Bill. You can check the initial implementation of our https://github.com/killbill/killbill-meter-plugin[metring module] that provides that aggregation functionality.

 
=== Example of a Customer Usage

Let's assume Louis, who is very passionate about chocolate, subscribed to the service on March 13th and watched 13 videos during his first month.

On march 13th, the system will trigger an invoice that will cover the billing period march 13th -> april 13th, and it will contain one RECURRING item with a price of $30; in return, he will receive his first box of chocolate.

On april 13th, the system will now trigger a new invoice that will cover:
* A RECURRING item for the billing period from april 13th -> may 13th with a price of $30,
* A USAGE item for a price of $18 (= 5 * 2 + 8 * 1)

So we can see, that each invoice will include an ITEM for the RECURRING piece (charged ahead, i.e in advance), as well as a USAGE item (charged at the end of the billing period when usage is known, i.e in arrear).

=== Additional Resources

We have integration tests that can used an example:

* https://github.com/killbill/killbill/blob/master/profiles/killbill/src/main/resources/SpyCarAdvanced.xml[Catalog]
* https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/core/test_usage.rb[Test] 


