The Analytics plugin provides two types of APIs: one to retrieve and manipulate the data and one to create dashboards.

===== Data API

To retrieve all data for a given account:

[source,bash]
----
curl -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     http://127.0.0.1:8080/plugins/killbill-analytics/f6da101f-b43c-4bb7-920d-188eaa5ae5f8
----


To force a refresh:

[source,bash]
----
curl -v \
     -X PUT \
     -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     http://127.0.0.1:8080/plugins/killbill-analytics/f6da101f-b43c-4bb7-920d-188eaa5ae5f8
----


===== Dashboards

The Analytics plugin provides simple, yet powerful, dashboarding capabilities.

A dashboard is constituted of a number of reports, each of them being numbered, starting from 1. All reports are displayed in a single column, the report number 1 being the top most one. All reports share the same X axis.

Each report can contain one or multiple time series, the source data being a table or a view with the following format:

[cols=3, options="header"]
|===
|SQL column name
|Description
|Required?

|pivot
|Subcategory in your data
|No

|day
|X values (date or datetime)
|Yes

|count
|Y values (float)
|Yes
|===

====== Reports configuration

Let's say you want to look at the number of accounts created per day, the query may look like:

[source,sql]
----
select
  date_format(created_date, '%Y-%m-%d') as day
, count(*) as count
from analytics_accounts
where report_group = 'default'
group by 1
order by 1 asc
;
----

The first step is to create a view for the query:

[source,sql]
----
create or replace view v_new_accounts_per_day as
select
  date_format(created_date, '%Y-%m-%d') as day
, count(*) as count
from analytics_accounts
where report_group = 'default'
group by 1
order by 1 asc
;
----


You can now create the report:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     -H 'Content-Type: application/json' \
     -d '{"reportName": "new_accounts_per_day",
          "reportPrettyName": "New accounts created (per day)",
          "sourceTableName": "v_new_accounts_per_day"}' \
     http://127.0.0.1:8080/plugins/killbill-analytics/reports
----

Where:

* *reportName* is a unique identifier for your report
* *reportPrettyName* is a description, which will be used on the dashboards
* *sourceTableName* is the name of the source table (view in our case)


If the query is expensive, you should think of materializing it on a regular basis. Assuming you have a stored procedure *refresh_new_accounts_per_day* which materializes *v_new_accounts_per_day* into *new_accounts_per_day*, you can tell the Analytics plugin to run it on a daily basis at 4am GMT:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     -H 'Content-Type: application/json' \
     -d '{"reportName": "new_accounts_per_day",
          "reportPrettyName": "New accounts created (per day)",
          "sourceTableName": "new_accounts_per_day",
          "refreshProcedureName": "refresh_new_accounts_per_day",
          "refreshFrequency": "DAILY",
          "refreshHourOfDayGmt": 4}' \
     http://127.0.0.1:8080/plugins/killbill-analytics/reports
----


Or alternatively, you can run it on an hourly basis (it will run at 5' past the hour):

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     -H 'Content-Type: application/json' \
     -d '{"reportName": "new_accounts_per_day",
          "reportPrettyName": "New accounts created (per day)",
          "sourceTableName": "new_accounts_per_day",
          "refreshProcedureName": "refresh_new_accounts_per_day",
          "refreshFrequency": "HOURLY"}' \
     http://127.0.0.1:8080/plugins/killbill-analytics/reports
----


To retrieve your report configuration, use the report name:

[source,bash]
----
curl -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     http://127.0.0.1:8080/plugins/killbill-analytics/reports/new_accounts_per_day
----


To update it (you can edit all fields but the reportName one):

[source,bash]
----
curl -v \
     -X PUT \
     -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     -H 'Content-Type: application/json' \
     -d '{"reportPrettyName": "New accounts created (refreshed at 2am GMT)",
          "refreshFrequency": "DAILY",
          "refreshHourOfDayGmt": 2}' \
     http://127.0.0.1:8080/plugins/killbill-analytics/reports/new_accounts_per_day
----


Finally, to delete it:

[source,bash]
----
curl -v \
     -X DELETE \
     -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     http://127.0.0.1:8080/plugins/killbill-analytics/reports/new_accounts_per_day
----


You can download the data behind your report as csv or json:

[source,bash]
----
curl -u admin:password \
     -H "X-Killbill-ApiKey:bob" \
     -H "X-Killbill-ApiSecret:lazar" \
     'http://127.0.0.1:8080/plugins/killbill-analytics/reports?name=new_accounts_per_day&format=csv'
----


====== Dashboard API

To create a dashboard, go to http://127.0.0.1:8080/plugins/killbill-analytics/static/analytics.html[http://127.0.0.1:8080/plugins/killbill-analytics/static/analytics.html].

The dashboard system is controlled by query parameters:

* **report1**, **report2**, etc.: report name (from the configuration). The number determines in which slot the data should be displayed, starting from the top of the page. For example, report1=trials&report1=conversions&report1=cancellations&report2=accounts will graph the trials, conversions and cancellations reports in the first slot (on the same graph), and the accounts report below (in slot 2)
* **startDate** and **endDate**: dates to filter the data on the server side. For example: startDate=2012-08-01&endDate=2013-10-01
* **smooth1**, **smooth2**, etc.: smoothing function to apply for data in a given slot. Currently support smoothing functions are:
 * AVERAGE_WEEKLY: average the values on a weekly basis
 * AVERAGE_MONTHLY: average the values on a monthly basis
 * SUM_WEEKLY: sum all values on a weekly basis
 * SUM_MONTHLY: sum all values on a monthly basis
* To filter pivots from a report, use *!* for exclusions and *$* for inclusions. For example, report1=payments_per_day$AUD$EUR will graph the payments for AUD and EUR only, whereas report1=payments_per_day!AUD!EUR will graph all payments but the ones in AUD and EUR.

To continue with our example above, you can see the report by going to http://127.0.0.1:8080/plugins/killbill-analytics/static/analytics.html?report1=new_accounts_per_day[http://127.0.0.1:8080/plugins/killbill-analytics/static/analytics.html?report1=new_accounts_per_day].
