= Kill Bill and Bitcoin
Kill Bill core team <killbilling-users@googlegroups.com>
:doctype: book
:toc:
:toclevels: 6
:data-uri:
:linkcss!:
:imagesdir: userguide/assets
:source-highlighter: highlightjs
:homepage: http://kill-bill.org

Kill Bill is an open-source platform to build billing and payments services. Besides traditional payment methods (Credit and Debit cards, hosted payment gateways, checks, etc.), it does support Bitcoin as well. This guide will focus on how you can integrate Bitcoin with Kill Bill. For general information on the project, check our website http://kill-bill.org.

Lost? Questions? Reach out to our https://groups.google.com/forum/#!forum/killbilling-users[mailing-list]!

== Introduction

Kill Bill is currency and payment method agnostic. Our one-time and recurring payments APIs work around the concept of an account, which represents a person or a corporate entity, to which several payments methods (means of payment) are attached. An account can have a US AmericanExpress credit card, German Visa debit card, a hosted Blockchain.info wallet and a MultiBit Bitcoin wallet - all of these four payment methods are treated the same in Kill Bill, for the purpose of API calls parameters, invoices and payments objects, etc. This can happen because the gateway specific logic is handled in Kill Bill plugins, which plug into the platform via tightly controlled integration points.

For more information on Kill Bill's payments APIs and plugins, check our http://docs.kill-bill.org/payments.html[Payments guide].

The following guide assumes you already have an instance of Kill Bill running locally. To get started, check out our http://docs.kill-bill.org/userguide.html[Kill Bill in 5 minutes] guide.

=== Recurring payments

Supporting recurring payments is currently not easily feasable with Bitcoin, since it requires the merchant to have access to your wallet secret keys. While we do offer a work-around using https://coinbase.com/[Coinbase] (see below), we are working with the community to extend the https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki[Payment Protocol (BIP 70)] to add support for it. You can follow the discussion on the http://sourceforge.net/mailarchive/forum.php?thread_name=D6BCC0C4-EF22-4DE8-868E-825D19C387E3%40kill-bill.org&forum_name=bitcoin-development[bitcoin-development] mailing-list.

=== PENDING payment state

Usually in Kill Bill, a payment can be either in a success or failed status (the latter being terminal or not, if you configured your instance to retry failed payments). Due to the nature of the blockchain, a merchant often wants to wait several block confirmations (usually 6) before considering a payment successful (and before releasing goods or services). This transition period maps to the `PENDING` (unconfirmed) state in Kill Bill.

Our Bitcoin plugins will verify blockchain transactions (either directly on the blockchain or indirectly, through third-parties, depending on the plugin) and make sure each payment in Kill Bill will have one single matching transaction within the Bitcoin blockchain. It will then notify Kill Bill when the payment can be considered successfull based on heuristics that are configurable, such as the depth of the blocks where the transaction occurred.

== Pre-requisites

No matter how you plan on accepting Bitcoin, you'll need to create an account for your customer in Kill Bill:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey: bob' \
     -H 'X-Killbill-ApiSecret: lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"name":"john","email":"john@foo.com","externalKey":"11-22-33-44-55","currency":"BTC"}' \
     http://127.0.0.1:8080/1.0/kb/accounts
----

We'll assume the account id is f7b86b16-2770-48a6-9582-1b1413a0053c in the rest of this document.

Then, the account needs an associated payment method in the plugin.

For BitPay:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey: bob' \
     -H 'X-Killbill-ApiSecret: lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"pluginName":"killbill-bitpay","pluginInfo":{}}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/f7b86b16-2770-48a6-9582-1b1413a0053c/paymentMethods?isDefault=true"
----

For Coinbase:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey: bob' \
     -H 'X-Killbill-ApiSecret: lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"pluginName":"killbill-coinbase","pluginInfo":{}}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/f7b86b16-2770-48a6-9582-1b1413a0053c/paymentMethods?isDefault=true"
----

== Accepting Bitcoin through a third-party

=== BitPay

Our https://github.com/killbill/killbill-bitpay-plugin[BitPay plugin] is a wrapper around the http://activemerchant.org[ActiveMerchant] BitPay integration.

The direct payment flow is as follow:

* Using the Kill Bill `buildFormDescriptor` API call, create an invoice in BitPay
* Redirect the user to the hosted invoice page and/or embed the invoice in an iframe
* Upon success, BitPay will send a notification to Kill Bill which will mark the payment as successful

For more details on how to configure the invoice in BitPay, see https://bitpay.com/bitcoin-payment-gateway-api.

==== Installation

Download the http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.kill-bill.billing.plugin.ruby%22%20a%3A%22bitpay-plugin%22[latest version] of the plugin.

Copy the inflated artifacted to `/var/tmp/bundles/plugins/ruby/killbill-bitpay` and create the configuration file at `/var/tmp/bundles/plugins/ruby/killbill-bitpay/0.0.1/bitpay.yml`. Here's an example (make sure to replace `XXX` with your https://bitpay.com/api-keys[BitPay API key]):

[source,ruby]
----
:bitpay:
  :api_key: 'XXXX'
  :log_file: /var/tmp/bitpay.log

:database:
  :adapter: 'jdbc'
  :driver: 'com.mysql.jdbc.Driver'
  :username: 'killbill'
  :password: 'killbill'
  :url: 'jdbc:mysql://127.0.0.1:3306/killbill'
----

Finally, install the https://raw.githubusercontent.com/killbill/killbill-bitpay-plugin/master/db/ddl.sql[plugin DDL] to your `killbill` database.

==== Usage

Create the invoice in BitPay using the `buildFormDescriptor` API call (note that the only required fields are amount and currency):

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey: bob' \
     -H 'X-Killbill-ApiSecret: lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{
                        "formFields": [
                            {
                                "key": "amount",
                                "value": "0.0001"
                            },
                            {
                                "key": "currency",
                                "value": "BTC"
                            },
                            {
                                "key": "order_id",
                                "value": "INV0019483"
                            },
                            {
                                "key": "notify_url",
                                "value": "https://my-killbill.com:8080/1.0/kb/paymentGateways/notifications/killbill-bitpay"
                            },
                            {
                                "key": "return_url",
                                "value": "https://my-e-commerce.com/thank-you"
                            }
                        ]
                    }' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/hosted/form/f7b86b16-2770-48a6-9582-1b1413a0053c"
----

BitPay will notify Kill Bill via the `notify_url` parameter and update the payment status.

=== Coinbase

Our https://github.com/killbill/killbill-coinbase-plugin[Coinbase plugin] is a wrapper around the https://github.com/coinbase/coinbase-ruby[Coinbase Ruby gem].


==== Installation

Download the http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.kill-bill.billing.plugin.ruby%22%20a%3A%22coinbase-plugin%22[latest version] of the plugin.

Copy the inflated artifacted to `/var/tmp/bundles/plugins/ruby/killbill-coinbase` and create the configuration file at `/var/tmp/bundles/plugins/ruby/killbill-bitpay/0.0.1/coinbase.yml`. Here's an example (make sure to replace `XXX` with your https://coinbase.com/settings/api[Coinbase API key]):

[source,ruby]
----
:coinbase:
  # TODO
  :api_key:
  :client_id:
  :client_secret:
  :redirect_uri:
  :app_redirect_uri:
  :btc_address:
  :log_file: /var/tmp/coinbase.log

:database:
  :adapter: 'jdbc'
  :driver: 'com.mysql.jdbc.Driver'
  :username: 'killbill'
  :password: 'killbill'
  :url: 'jdbc:mysql://127.0.0.1:3306/killbill'
----

Finally, install the https://raw.githubusercontent.com/killbill/killbill-coinbase-plugin/master/db/ddl.sql[plugin DDL] to your `killbill` database.

==== Usage

TODO

==== Recurring payment

TODO

== Self-hosted blockchain

Alternatively, you can use our native https://github.com/killbill/killbill-bitcoin-plugin[Bitcoin plugin] to handle transactions yourself.

=== Overview

The plugin uses Bitcoinj to create a local wallet and runs in Simplified Payment Verification (SPV) mode.

The flow of operations can be summarized as follows: each time the plugin detects a new `PENDING` Bitcoin payment, it keeps track of that payment in its persistent tables (it keeps a mapping between the Kill Bill payment id and the blockchain transaction). When a new block is added to the blockchain, it checks to see if there is a `PENDING` payment that matches that BTC transactionId and it verifies if the payment can be considered valid (depending on the depth configuration). If it is, it notifies Kill Bill so that the payment status can be updated to `SUCCESS`.

=== Usage

TODO

=== Storing funds

Each plugin instance has its own instance of a wallet ; since we often run Kill Bill as a distributed service -- for robustness purpose, or to address needs of scaling horizontally -- that means that each node where Kill Bill runs has a different wallet, and the bitcoins in each wallet needs to be transferred to a well known (set of) public merchant keys. To address that issue, you can configure the plugin to periodically empty its wallet using a well known (set of) public keys (the interval, amount of money, etc. are configurable thresholds).
