One of the most powerful features of Kill Bill is its extensibility via plugins.

Here are a few examples of official plugins maintained by the Kill Bill core team:

* https://github.com/killbill/killbill-stripe-plugin[Stripe plugin], to use https://stripe.com[Stripe] as a payment gateway
* https://github.com/killbill/killbill-coinbase-plugin[Coinbase plugin], to use https://coinbase.com[Coinbase] as a payment gateway
* https://github.com/killbill/killbill-recurly-plugin[Recurly plugin], to use https://recurly.com[Recurly] as a payment gateway
* https://github.com/killbill/killbill-paypal-express-plugin[PayPal plugin], to use https://paypal.com[PayPal] as a payment gateway
* https://github.com/killbill/killbill-litle-plugin[Litle plugin], to use https://www.litle.com[Litle & co.] as a payment gateway
* https://github.com/killbill/killbill-logging-plugin[Logging plugin], to forward Kill Bill events to email, IRC, Syslog, ...
* https://github.com/killbill/killbill-bitcoin-plugin[Bitcoin plugin], to verify Kill Bill transactions on the block chain
* https://github.com/killbill/killbill-analytics-plugin[Analytics plugin], for Business Intelligence and create dashboards
* https://github.com/killbill/killbill-zendesk-plugin[Zendesk plugin], for mirroring Kill Bill accounts into https://zendesk.com[Zendesk]
* https://github.com/killbill/killbill-meter-plugin[Meter plugin], for metering (usage) billing

You can find more on our https://github.com/killbill[Github] project page. If you are interested in writing your own plugin, checkout our https://github.com/killbill/killbill-hello-world-java-plugin[hello world] example.

===== Bundles directory layout

Kill Bill looks for all plugins in a bundles directory, by default */var/tmp/bundles* (you can override it via the system property +org.killbill.osgi.bundle.install.dir+).

The expected layout is the following:

[source]
----
bundles/
  platform/
  plugins/
    ruby/
      ruby-plugin-a/
        ruby-plugin-a-version/
          killbill.properties
          gems/
      ruby-plugin-b/
        ruby-plugin-b-version/
          killbill.properties
          gems/
    java/
      java-plugin-a/
        java-plugin-a-version/
          plugin-a.jar
      java-plugin-b/
        java-plugin-b-version/
          plugin-b.jar
----

The +bundles/platform/+ directory is used for non Kill Bill specific OSGI plugins. For example, you can drop in it the http://felix.apache.org/site/apache-felix-web-console.html[Apache Felix Web Console] jar, and Kill Bill will automatically start it during its initialization sequence. https://github.com/killbill/killbill/tree/master/osgi-bundles/defaultbundles[Here] is a recommended set of convenience plugins to run.

Note that if you want to run Ruby plugins (see below), you need to place the +org.kill-bill.billing:killbill-platform-osgi-bundles-jruby+ artifact as +bundles/platform/jruby.jar+.

The plugins directory contains Kill Bill specific OSGI plugins, written either in Ruby or Java. Whereas only a jar is needed for Java plugins, the layout of Ruby plugins is a bit more complex. It expects a top level +killbill.properties+ file describing the type of plugin and special libraries to load, as well as a +gems/+ directory containing all the dependencies.

Fortunately, if you are using one of the official Ruby plugins, you don't need to worry about this. You can download http://search.maven.org/#search%7Cga%7C1%7Corg.kill-bill.billing.plugin.ruby[tar.gz packages] with the correct layout. Simply unpack them and restart Kill Bill.

If you want to develop your own Ruby plugin, check our instructions https://github.com/killbill/killbill-plugin-framework-ruby/wiki/Build-Release[here] and https://github.com/killbill/killbill-plugin-framework-ruby/wiki/How-to-vendor-a-plugin-gem-for-Killbill-deployment[here].
