==== Download the Tomcat container

If you don't have it yet, you can download the Tomcat container https://s3.amazonaws.com/kb-binaries/apache-tomcat-7.0.42.tar.gz[here]. You can then untar the archive and at this point you need to tweak the configuration before starting it. The setup suggested below is a quick setup used for demo, it may not be not best way to deploy your Kill Bill war into tomcat especially if you plan to have multiple wars within the same container.

==== Deploy Kill Bill in Tomcat

Assuming you installed tomcat in a directory called *CATALINA_HOME*, then there are two things that need to happen:

The Kill Bill system properties need to be added at the end of the *CATALINA_HOME/conf/catalina.properties*. The minimal set of system properties that need to added are the one for the jdbc parameters:

[source,java]
----
# Kill Bill properties
com.ning.jetty.jdbi.url=jdbc:mysql://127.0.0.1:3306/killbill
com.ning.jetty.jdbi.user=killbill
com.ning.jetty.jdbi.password=killbil
ANTLR_USE_DIRECT_CLASS_LOADING=true
----

A new entry must be added to let tomcat know about the location of the Kill Bill war. That file is called *Root.xml* and it must located under *CATALINA_HOME/conf/Catalina/localhost* (create the directories if they don't exist). Its content must be:

[source,xml]
----
<Context docBase="path_to_killbill-server.war">
</Context>
----

Once this is setup, you can start the tomcat container using the script *CATALINA_HOME/bin/startup.sh*. The server will be started in the background but logs can be followed at *CATALINA_HOME/logs/catalina.out*.
