=== Direct payments

A payment object is associated with a set of transactions (authorization, multiple catures, etc.). You can retrieve that object via:

[source,bash]
----
curl -v \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

==== Authorization

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"AUTHORIZE","amount":"10","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/directPayments"
----

This will return a direct payment object. We will assume its uuid is 078a4500-d15e-11e3-9c1a-0800200c9a66 in the example below.

For multi-steps authorization (e.g. 3DS), you can specify a directPaymentId field in the body for subsequent calls.

==== Capture

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"amount":"5","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

You can call this endpoint multiple times for partial captures (all of these captures will share the same direct payment id).

==== Purchase

This call is similar to the authorization one:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"PURCHASE","amount":"10","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/directPayments"
----


==== Void

[source,bash]
----
curl -v \
     -X DELETE \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

==== Credit

This call is similar to the capture one:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"amount":"5","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66/credits"
----

=== Hosted pages helpers

==== Build form descriptor

Given an order of $10, here is how you can get the HTML fields to build the form:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{ "formFields": [{ "key": "order_id", "value": "1234" }, { "key": "amount", "value": "10" }, { "key": "currency", "value": "USD" }]}' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/hosted/form/268983f2-5443-47e4-a967-b8962fc699c5
----

Kill Bill will lookup the plugin associated with the default payment method for that account, and in turn the plugin will build the fields expected by the gateway (some require a field called Sum instead of amount, etc.).


==== Process gateway notifications

Gateway notifications (Recurly push notificatoins, PayPal or BitPay IPN, etc.) can be processed through this API:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/notifications/killbill-paypal-express?customKey=value
----

The plugin will deserialize either the request body and/or the url query parameters to process the notification.