=== Overview

This section focues on writing your own plugins. Check our http://docs.kill-bill.org/userguide.html#_common_steps[deployment guide] for tips on how to deploy them.

=== Java payment plugins

To get started, check the https://github.com/killbill/killbill-hello-world-java-plugin[hello world Java plugin]. The https://github.com/killbill/killbill-plugin-api/blob/master/payment/src/main/java/org/killbill/billing/payment/plugin/api/PaymentPluginApi.java[plugin API] gives you the list of calls you can implement.

None are mandatory, not all will make sense with your gateway.


=== Ruby payment plugins

To get started, check the https://github.com/killbill/killbill-hello-world-ruby-plugin[hello world Ruby plugin]. The https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/payment.rb[plugin API] gives you the list of calls you can implement.

None are mandatory, not all will make sense with your gateway.

==== ActiveMerchant

The easiest way to get started with ActiveMerchant is to use our https://github.com/killbill/killbill-plugin-framework-ruby/[plugin generator]. It will create a skeleton plugin with most calls filled in. You just need to fill in the blanks or tweak certain behaviors specific for your gateway.

The https://github.com/killbill/killbill-stripe-plugin[Stripe plugin] is a good example for an ActiveMerchant gateway implementation, whereas the https://github.com/killbill/killbill-bitpay-plugin[BitPay plugin] shows how to deal with ActiveMerchant integrations.