=== Direct Payments APIs

A payment object is associated with a set of transactions (authorization, multiple captures, etc.). You can retrieve that object via:

[source,bash]
----
curl -v \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

==== Authorization

To create an authorization on the default payment method of the account:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"AUTHORIZE","amount":"10","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/directPayments"
----

This will return a direct payment object. We will assume its uuid is 078a4500-d15e-11e3-9c1a-0800200c9a66 in the examples below.

Notes:

* For multi-steps authorization (e.g. 3DS), you can specify a *directPaymentId* field in the body for subsequent calls
* You can specify another payment method (other than the default one) via the *kbPaymentMethodId* query parameter

==== Capture

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"amount":"5","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

Notes:

* You can call this endpoint multiple times for partial captures (all of these captures will share the same direct payment id)

==== Purchase

This call is similar to the authorization one:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"PURCHASE","amount":"10","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/directPayments"
----

Notes:

* You can specify another payment method (other than the default one) via the *kbPaymentMethodId* query parameter

==== Void

[source,bash]
----
curl -v \
     -X DELETE \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

==== Credit

This call is similar to the capture one:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"amount":"5","currency":"USD"}' \
     "http://127.0.0.1:8080/1.0/kb/directPayments/078a4500-d15e-11e3-9c1a-0800200c9a66/credits"
----

=== Hosted pages helpers

[[build-form-descriptor]]
==== Build form descriptor

The *build form descriptor* call is used when you need to prepare a payment form. There are two main scenarii:

* The payment form is hosted on your own website, but the gateway requires custom hidden fields and visible fields need special names. In that case, the plugin simply returns the list of fields with their expected name (e.g. *Sum* field for the order amount, hidden *merchantId* field, etc.)
* The payment form is hosted on the gateway website. In that case, the plugin builds a unique URL to redirect the user to by either:
** submitting the order information (amount, etc.) to the gateway which returns the location of the hosted payment form
** constructing the special URL via query parameters

Given an order of $10, here is how you can get the HTML fields to build the form:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{ "formFields": [{ "key": "order_id", "value": "1234" }, { "key": "amount", "value": "10" }, { "key": "currency", "value": "USD" }]}' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/hosted/form/268983f2-5443-47e4-a967-b8962fc699c5
----

Kill Bill will lookup the plugin associated with the default payment method for that account, and in turn the plugin will build the fields expected by the gateway.

Notes:

* You can specify another payment method (other than the default one) via the *kbPaymentMethodId* query parameter

[[gateway-notification]]
==== Process gateway notifications

Gateway notifications (Recurly push notifications, PayPal or BitPay IPN, etc.) can be processed through this API:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/notifications/pluginName?customKey=value
----

Make sure to replace *pluginName* by your plugin name (e.g. killbill-bitpay).

The plugin will deserialize either the request body and/or the url query parameters to process the notification and return a properly formatted HTTP response object for the gateway (some gateways require specific reponse codes or headers to consider the notification processed and prevent retries).
