In this tutorial, we've shown you how to leverage the basic features of the Kill Bill platform, how to provide recurring and one-off billing, as well as integrate with various payment processors. Kill Bill has many more features to offer, make sure to read the http://killbill.io/userguide/[user guide].

=== Next steps: exercises for the reader

If you want to continue the exercise, here are some exercies:

* Setup Kaui. Kaui is the Kill Bill Administrative UI. It can be used as an internal tool to visualize subscriptions, handle refunds, add credits, perform payments, etc. (Hint: KPM can handle it for you)
* Configure the overdue system. What happens when premium subscribers don't pay?
* Setup the Analytics plugin to create revenue dashboards and monitor your MRR.
* Defer authorize and capture: if you are shipping physical goods, you are required to defer capture only when the product ships.
* Add a second plan, with a discounted yearly pricing and try to upgrade/downgrade users between plans.
