To accept credit cards, we will integrate with https://stripe.com[Stripe]: they offer free sandbox accounts and provide a nice dashboard to follow what's going on. Choosing your payment processor is critical however, you need to make sure it offers the features you need (international payments, etc.) while minimizing your costs. Luckily, there are thousands of vendors available and Kill Bill can integrate with pretty much any of them, so make sure to do your research.

Another word of caution is regarding PayPal: the setup is a bit complicated and their UI glitchy unfortunately. You can follow along this tutorial even if you don't have yet your credentials (you just won't be able to test payments end-to-end).

==== Stripe

* Create a free account at https://stripe.com[stripe.com]
* Go to your https://dashboard.stripe.com/account/apikeys[API Key Settings]
* Write down the Test Secret Key

==== PayPal

* Create a free account at https://developer.paypal.com[paypal.com]
* Go to your https://developer.paypal.com/webapps/developer/applications/account[Dashboard] and click Create Account
* Fill-in some details and add some fake money (PayPal balance field)
* Repeat and create one Personal and one Business account

You then need to contact support so they can enable recurring payments on your sandbox:

* Go to https://ppmts.custhelp.com[PayPal Technical Support]
* Create a ticket and ask to "Enable reference transactions for the Sandbox account XXXXX". Replace XXX with the API username of the Business test account you created (to see the username, click on Profile in the dashboard under the email address of the account, then click on the API credentials tab)

This process can take up to 48 hours. In the meantime, while you will be able to test one-time purchases, you won't be able to test recurring transactions in PayPal.