==== Usage Modes

Kill Bill supports billing customers based on their usage data, and the pricing schemes for this billing are defined in the Kill Bill catalog.
The `Plan` section of the catalog can contain one or several `usage` section(s) to define how customers will be billed.
These sections can be defined in addition to other, non usage based, billing schemes, such as fixed or recurring price.

Each usage section will need to specify a `billingMode`.
The only billing mode supported today is the `IN_ARREAR` mode, which allows customers to be billed based on usage data from previous periods.
We plan to add the `IN_ADVANCE` mode in the future to support prepaid scenarios such as toll bridge pass, where the customer purchases a
certain number of units *in advance* and such units are decremented as the customer uses the service.

Each usage section will also need to specify a `usageType` and along with it, specify the `unit` (types) for which the customer is being billed, such as cell phone/minutes.
The usage type can be one of the following:

* `CONSUMABLE` : This is used for defining prices that are based on the number of units (of a certain types) being consumed -- e.g water consumed in the last period. 
* `CAPACITY` : This is used for defining prices that are based on rates or upper bound values. In this scheme, we bill based on the maximum value that was seen over the period -- e.g MBytes/sec

The following http://killbill.io/blog/usage-billing[ blog post] provides additional context about these use cases.

For each usage section, we support defining pricing *tiers*, allowing customers to be billed differently based on their usage.
These tiers work differently depending on the usage type, `CONSUMABLE` or `CAPACITY`.

Each usage section also needs to define the `billingPeriod` -- e.g `MONTHLY` -- to define how often and for which period consumers are being billed.

===== Consumable In Arrear Mode

In this mode, each `tier` definition contains a `tieredBlock` that defines the limits and price associated with a particular `unit` type. We support two `TierBlockPolicy` policies:

* `ALL_TIER`: This policy charges users across each tier based on their usage. Higher prices are charged to the less preferred tier. This may be a lower tier, e.g for cloud usage where we want to reward users who consume more, or a higher tier, e.g for an electric bill where we want to encourage users to consume less.
* `TOP_TIER`: With this policy we still go through each tier, but everything is charged at the top tier pricing. Here it makes sense to offer lower pricing for the top tier, since this is a rewarding model.


===== Consumable In Arrear Mode: `ALL_TIER`

To demonstate the `ALL_TIER` policy, let's start with an example of a `tieredBlock` definition. The following tier block section defines the pricing for the `cell-phone-minutes` unit, and can be understood the following way:

[source,bash]
----
<tieredBlock>
    <unit>cell-phone-minutes</unit>
    <size>10</size>
    <prices>
        <price>
            <currency>EUR</currency>
            <value>1.00</value>
        </price>
    </prices>
    <max>100</max>
</tieredBlock>
----

* This defines a block of size `10`, where each block is priced at 1.00 EUR
* The first `100` blocks of this size will be priced at 1.00 EUR
* If a consumer uses more than `100` blocks of this size, he will be charged at the price of the next tier.

As mentioned previously, each usage section can contain multiple tiers and also charge for multiple unit types.
The following section shows the defintion for 2 units, *cell-phone-minutes* and *Mbytes*, and defines two tiers.
The `max` value for the last tier is defined with *-1* which represents an unbounded value:

[source,bash]
----
<tiers>
    <tier>
        <blocks>
            <tieredBlock>
                <unit>cell-phone-minutes</unit>
                <size>10</size>
                <prices>
                    <price>
                        <currency>EUR</currency>
                        <value>1.00</value>
                    </price>
                </prices>
                <max>100</max>
            </tieredBlock>
            <tieredBlock>
                <unit>Mbytes</unit>
                <size>1</size>
                <prices>
                    <price>
                        <currency>EUR</currency>
                        <value>0.5</value>
                    </price>
                </prices>
                <max>1024</max>
            </tieredBlock>
        </blocks>
    </tier>
    <tier>
        <blocks>
            <tieredBlock>
                <unit>cell-phone-minutes</unit>
                <size>10</size>
                <prices>
                    <price>
                        <currency>EUR</currency>
                        <value>0.50</value>
                    </price>
                </prices>
                <max>-1</max>
            </tieredBlock>
            <tieredBlock>
                <unit>Mbytes</unit>
                <size>1</size>
                <prices>
                    <price>
                        <currency>EUR</currency>
                        <value>0.1</value>
                    </price>
                </prices>
                <max>-1</max>
            </tieredBlock>
        </blocks>
    </tier>
</tiers>
----

In the `CONSUMABLE` mode, when defining a usage section with multiple unit (types), it is important to realize that the consumer *is charged independently
for each unit*. For example, with the definition provided above, and given the following usage data for the period:

* 1500 cell-phone-minutes
* 2048 Mbytes

The total amount would be 739.4. This is calculated as follows:

cell-phone-minutes:

* Tier 1: 100 blocks of size 10 at 1 EUR => 100 EUR
* Tier 2: 50 blocks of size 10 at 0.5 EUR => 25 EUR

Mbytes

* Tier 1: 1024 blocks of size 1 at 0.5 EUR => 512
* Tier 2: 1024 blocks of size 1 at 0.1 EUR => 102.4

Total: 100 + 25 + 512 + 102.4 = 739.4


For more information on this model, see our http://docs.killbill.io/latest/consumable_in_arrear.html[tutorial].


===== Consumable In Arrear Mode: `TOP_TIER`

Using the same example from the previous section with the `TOP_TIER` policy would lead to a different result, since all charges would be calculated at the higher tier:

* cell-phone-minutes: 150 blocks of size 10 at 0.50 EUR = 150 * 0.5 = 75
* Mbytes: 2048 blocks of size 1 at 0.10 EUR = 2048 * 0.1 = 204.8

So the total amount would be 279.8.

===== Capacity In Arrear Mode

In the `CAPACITY` mode, each `tier` definition contains a list of `limit`, specifying the maximum value for this tier for each `unit` (type). *In contrast to the `CONSUMABLE` mode, the billing happens across the units*. Let's assume the following definition for one tier, with 2 different types of units, `bandwith-meg-sec` and `members`:

[source,bash]
----
<tier>
   <limits>
       <limit>
           <unit>bandwith-meg-sec</unit>
           <max>100</max>
       </limit>
       <limit>
           <unit>members</unit>
           <max>500</max>
       </limit>
   </limits>
   <recurringPrice>
       <price>
           <currency>EUR</currency>
           <value>5.00</value>
       </price>
   </recurringPrice>
</tier>
----

Given the following usage data for the period:

* `bandwith-meg-sec`: A peak of 50 in the period
* `members`: A peak of 350 active members in the period

The user would be charged 5.00 EUR.

However if the `members` peak data was 501, this would move to the next tier -- not shown for simplicity.

So, in this model, the peak data for each unit is used to *define which tier to use*, and based on the tier we simply apply the pricing defined. 
