The catalog is the central configuration object of Kill Bill for all of your Business rules. It contains what the customer buys (products), how the customer pays for a product (plans), change rules, prices, etc.

In practice, the catalog is an XML file: https://github.com/killbill/killbill/blob/45fe9209ed2419b639d3472fc24dae87637d84b5/profiles/killbill/src/test/resources/org/killbill/billing/server/SpyCarBasic.xml[here] is a basic example we use in most of our tests and tutorials. We also have a few other examples to get you started https://github.com/killbill/killbill-docs/tree/v3/catalogs[here].

Please refer to the Catalog Configuration documentation to make Kill Bill use your own catalog.

The catalog is one of the most complex yet powerful tools provided by Kill Bill.

If you want to validate your catalog, you can use the catalog load-tool (where x.y.z is your current Kill Bill version):

[source,bash]
----
# Download the tool from maven central:
curl -L -O 'http://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-catalog/x.y.z/killbill-catalog-x.y.z-load-tool.jar'
# Run the command
java -jar killbill-catalog-*-load-tool.jar /path/to/catalog.xml
----

If you see "Success: Catalog loads!", the catalog is valid.

Also, if you need an xsd file, you can find one http://docs.killbill.io/latest/catalog.xsd[here] or generate one using the catalog xsd-tool:

[source,bash]
----
# Download the tool from maven central:
curl -L -O 'http://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-catalog/x.y.z/killbill-catalog-x.y.z-xsd-tool.jar'
# Run the command
java -jar killbill-catalog-*-xsd-tool.jar schema.xsd
----
