image:https://drive.google.com/uc?&id=0Bw8rymjWckBHcU9DbnVkY1FhR2M&w=960&amp;h=480[align=center]
// https://drive.google.com/file/d/0Bw8rymjWckBHcU9DbnVkY1FhR2M/view?usp=sharing

The Catalog is at the heart of the billing system.
It is a data model that captures the core configuration of the billing system.
It is very important that all the business logic associated with the billing behaviour of your system is captured in the billing system.
If your billing system is not capable of capturing that business logic it ends up being put in multiple places such as your purchase flow, Admin UI, human process etc.
It becomes very difficult to keep all these places consistent, and very difficult to make changes when they are needed.

Kill Bill provides a very powerful catalog that, unlike other billing systems, allows the administrator to set up sophisticated business rules around cancellation and plan changes.
For example, Kill Bill can just be told to “Cancel” a plan and Kill Bill can know when to perform the cancel, based on things like the type of plan, or whether it is in trial.

The things you can configure with the Kill Bill catalog include:

* Trials and discount phases - plans can be configured with trial and discount phases so that they move automatically between different pricing schemes
* Cancellation - business rules to determine when a cancellation should happen.
* Plan Change - business rules to determine when to apply upgrades and downgrades.
* Which add-ons are available with which products types, so that when the customer upgrades or downgrades add-ons that are not available are automatically cancelled
* Billing Alignment - rules to determine if a Plan should be billed independently or on the account billing date.
* Catalog change - ways to specify how and when catalog changes apply to new and existing subscriptions

Kill Bill also supports the concept of a Price List, which is a grouping of (usually discounted) plans that can be offered to a customer.

Of course, any catalog can only support a finite number of options. When you need to go further, and many people do, you can write plugins to implement pretty much anything you need.


==== Concepts

In this section we outline some key pieces of terminology that you will need to understand.
Different billing systems use these same words to mean subtly different things so, even if you are familiar with the language, it is worth looking though exactly how we use the terms in Kill Bill.

===== Background Concepts

* *Customer* – someone who buys your product
* *Administrator* (or *Admin*) – the person who can use the Kill Bill UI to view and modify customer accounts
* *Kill Bill Administrator* (or *Kill Bill Admin*) - the person responsible for installing or configuring Kill Bill
* *Account* – a customer account. It represents what Kill Bill knows about a customer.
* *Subscription* – a Subscription is a contract between you and a customer to purchase a particular product with particular terms. In the system it associates a Plan (see below) with an Account and a start date.
* *Subscription Bundle* (or just *Bundle*) – Is a collection of subscriptions that are associated with a particular instance of a product. For example, you might have a voice plan, a data plan and a text plan for your mobile phone. In Kill Bill each plan would have its own subscription and we would represent the fact that they are associated with a single phone by grouping them in a Subscription Bundle. Of course an account might have multiple phones associated with it and a Kill Bill Account can have multiple Bundles associated with it.

==== What’s in a Catalog?

Writing a Kill Bill Catalog involves defining of the following pieces:

* *Products* - the product is the thing that the customer actually buys (or rents). In the example depicted at the start of the chapter, the product available for rent is a Spy Car. There are actually three different products available, `Standard`, `Sports` and `Super`.
* *Plans* - Plans specify the terms of the Subscription contract. In particular, they define, how much a customer pays for a product, and how often they pay it. For example, we could offer the Standard Spy Car product at $100 per month.
* *Plan Phase* (or just *Phase*) - Kill Bill plans can have multiple phases and each phase can have a different price and payment term. In this way, we can have plans with built in trials or discount phases. Kill Bill automatically handles the transitions between phases. In our example above the plans have two phases, they start with a 30 day trial which is free and then move to a recurring phase at $100 per month.
* *Price List* - A price list is a collection of plans. Price Lists are normally used to group discount plans that are associated with a particular customer group. For example, MI6 might have a special rental terms for their Spy Cars with the C.I.A. In which case they would create a C.I.A. Price List that grouped plans with those special terms together. When C.I.A. Agents come to the rental site, they will see plans from that price list. More importantly if they change plans, for example, if they upgrade from Sports to Super to meet the needs of a particularly difficult mission, they will upgrade to the Sports plan within the C.I.A. Price List.
* *Billing Period* - The periodicity for when the customer is billed (e.g `MONTHLY`, `ANNUAL`, ...)
* *BillCycleDay (BCD)* - The day in the month when the invoicing for a particular subscription happens. This only makes sense for recurring subscriptions whose `Billing Period` is a multiple of the month. For other schemes (e.g. `WEEKLY`). the day will vary for each invoice, in which case there is no `BCD` defined. 
* *Rules* - The catalog rules determine the behaviour that Kill Bill should display when a plan is created, cancelled or changed.


==== How is the Catalog Used Inside Kill Bill?

The catalog is first used by Kill Bill at the time the user creates a subscription, then subsequently if there is change of `Plan` (upgrade, downgrade), and then finally when the user cancels the subscription. During such operations, Catalog information is retrieved to make sure the system builds the right subscription (e.g. maybe there is a `TRIAL` phase to start). Information about **how** to perform such operations is configured in the catalog through the http://docs.killbill.io/0.16/userguide_subscription.html#_subscription_alignment_rules[Subscription Alignment Rules]. An overview of some of these rules:

* **Plan Cancellation Timing** - Should the customer get a pro-ration credit when the subscription is cancelled before its next renewal date?
* **Plan Change Timing** - Should a customer downgrading to a lower (paid) plan be active immediately or should the system wait for the next renewal date?


The catalog is also used by the invoicing system to make sure each each `Customer` is billed at the right time and for the right amount. Information about **how** the customer is billed and **when** the customer is billed is also defined in the catalog using alignments and their associated rules.

Catalog configuration allows to define if different subscriptions attached to a customer should be invoiced at the same time, or at the opposite if they should be billed separately on their own schedule (or a mix of both where some are grouped together on the same invoice and others are invoiced independently). In the simplest case, where all subscriptions are grouped together and there is a `BCD` defined (`Billing Period` is a multiple of the month), the customer gets one invoice per `Billing Period` on that (`BCD`) day. Note that grouping subscriptions together may by default lead to some leading pro-ration when the subscription is started on a different date than the `BCD` (as the system needs to realign invoicing on that particular date). This behavior is configured in the catalog through the http://docs.killbill.io/0.16/userguide_subscription.html#_billing_alignment_rules[Billing Alignment Rules].


==== Catalog Documentation

Where do you go from here to learn more:

* Basic Catalog Tutorial - how to create a simple three tier catalog with simple rules
* Advanced Catalog Tutorial - enhancing the Basic Catalog Example with add-ons, discount plans, complex rules and catalog changes
