The invoice payment table is the bridge between the invoice and payment subsystems, and is used to compute invoice balances. It will contain the payments, refunds and chargebacks made against an invoice.

If an invoice doesn't have any corresponding row in invoice payment, this means the invoice isn't paid (either because no payment was ever attempted, or the payment attempts weren't successful).

A successful payment against an invoice would have a single row (of type ATTEMPT):

[cols=4, options="header"]
|===
|Invoice #
|Type
|Payment date
|Amount

|1029
|ATTEMPT
|2013-04-12 22:45:39
|$20
|===

==== Refund

Here is how a payment, followed by a refund would look like:

[cols=4, options="header"]
|===
|Invoice #
|Type
|Payment date
|Amount

|1029
|ATTEMPT
|2013-04-12 22:45:39
|$20

|1029
|REFUND
|2013-04-18 10:23:11
|$-20
|===

==== Chargeback

Here is how a payment, followed by a chargeback would look like:

[cols=4, options="header"]
|===
|Invoice #
|Type
|Payment date
|Amount

|1029
|ATTEMPT
|2013-04-12 22:45:39
|$20

|1029
|CHARGED_BACK
|2013-04-18 10:23:11
|$-20
|===
