= How to Maintain a Single-Tier System

== Overview

This guide explains how to maintain your single-tier Kill Bill installation on AWS.

== Log in

To perform most maintenance tasks you will need to log in to your EC2 instance. Be sure that SSH is enabled on Port 22 in your security group. Login procedures are described in the setup guide  (See https://docs.killbill.io/latest/how-to-set-up-a-single-tier-system.html#step_7_login_to_your_instance[Step 7: Login to an Instance])


== Troubleshooting

If a new installation does not seem to work correctly, the first step is to review your installation process carefully, to be sure that everything has been done and checked as described in the https://docs.killbill.io/latest/how-to-set-up-a-single-tier-system[setup guide]. If problems persist, we will be glad to work with you to identify the problem. To help us to do this, there are several information reports that you may need to gather. These reports are somewhat technical but can be analyzed by Kill Bill personnel. This section explains how to obtain the reports that may be needed.

=== Status Reports

include::{sourcedir}/aws/includes/status-reports.adoc[]

=== Log Files

The system maintains a series of log files that may be helpful when troubleshooting is needed. These logs may be forwarded to Kill Bill to help diagnose your problem.

include::{sourcedir}/aws/includes/logs.adoc[]

=== System Health Check

include::{sourcedir}/aws/includes/healthcheck.adoc[]

=== System Information

include::{sourcedir}/aws/includes/system-information.adoc[]

=== Diagnostic Command

include::{sourcedir}/aws/includes/diagnostics.adoc[]

=== Databases

To access the mysql (MariaDB) databases, you can use the following command:

`mysql -u root -proot`

include::{sourcedir}/aws/includes/database.adoc[]

=== Load Balancer

The load balancer `nginx` should normally require little attention. The configuration files are located under `/etc/nginx/`. The configuration file for `nginx` itself is `/etc/nginx/nginx.conf`. Additional configuration files are located under `/etc/nginx/sites-enabled/`. The only file normally present in this directory is `/etc/nginx/sites-enabled/killbill.conf`.


Nginx logs can be found under `/var/log/nginx/`

* Access logs: `/var/log/nginx/access.log`
* Error logs: `/var/log/nginx/error.log`

== Configuration

include::{sourcedir}/aws/includes/configuration.adoc[]

== Upgrades

include::{sourcedir}/aws/includes/upgrade.adoc[]

== SSL Certificate

The KB single tier AMI comes pre-configured with a self-signed certificate. This can be found at `/etc/nginx/ssl/ssl-cert-snakeoil.pem` (public key) and `/etc/nginx/ssl/ssl-cert-snakeoil.key` (private key). Some backend systems might not trust this certificate, leading to SSL related failures. There are two possible solutions:

1. You can update the backend to trust KB's self-signed certificate. This involves configuring the backend application to trust the certificate. For instance, if your backend is using Java, you can add KB's certificate to the truststore.
2. If you prefer not to modify the backend, you can obtain a valid certificate from a Certificate Authority. This certificate would be automatically trusted by most clients without requiring any additional configuration in your backend application. Let’s Encrypt is a root CA that is free to use. See https://docs.killbill.io/latest/using-https#_using_lets_encrypt_with_certbot[Using Let's Encrypt].