= How to Maintain a Single-Tier System

== Overview

This guide explains how to maintain your single-tier Kill Bill installation on AWS.

== Log in

To perform most maintenance tasks you will need to log in to your EC2 instance. Be sure that SSH is enabled on Port 22 in your security group. Login procedures are described in the setup guide  (See https://docs.killbill.io/latest/how-to-set-up-a-single-tier-system.html#step_7_login_to_your_instance[Step 7: Login to an Instance])


== Troubleshooting

If a new installation does not seem to work correctly, the first step is to review your installation process carefully, to be sure that everything has been done and checked as described in the https://docs.killbill.io/latest/how-to-set-up-a-single-tier-system[setup guide]. If problems persist, we will be glad to work with you to identify the problem. To help us to do this, there are several information reports that you may need to gather. These reports are somewhat technical but can be analyzed by Kill Bill personnel. This section explains how to obtain the reports that may be needed.

=== Status Reports

When you launch the EC2 instance,  all required services should be enabled and running, including:

* An instance of `nginx` receiving traffic on port `443` and `8443`
* An instance of Kill Bill server listening on `127.0.0.1:8080` (and receiving external traffic through nginx on port `8443`)
* An instance of Kaui listening on `127.0.0.1:3000` (and receiving external traffic through nginx on port `443`)
* A local `mysql` server running on port `3306`

The status of nginx/KB/mysql services can be checked by the following commands:

* Kill Bill service: `sudo service killbill status`
* Nginx service: `sudo service nginx status`
* Mysql service: `sudo service mysql status`

For each report there should be a line near the top with the following form:

`Active: active (running) since Sat 2020-10-24 20:13:43 UTC; 1 day 1h ago`

You can `start` or `stop` the services using similar commands, such as `sudo service killbill stop` to stop Kill Bill. If any service is not active, try starting it using the appropriate command.

If all services are running, the next step is to collect several reports.

=== Log Files

The system maintains a series of log files that may be helpful when troubleshooting is needed. These logs may be forwarded to Kill Bill to help diagnose your problem.

include::{sourcedir}/aws/includes/logs.adoc[]

=== System Health Check

include::{sourcedir}/aws/includes/healthcheck.adoc[]

=== System Information

include::{sourcedir}/aws/includes/system-information.adoc[]

=== Diagnostic Command

include::{sourcedir}/aws/includes/diagnostics.adoc[]

=== Databases

To access the mysql (MariaDB) databases, you can use the following command:

`mysql -u root -proot`

include::{sourcedir}/aws/includes/database.adoc[]

=== Load Balancer

The load balancer `nginx` should normally require little attention. The configuration files are located under `/etc/nginx/`. The configuration file for `nginx` itself is `/etc/nginx/nginx.conf`. Additional configuration files are located under `/etc/nginx/sites-enabled/`. The only file normally present in this directory is `/etc/nginx/sites-enabled/killbill.conf`.


Nginx logs can be found under `/var/log/nginx/`

* Access logs: `/var/log/nginx/access.log`
* Error logs: `/var/log/nginx/error.log`

== Configuration

include::{sourcedir}/aws/includes/configuration.adoc[]

== Upgrades

include::{sourcedir}/aws/includes/upgrade.adoc[]

== SSL Certificate

The KB single tier AMI comes pre-configured with a self-signed certificate. This can be found at `/etc/nginx/ssl/ssl-cert-snakeoil.pem` (public key) and `/etc/nginx/ssl/ssl-cert-snakeoil.key` (private key). Some backend systems might not trust this certificate, leading to SSL related failures. There are two possible solutions:

1. You can update the backend to trust KB's self-signed certificate. This involves configuring the backend application to trust the certificate. For instance, if your backend is using Java, you can add KB's certificate to the truststore.
2. If you prefer not to modify the backend, you can obtain a valid certificate from a Certificate Authority. This certificate would be automatically trusted by most clients without requiring any additional configuration in your backend application. Let’s Encrypt is a root CA that is free to use. See https://docs.killbill.io/latest/using-https#_using_lets_encrypt_with_certbot[Using Let's Encrypt].