= How to Maintain a Multi-Tier System

== Overview

This guide explains how to maintain your multi-tier Kill Bill installation on AWS. The procedures described in this guide apply separately to each of your EC2 instances.

== Log in

To perform most maintenance tasks you will need to log in to your EC2 instances. Be sure that SSH is enabled on Port 22 in your security group. Login procedures are described in the setup guide  (See https://docs.killbill.io/latest/how-to-set-up-a-multi-tier-system.html#_4_5_login_to_an_instance[4.5. Login to an Instance]).


== Troubleshooting

If a new installation does not seem to work correctly, the first step is to review your installation process carefully, to be sure that everything has been done and checked as described in the https://docs.killbill.io/latest/how-to-set-up-a-multi-tier-system[setup guide]. If problems persist, we will be glad to work with you to identify the problem. To help us to do this, there are several information reports that you may need to gather. These reports are somewhat technical but can be analyzed by Kill Bill personnel. This section explains how to obtain the reports that may be needed.

=== Log Files

The system maintains a series of log files that may be helpful when troubleshooting is needed. These logs may be forwarded to Kill Bill to help diagnose your problem.

include::{sourcedir}/aws/includes/logs.adoc[]

=== Status Reports

include::{sourcedir}/aws/includes/status-reports.adoc[]

=== System Health Check

include::{sourcedir}/aws/includes/healthcheck.adoc[]

=== System Information

include::{sourcedir}/aws/includes/system-information.adoc[]
      
=== Diagnostic Command

include::{sourcedir}/aws/includes/diagnostics.adoc[]


=== Databases

To access the RDS database, you can use the following command:

`mysql -h<db-writer-endpont> -u<db-username> -p<db-password>`

Replace `<db-writer-endpont>` with the DB writer endpoint and `<db-username>/<db-password>` with the database credentials obtained during the setup (https://docs.killbill.io/latest/how-to-set-up-a-multi-tier-system#_2_2_create_the_database_manager[Step 2.2]).

include::{sourcedir}/aws/includes/database.adoc[]

== Configuration

include::{sourcedir}/aws/includes/configuration.adoc[]

== Upgrades

include::{sourcedir}/aws/includes/upgrade.adoc[]
