= Getting Started

This document explains what you need to get started using Kill Bill in your chosen environment. The first step is installing Kill Bill itself and the Kaui administrative console, along with their required database, in the environment you will be using. Make sure you read the  https://docs.killbill.io/latest/what_is_kill_bill.html[overview] to familiarize yourself with some concepts prior moving forward.

[[installation]]
== Kill Bill Installation

There are several different ways to get Kill Bill and Kaui up and running. The packages can be installed on your local computer (Windows, Mac, or Linux) or on a Linux server in the cloud. The three principal options are:

1. Use our one-click installer to install the programs using a ready-to-run container on a fresh AWS Ubuntu instance that you provide
2. Install Docker on your local machine or a new or existing cloud server instance. Then install Kill Bill and Kaui in a Docker container.
3. Install Kill Bill and Kaui, together with a MySQL database, directly on an Apache Tomcat server in your chosen environment.

These options are discussed in the subsequent sections.

== AWS (One-Click)
include::{sourcedir}/getting-started/includes/aws.adoc[]


== Docker
include::{sourcedir}/getting-started/includes/docker.adoc[]

== Tomcat

include::{sourcedir}/getting-started/includes/tomcat.adoc[]

== Next steps

Create your first tenant, simple catalog, account, payment method, and subscription by following the steps in the either of these guides:

* https://docs.killbill.io/latest/quick_start_with_kaui.html[_Quick Start with Kaui_] 
* https://docs.killbill.io/latest/quick_start_with_kb_api.html[_Quick Start with the Kill Bill API_]

Explore our full https://killbill.github.io/slate/[API documentation].

We also have lots of examples in our https://github.com/killbill/killbill-integration-tests[Ruby] and https://github.com/killbill/killbill/tree/master/profiles/killbill/src/test/java/org/killbill/billing/jaxrs[Java] integration tests.

For support along the way, do *not* open GitHub issues. Instead, reach out to our https://groups.google.com/forum/#!forum/killbilling-users[Google Group]. Our +++<a href="https://github.com/sponsors/killbill" onclick="getOutboundLink('https://github.com/sponsors/killbill'); return false;">GitHub sponsors</a>+++ can also jump on our VIP community Slack channel.
