Kill Bill maintains a reporting schema that is kept current in realtime for Analytics purposes. In contrary to other tables in the system, this set of tables is stable and potentially changes only between major revisions of Kill Bill. These tables are meant to be used as building blocks for reports and dashboards.

This analytics feature is provided as a Kill Bill https://github.com/killbill/killbill-analytics-plugin[plugin]. To install it, simply install the killbill-osgi-bundles-analytics jar to */var/tmp/bundles/platform/* (or to your custom OSGI bundles directory if you have overridden the default path) and run the following DDL https://raw.githubusercontent.com/killbill/killbill-analytics-plugin/master/src/main/resources/org/killbill/billing/plugin/analytics/ddl.sql[script].

For ease of tracking, Analytics objects contain id references to the Kill Bill ones but we strongly advise against using them for reporting purposes. Instead, use the external keys as much as possible, as they are tied to your business concepts. For instance, to count the number of accounts in the system, run a query using *count(distinct account_key)*, not *count(distinct account_id)*.

Data has been denormalized on purpose to avoid joins as much as possible.

=== Internals

This plugin listens to events generated by Kill Bill, and rebuild the complete state of its mirrored data upon receipt. The refresh jobs (one created per event) are kept in a notification queue. By default, it uses the same notification queue tables as the system, but we encourage you to use separate ones. To do so, set the following properties (the tables have been created by the provided ddl script):

[source,bash]
----
org.killbill.notificationq.analytics.tableName=analytics_notifications
org.killbill.notificationq.analytics.historyTableName=analytics_notifications_history
----

These jobs are kept in the *refresh-queue* queue of the *AnalyticsService* service. For debugging purposes, search key 1 is the account record id and search key 2 is the tenant record id.
