= Kill Bill and Kaui Configuration Guide

Kill Bill supports configuring the system by specifying external properties. This document explains how such properties can be configured.

== Kill Bill Configuration

=== Overview

At a high level, Kill Bill configuration can be done in one of the following ways:

* *Per-tenant configuration* - Used to define tenant-specific configuration properties (such as Catalog/Overdue XML files, Invoice, Payment properties, etc.).
* *Properties file* - Used to define properties global to the system. 
* *Java System Properties* - Used to define certain "special" configuration properties. 
* *Third Party Configuration Files* -  Can be used to specify third-party configuration (e.g. EhCache configuration file, logback configuration file, etc. 
* *Environment variables* - Can also be used to define configuration properties. 

The subsequent sections elaborate each of these approaches.

=== Per Tenant Properties

Per tenant properties refers to properties that can be specified at a tenant level. Thus, each tenant can have different values for these properties.

Such properties are stored in the Kill Bill database and can be set by invoking the https://killbill.github.io/slate/#tenant-add-a-per-tenant-system-properties-configuration[_uploadPerTenantConfig_] endpoint.

For instance to set the invoice dry run notification schedule for the  `boblazar` tenant, you can invoke the endpoint as follows:

[source]
----
curl -v \
     -X POST \
     -u 'admin:password' \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: text/plain" \
     -H "X-Killbill-CreatedBy: configurator" \
     -d '{"org.killbill.invoice.dryRunNotificationSchedule":"48h"}' \
     "http://127.0.0.1:8080/1.0/kb/tenants/uploadPerTenantConfig"
----

This sets `org.killbill.invoice.dryRunNotificationSchedule=48h` for the `boblazar` tenant.

*Important Notes:*

* Each call overwrites previous properties, so it is necessary to specify the full list of properties for a given tenant. 
* These properties can also be specified in the killbill properties file in which case they become global properties applicable to all tenants. 
* If a property is specified in the properties file as well as at a per-tenant level, the per-tenant configuration takes precedence.

The <<configuration_properties_table, "Configuration Properties Table">> below lists all the per tenant properties.

[[global_configuration_properties]]
=== Properties File

Kill Bill configuration properties can also be defined within an explicit `.properties` file. Properties defined within this file are global and are applicable across all tenants. Typically, a default `killbill.properties` exists as explained in the <<setup_specific_notes, "Setup Specific Notes">> section. You can add new properties/modify property values in this file as required. 

The <<configuration_properties_table, "Configuration Properties Table">> below lists all the global properties.

=== Environment Variables

Kill Bill also allows setting configuration properties via environment variables. In such a case, the value specified via the environment variable overrides the value defined in the `killbill.properties` file. 

In order for environment variables to be enabled, you need to set the following property in the property file:
[source,bash]
----
org.killbill.server.lookupEnvironmentVariables=true
----

Once enabled, you can define an environment variable corresponding to any property by prefixing the property name with *KB_*. For example, you can define an environment variable corresponding to the `org.killbill.dao.url` property as follows:
[source,bash]
----
KB_org_killbill_dao_url = <jdbc URL here>
----

The <<configuration_properties_table, "Configuration Properties Table">> below lists all the environment variables.

[[system_properties]]
=== Java System Properties 

Certain "special" configuration properties need to be specified as Java system properties and cannot be specified in the `properties` file or as environment variables. Typically, you would not need to modify such properties. 

The <<configuration_properties_table, "Configuration Properties Table">> below lists all the system properties.

=== Third Party Configuration Files

Third party configuration files can be used to specify configuration related to third party libraries like ehcache, logback, etc. The path of a third party configuration file in turn needs to be specified as a configuration property.

The following table lists the third party configuration files supported by Kill Bill and their corresponding configuration properties.

[options="header",cols="1,1,1"]
|===
|Third-Party Configuration   |Configuration Property   |Default Location
//----------------------
|ehcache   |org.killbill.cache.config.location   |https://github.com/killbill/killbill/blob/2b80b0445c7baf1f613425bb236a8cb36f1f377a/util/src/main/resources/ehcache.xml[ehcache.xml]   
|logback   |logback.configurationFile|https://github.com/killbill/killbill/blob/2b80b0445c7baf1f613425bb236a8cb36f1f377a/profiles/killbill/src/main/resources/logback.xml[logback.xml]   
|shiro |org.killbill.security.shiroResourcePath |https://github.com/killbill/killbill/blob/2b80b0445c7baf1f613425bb236a8cb36f1f377a/profiles/killbill/src/main/resources/shiro.ini[shiro.ini]   
|===

[[configuration_properties_table]]
== Configuration Properties Table

The following table lists all the Kill Bill configuration properties.

include::{sourcedir}/platform/includes/killbill-configuration-properties-table.adoc[]


=== Persistent Bus/Notification Queue Configuration Notes

Note that the *Persistence Bus* and *Notification Queue* configuration properties use a substitution parameter called `instanceName`. This is because the properties defined here are built to be used across multiple instances. Kill Bill typically uses two persistent buses named `main` and `external` and one notification queue named `main`. Thus, `instanceName` needs to be replaced with these instance names while specifying these properties.

[[setup_specific_notes]]
=== Setup Specific Notes

As explained in the https://docs.killbill.io/latest/getting_started.html[_Getting Started_] guide, there are several ways to install Kill Bill. In addition, you may also be using Kill Bill for development/debugging using a https://docs.killbill.io/latest/development.html[_standalone_] setup.

This section provides some setup specific instructions such as location of the default `killbill.properties` and so forth.

==== AWS

In case of an https://docs.killbill.io/latest/getting_started.html#_aws_one_click[__AWS__] installation, the `killbill.properties` is present at the  `/var/lib/killbill/config/killbill.properties` location.

==== Docker

In case of a https://docs.killbill.io/latest/getting_started.html#_docker[__Docker__] installation, the `killbill.properties` file is present at the `/var/lib/killbill/killbill.properties` path within the Docker container.  You can modify the properties defined here. 

Alternatively, you can bind mount your own file, by specifying `-v /path/to/killbill.properties:/var/lib/killbill/killbill.properties` when starting your container.

You can also specify configuration properties using individual environment variables as specified in the <<configuration_properties_table, "Configuration Properties Table">> above.

==== Tomcat/Jetty

In case of a https://docs.killbill.io/latest/getting_started.html#_tomcat[__Tomcat Installation__], the <<global_configuration_properties, global configuration properties>>  and <<system_properties, system properties>> need to be specified within the `TOMCAT_HOME/conf/catalina.properties` file.

In case of a https://docs.killbill.io/latest/development.html#_running_the_application[__Standalone Jetty Setup__], configuration properties need to be specified within an explicit  `killbill.properties` file. Its path needs to be specified via the `org.killbill.server.properties` Java system property while starting the application as follows:

[source,bash]
----
mvn -Dorg.killbill.server.properties=file:///PROJECT_ROOT/profiles/killbill/src/main/resources/killbill-server.properties
----

== Kaui Configuration

In addition to Kill Bill, Kaui can also be configured via some configuration properties. These can either be set as system properties or environment variables. Note that in case of a Tomcat installation, system properties can be specified in the `catalina.properties` file.

The following table lists the Kaui Configuration properties. 

include::{sourcedir}/platform/includes/kaui-configuration-properties-table.adoc[]