[[deployment]]
== Deployment

When deploying Kill Bill to a production environment, you'll likely want to use your own container and deploy Kill Bill as a war. Below are instructions for various containers. If you're unsure which one to use and/or don't have any preference, we recommend Jetty.

=== Common steps

==== Download the latest version of Kill Bill server

Releases are available in Maven Central. Among other packaging formats, we provide a war with all dependencies. You can get the latest version http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.kill-bill.billing%22%20AND%20a%3A%22killbill-profiles-killbill%22%20AND%20p%3A%22war%22[here] (download the *war* artifact).

==== Setup the database

Note: currently, only MySQL is supported for multi-nodes deployments.

Create the database killbill will use and apply the latest DDL schema, which can be found http://docs.kill-bill.org/schema.html[here].


[[deployment-plugins]]
==== Install plugins

include::platform/deployment-plugins.adoc[]


[[deployment-jetty]]
=== Installation in Jetty

include::platform/deployment-jetty.adoc[]


[[deployment-tomcat]]
=== Installation in Tomcat

include::platform/deployment-tomcat.adoc[]


[[deployment-glassfish]]
=== Installation in Glassfish

include::platform/deployment-glassfish.adoc[]