= Aviate Catalog Guide

== Introduction

The https://aviate.killbill.io[Aviate Catalog UI] allows you to create individual catalog entries such as products, plans, and pricelists.
This provides much finer granularity than the Kill Bill open-source model, which requires creating a new catalog version for any change. As a result, this approach is more dynamic and scales significantly better when managing a large number of catalog entries.
Internally, the UI uses the https://apidocs.killbill.io/aviate-catalog[Aviate Catalog APIs].

== Create Product,Plan, Pricelist

To create a product, plan, and pricelist:

. Open the *Create Product, Plan, Pricelist* screen.
. Enter the product name (e.g., `netflix`).
. Define a plan (e.g., `netflix-basic-monthly`).
. Set the price (e.g., `$10` per month).
. Save your entries.


Demo:

:storylane-id: elbar7il3dvs
:storylane-embed-type: popup
include::{sourcedir}/includes/storylane-embed.adoc[]

API Used: https://apidocs.killbill.io/aviate-catalog#create-plan-product-pricelist[Create Plan, Product, Pricelist API].

== Add New Plan

Once a product exists, you can add additional plans:

. Select the product (e.g., `netflix`).
. Create a new plan (e.g., `netflix-premium-monthly`).
. Configure phases such as `DISCOUNT` or `EVERGREEN`.
. Save the plan.


Demo:

:storylane-id: h0mwfwocymqr
:storylane-embed-type: popup
include::{sourcedir}/includes/storylane-embed.adoc[]

API used: https://apidocs.killbill.io/aviate-catalog#create-plan[Create Plan API].

[[edit_plan]]
== Edit Plan

The edit plan feature allows you to update plan prices after a plan is created. Note that Other attributes (like *phase duration*) cannot be changed.

[NOTE]
Editing a plan creates a new version of the plan. Existing subscriptions continue to use the old plan. See https://docs.killbill.io/latest/userguide_subscription#_catalog_versions[docs].

. Select the plan (e.g., `netflix-basic-monthly`).
. Adjust the price.
. Save changes.


Demo:

:storylane-id: 4unxvpnzucbe
:storylane-embed-type: popup
include::{sourcedir}/includes/storylane-embed.adoc[]

API used: https://apidocs.killbill.io/aviate-catalog#modify-plan[Modify Plan API].

== Archive Plan

You can archive an existing plan. Archiving prevents creating new subscriptions corresponding to the plan.
The plan remains active for existing subscriptions.

. Select the plan (e.g., `Netflix Usage Monthly`).
. Choose *Archive*.
. Confirm the action.


Demo:

:storylane-id: p10rv35qaed9
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]

API used: https://apidocs.killbill.io/aviate-catalog#retire-plan[Retire Plan API].

== Delete Plan

You can delete an existing plan permanently. Deleting permanently removes the plan from the database.

WARNING: Deleting a plan could break the system if there are active subscriptions. Use this only for plans created erroneously that do not have active subscriptions.

. Select the plan.
. Choose *Delete*.
. Confirm deletion.


Demo:

:storylane-id: 2mzetbzl440n
:storylane-embed-type: popup
include::{sourcedir}/includes/storylane-embed.adoc[]

API used: https://apidocs.killbill.io/aviate-catalog#delete-plan[Delete Plan API].

== Delete Product

You can delete an existing product permanently. Deleting permanently removes the product from the database.

WARNING: Deleting a product could break the system if there are active subscriptions. Use this only for products created erroneously that do not have active subscriptions.

. Select the product.
. Choose *Delete*.
. Confirm deletion.


Demo:

:storylane-id: ju6wzojzj4ib
:storylane-embed-type: popup
include::{sourcedir}/includes/storylane-embed.adoc[]

== Duplicate Plan

You can create a new plan based on an existing plan.

[NOTE]
The *Duplicate Plan* feature is a time-saving convenience that lets you quickly create a new plan. When duplicating, all plan attributes can be edited and on saving,a new plan is created.
By contrast, the <<edit_plan, Edit Plan>> feature is limited to updating prices only, and each change automatically generates a new version of the plan.

. Select the plan
. Choose *Duplicate*
. Make changes to the plan as desired
. Save the new plan.

Demo:

:storylane-id: vbzqz7fq9y5q
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]

== Duplicate Product

You can create a new product based on an existing product. This is a time-saving convenience that lets you quickly create a new product

. Select the product
. Choose *Duplicate*
. Make changes to the product and its plans as desired
. Save the new product.

Demo:

:storylane-id: m2kja9avscji
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]

== Creating Usage Plans

Usage plans allow billing based on consumption. See https://docs.killbill.io/latest/userguide_subscription#components-catalog-usage[docs].

. Define a https://apidocs.killbill.io/aviate-metering#billingmeter[billing meter] (how usage is tracked).
. Configure *blocks/tiers*.
. Assign usage-based prices to each block.
. Save the plan.


Demo:

:storylane-id: wst70zfovkue
:storylane-embed-type: popup
include::{sourcedir}/includes/storylane-embed.adoc[]

API used: https://apidocs.killbill.io/aviate-catalog#create-plan[Create Plan API].


== Conclusion

You now know how to:

* Create products, plans, and pricelists
* Add new plans
* Edit plan prices
* Archive plans
* Delete plans/products
* Duplicate plans/products
* Build usage-based plans



