= Aviate Catalog Guide

== Introduction

The http://aviate.killbill.io[Aviate Catalog UI] allows you to create individual catalog entries such as products, plans, and pricelists.
This means you don’t need to manage entire catalog versions.
Internally, the UI uses the https://apidocs.killbill.io/aviate-catalog[Aviate Catalog APIs].

== Create Product,Plan, Pricelist

The Create Product, Plan, Pricelist screen can be used to create a product, plan, and pricelist.

You can refer to the following demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/elbar7il3dvs?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

The above demo creates a new product called `netflix` with a `netflix-basic-monthly` plan that is priced at `$10` per month.

This UI internally uses the https://apidocs.killbill.io/aviate-catalog#create-plan-product-pricelist[Create Plan, Product, Pricelist API].

== Add New Plan

Once a product is created, you can add new plans at any time.

You can refer to the following demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/h0mwfwocymqr?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

The above demo creates a new plan called `netflix-premium-monthly` corresponding to the `netflix` product. It has a `DISCOUNT` and `EVERGREEN` phase.

The UI internally uses the https://apidocs.killbill.io/aviate-catalog#create-plan[Create Plan API].

== Edit Plan

The Aviate Catalog  UI allows modifying plan prices after a plan is created. Note that only plan prices can be modified, other plan attributes like duration of the phases, etc. are not allowed to be changed.

You can refer to the following demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/4unxvpnzucbe?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

The above demo modifies the prices of the `netflix-basic-monthly` plan.

The UI internally uses the https://apidocs.killbill.io/aviate-catalog#modify-plan[Modify Plan API].

== Archive Plan

The Aviate Catalog UI allows archiving a plan. When a plan is archived, it is no longer possible to create new subscriptions corresponding to the plan. Existing subscriptions continue to work.

You can refer to the following demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/p10rv35qaed9?embed=inline" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

The above demo archives the `Netflix Usage Monthly` plan.

The UI internally uses the https://apidocs.killbill.io/aviate-catalog#retire-plan[Retire Plan API].

== Delete Plan

The Aviate Catalog UI allows deleting a plan permanently. Note that deleting a plan hard deletes it from the database and will affect existing subscriptions. This operation should only typically be performed on plans created erroneously to which there are no subscriptions.

//You can refer to the following demo:

//The above demo deletes the `temp` plan.

The UI internally uses the https://apidocs.killbill.io/aviate-catalog#delete-plan[Delete Plan API].



== Creating Usage Plans

The Aviate Catalog  UI also allows creating usage plans. So you can define a billing meter (which encapsulates how usages are aggregated), define blocks/tiers in the usage plan, and add usage based prices corresponding to these blocks.

You can refer to the following demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/wst70zfovkue?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

//TODO Delete Plan/Product

//TODO Duplicate Plan/Product

== Conclusion

You now know how to:

* Create products, plans, and pricelists
* Add new plans
* Edit plan prices
* Archive or delete plans
* Build usage-based plans



