= Aviate Catalog Guide

== Introduction

The https://aviate.killbill.io[Aviate Catalog UI] allows you to create individual catalog entries such as products, plans, and pricelists.
This provides much finer granularity than the Kill Bill open-source model, which requires creating a new catalog version for any change. As a result, this approach is more dynamic and scales significantly better when managing a large number of catalog entries.
Internally, the UI uses the https://apidocs.killbill.io/aviate-catalog[Aviate Catalog APIs].

== Create Product,Plan, Pricelist

To create a product, plan, and pricelist:

. Open the *Create Product, Plan, Pricelist* screen.
. Enter the product name (e.g., `netflix`).
. Define a plan (e.g., `netflix-basic-monthly`).
. Set the price (e.g., `$10` per month).
. Save your entries.


Demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/elbar7il3dvs?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

API Used: https://apidocs.killbill.io/aviate-catalog#create-plan-product-pricelist[Create Plan, Product, Pricelist API].

== Add New Plan

Once a product exists, you can add additional plans:

. Select the product (e.g., `netflix`).
. Create a new plan (e.g., `netflix-premium-monthly`).
. Configure phases such as `DISCOUNT` or `EVERGREEN`.
. Save the plan.


Demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/h0mwfwocymqr?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

API used: https://apidocs.killbill.io/aviate-catalog#create-plan[Create Plan API].

[[edit_plan]]
== Edit Plan

The edit plan feature allows you to update plan prices after a plan is created. Note that Other attributes (like *phase duration*) cannot be changed.

[NOTE]
Editing a plan creates a new version of the plan. Existing subscriptions continue to use the old plan. See https://docs.killbill.io/latest/userguide_subscription#_catalog_versions[docs].

. Select the plan (e.g., `netflix-basic-monthly`).
. Adjust the price.
. Save changes.


Demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/4unxvpnzucbe?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

API used: https://apidocs.killbill.io/aviate-catalog#modify-plan[Modify Plan API].

== Archive Plan

You can archive an existing plan. Archiving prevents creating new subscriptions corresponding to the plan.
The plan remains active for existing subscriptions.

. Select the plan (e.g., `Netflix Usage Monthly`).
. Choose *Archive*.
. Confirm the action.


Demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/p10rv35qaed9?embed=inline" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

API used: https://apidocs.killbill.io/aviate-catalog#retire-plan[Retire Plan API].

== Delete Plan

You can delete an existing plan permanently. Deleting permanently removes a plan from the database.

WARNING: Deleting a plan could break the system if there are active subscriptions. Use this only for plans created erroneously that do not have active subscriptions.

. Select the plan.
. Choose *Delete*.
. Confirm deletion.


//Demo:

API used: https://apidocs.killbill.io/aviate-catalog#delete-plan[Delete Plan API].

== Duplicate Plan

You can create a new plan based on an existing plan.

[NOTE]
The *Duplicate Plan* feature is a time-saving convenience that lets you quickly create a new plan. When duplicating, all plan attributes can be edited and on saving,a new plan is created.
By contrast, the <<edit_plan, Edit Plan>> feature is limited to updating prices only, and each change automatically generates a new version of the plan.

. Select the plan
. Choose *Duplicate*
. Make changes to the plan as desired
. Save the new plan.

Demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/vbzqz7fq9y5q?embed=inline" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++



== Creating Usage Plans

Usage plans allow billing based on consumption. See https://docs.killbill.io/latest/userguide_subscription#components-catalog-usage[docs].

. Define a https://apidocs.killbill.io/aviate-metering#billingmeter[billing meter] (how usage is tracked).
. Configure *blocks/tiers*.
. Assign usage-based prices to each block.
. Save the plan.


Demo:

++++
<div>
  <script async src="https://js.storylane.io/js/v2/storylane.js"></script>
  <div class="sl-embed" style="position:relative;padding-bottom:calc(49.85% + 25px);width:100%;height:0;transform:scale(1)">
    <iframe loading="lazy" class="sl-demo" src="https://killbill.storylane.io/demo/wst70zfovkue?embed=popup" name="sl-embed" allow="fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
  </div>
</div>
++++

API used: https://apidocs.killbill.io/aviate-catalog#create-plan[Create Plan API].

//TODO Delete Plan/Product

//TODO Duplicate Plan/Product

== Conclusion

You now know how to:

* Create products, plans, and pricelists
* Add new plans
* Edit plan prices
* Archive or delete plans
* Duplicate plans
* Build usage-based plans



