= Aviate Deployment Management

This guide explains how to add/manage a custom  Kill Bill deployment in the https://aviate.killbill.io[Aviate UI].

== Prerequisites

* Access to the https://aviate.killbill.io[Aviate UI] with a valid Flock account.
* A running Kill Bill instance accessible from your network.
* Administrative credentials for your Kill Bill instance (API key, API secret, and admin user credentials).

== Add a Local Deployment

You can add a local deployment to Aviate by providing the connection details (URL and credentials) for your Kill Bill instance. This allows you to manage your Kill Bill instance directly from the Aviate UI.

Once a deployment is added, Aviate allows you to perform a wide range of management actions, including but not limited to:

* Installing and managing plugins
* Creating and managing product plans and catalogs
* Configuring plugins and their properties
* Uploading and managing invoice templates
* Setting and updating tenant properties
* Monitoring deployment status and plugin health

Refer to the following demo for a walkthrough of the process to add a local deployment in Aviate:

:storylane-id: uamhutfpgj7q
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]

== Add a Tenant to an Existing Deployment

You can also add a new tenant to an existing deployment. This allows you to manage multiple tenants within the same Kill Bill instance from Aviate.

Refer to the following demo for a walkthrough of the process to add a tenant to an existing deployment in Aviate:

:storylane-id: 83wimvrsbani
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]

== Edit the Deployment

You can edit the deployment details (e.g., URL, credentials, etc.) at any time from the Aviate UI. This is useful if you need to update the connection information or credentials for your Kill Bill instance.

Refer to the following demo for a walkthrough of the process to edit a deployment in Aviate:

:storylane-id: itb3ko5nt4lq
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]

== Delete the Deployment

You can delete a deployment from the Aviate UI if you no longer want to manage it through Aviate.

Refer to the following demo for a walkthrough of the process to delete a deployment in Aviate:


:storylane-id: zgsvpxse48pe
:storylane-embed-type: inline
include::{sourcedir}/includes/storylane-embed.adoc[]
