= What Is Aviate?

include::{sourcedir}/aviate/includes/aviate-card.adoc[]

== About Aviate
Aviate is designed to deliver a seamless billing experience that builds upon the core capabilities of Kill Bill. Our goal is to provide users with advanced features that cover the entire quote-to-cash lifecycle, including enhanced system observability, streamlined configurations, and valuable business intelligence.

== Beta Program Access
As part of the Beta program, you'll have access to early feature releases directly on https://aviate.killbill.io[aviate.killbill.io]. This platform will continue to evolve with new functionalities aimed at making billing management easier and more powerful.

== Aviate Plugin
For Beta customers, we offer the *Aviate plugin*. This plugin extends Kill Bill with additional endpoints specifically for the Beta phase, allowing early access to some of Aviate's backend features. These endpoints are detailed in the *Aviate section* below.

NOTE: Only users on the Flock plan and higher can download and install the plugin. Free/Entourage users can use the plugin in their sandbox deployment; however, they cannot download the plugin in their local environment.

Please refer to the documentation below to start integrating Aviate into your Kill Bill environment.
