[[overdue]]
=== Overdue Module

The Overdue module in Kill Bill relies on a configuration file which drives its behavior. The file is specifed through the use of the `org.killbill.overdue.uri` system property. The Overdue module listens to payment events and then, based on the configuration it transitions the overdue state for an account to the appropriate state. Whether the payment was a failure or not, the Overdue module will recompute the state associated to the account and potentially make the transition to another state.


The overdue configuration contains a list of the various states through which a customer who does not pay will go through. Each state has a `name` and a `condition` which is evaluated by the `Overdue` module. Currently the condition to transition to a given state is based on the properties below, and the system will https://github.com/killbill/killbill/blob/master/overdue/src/main/java/org/killbill/billing/overdue/config/DefaultCondition.java[evaluate to true if all the part of the conditions are true]. The names of the properties are fairly explicit:

* numberOfUnpaidInvoicesEqualsOrExceeds
* totalUnpaidInvoiceBalanceEqualsOrExceeds
* timeSinceEarliestUnpaidInvoiceEqualsOrExceeds
* responseForLastFailedPaymentIn
* responseForLastFailedPayment
* controlTag

In addition the definition of a overdue state, will also specify some ways to alter the behavior of the system:

* subscriptionCancellationPolicy: Whether ot cancel the subscriptions associated with the account (and the cancelation policy that should be used). By default no cancellation is performed.
* blockChanges: Specifies whether the customer is allowed to make any plan change on his subscriptions
* disableEntitlementAndChangesBlocked ???

Finally, one can add an `externalMessage` which can be retrieved by plugins listening to Overdue events.
