Tomcat/KB/Kaui logs are under `/var/lib/tomcat/logs/`:

* Kaui log: `/var/lib/tomcat/logs/kaui.out`
* Kill Bill server log: `/var/lib/tomcat/logs/killbill.out`
* Complete tomcat log: `/var/lib/tomcat/logs/catalina.out`
* Access requests to the servers: `localhost_access_log*.txt`

Sometimes these logs will clearly show anomalies that will pinpoint the problem. If not you should forward your logs to Kill Bill for review.Some of these logs may be very large, especially catalina.out.

=== Logging Configuration

The logging configuration, including settings for log rotation and log levels, is defined in the `logback.xml file`. Separate `logback.xml` files are used for KB and Kaui, located at the following paths:

* KB logback file: `/var/lib/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml`
* Kaui logback file: `/var/lib/tomcat/webapps2/ROOT/WEB-INF/classes/logback.xml`

These files can be modified to customize the logging settings for KB and Kaui. By default, the log level is configured as `INFO`.

