From time to time new versions of Kill Bill are released. These versions can be incorporated in your installation with minimal impact on production. This section explains how to upgrade to a new version of Kill Bill. Note that these are *not* the same as new versions of the AMI, which can be incorporated only by a full re-installation.

You can upgrade KB using the following steps:

1. Log in to your instance using `ssh`.

2. Switch to the `tomcat` user:
+
[source,bash]
----
sudo su - tomcat
----
+
3. Update `/var/lib/killbill/kpm.yml` with the appropriate KB version. For example, to upgrade to KB `0.24.9`, update this file as follows:
+
[source,yaml]
----
killbill:
  version: 0.24.9
  plugins:
  plugins_dir: /var/lib/killbill/bundles
  webapp_path: /var/lib/tomcat/webapps/ROOT.war
----
4. Delete the cached `webapps/ROOT` directory:
+
[source,bash]
----
rm -rf /var/lib/tomcat/webapps/ROOT
----
+
5. Run the following command to update KB:
+
[source,bash]
----
$KPM_INSTALL_KB_CMD
----
+
6. Restart KB:
+
[source,bash]
----
sudo service killbill restart
----

You can upgrade Kaui using the following steps:

1. Log in to your instance using `ssh`.

2. Switch to the `tomcat` user:
+
[source,bash]
----
sudo su - tomcat
----
+
3. Update `/var/lib/kaui/kpm.yml` with the appropriate Kaui version. For example, to upgrade to Kaui `3.0.6`, edit this file as follows:
+
[source,yaml]
----
kaui:
  version: 3.0.6
  # Used for the sha1.yml
  plugins_dir: /var/lib/kaui/bundles
  webapp_path: /var/lib/tomcat/webapps2/ROOT.war
----
+
4. Delete the cached `webapps2/ROOT` directory:
+
[source,bash]
----
rm -rf /var/lib/tomcat/webapps2/ROOT
----
+
5. Run the following command to update Kaui:
+
[source,bash]
----
$KPM_INSTALL_KAUI_CMD
----
+
6. Restart KB:
+
[source,bash]
----
sudo service killbill restart
----
