Let's take the case of a customer that subscribed to the service. Immediately after the subscription was created a $0 invoice is created to indicate the customer is in TRIAL. Let's assume his credit card does not have enough funds. 10 days later the customer moves out of TRIAL and the system generates a $10 invoice for the month. At this point, the system attempts to make a payment, but the payment does not go through:

* Day 1: the system will retry the payment one day later and fail again
* Day 2: the system will retry the payment one day later and fail again
* Day 10: the system will retry (one last time) the payment 8 days later and fail again; at this point the overdue system will transiton the account into a `WARNING` state

=== Bad Customer

Let's assume this is a bad customer, that will not update his credit card:

* Day 14: the customer moves to a `BLOCKED` state; the system will stop invoicing, and will indicate that the customer is not entititled to receiving service any longer (more details below)
* Day 21: the system will cancel the subscription (final state)

=== Good Customer

Let's assume this is a good customer, and after the WARNING, he updates his credit card:

* Day 15: customer updates credit card and pays his unpaid invoice(s) (more details below). The system brings back the overdue status to `CLEAR`.
