= Kill Bill on AWS

== Introduction

Running Kill Bill on AWS using our official CloudFormation template is the easiest and fastest way to get started. *It is also the only method of installation that is certified by the core developers for a Highly Available, horizontally scalable and production-ready installation.*

With the click of a button, the template will install and configure:

* Kill Bill and Kaui on a custom AMI optimized for AWS workloads (integrated with CloudWatch, SQS, SES, X-Ray and more)
* Auto Scaling Groups, to automatically scale up and down the number of instances as needed (such as when batches of invoices are generated)
* A load balancer, integrated with our internal healthchecks to promptly take out of rotation unhealthy instances
* A RDS Aurora Cluster with automatic failover

Kill Bill comes with the Analytics and Stripe plugins pre-configured: you get a subscription billing management solution as feature-rich as popular SaaS platforms, but you are in control.

== Installation

For installation support along the way, reach out to `support@killbill.io`.

=== Configuration options

The installation supports the following configuration options:

* *VpcId:* the VPC to use for the installation. In your AWS Console, go to *Services* and search for *VPC*. Under *Your VPCs*, locate the VPC ID you would like to use or create a new one.
* *Subnets:* the subnets to use, associated with at least two different availability zones. In the VPC Dashboard, go to *Subnets* and find two subnets in your VPC *in two different availability zones*. Alternatively, create new ones (use 10.0.0.0/24 and 10.0.1.0/24 as the IPv4 CIDR for instance).
* *KeyName:* name of an existing EC2 KeyPair to enable SSH access to the instances. You can create a new one by going to *Key Pairs* in your EC2 Dashboard.
* *HTTPLocation:* IP address range allowed to access the load balancer (you can always use 0.0.0.0/0 initially and adjust access later on).
* *EnvType:* environment purpose (test, prod, etc.)
* *InstanceType:* the EC2 instance type to use for Kill Bill. Here are some guidelines:
** `m5.large`: test environment
** `c5.xlarge`: up to 5,000 subscriptions
** `c5.2xlarge`: up to 50,000 subscriptions
** `c5.4xlarge`: beyond 50,000 subscriptions
* *KillBillServerCapacity:* the initial number of Kill Bill instances in the Auto Scaling group. Here are some guidelines:
** `1`: test environment
** `2`: up to 5,000 subscriptions
** `3`: up to 50,000 subscriptions
** `4`: beyond 50,000 subscriptions
* *KauiServerCapacity:* the initial number of Kaui instances in the Auto Scaling group. We recommend using the default value `2`.
* *DBClass:* the database instance type to use for RDS. Here are some guidelines:
** `db.t3.medium`: test environment
** `db.r5.xlarge`: up to 5,000 subscriptions
** `db.r5.2xlarge`: up to 50,000 subscriptions
** `db.r5.4xlarge`: beyond 50,000 subscriptions
* *DBName:* database name for Kill Bill. We recommend using the default value *killbill*.
* *KauiDBName:* database name for Kaui. We recommend using the default value *kaui*.
* *DBUser:* database admin username
* *DBPassword:* database admin password
* *EnableCloudWatchMetrics:* whether to record Kill Bill metrics in CloudWatch. Strongly recommended for production. When enabled, a default monitoring dashboard will be created.

=== Setup steps

1. Start the installation process and populate the configuration options in the CloudFormation form.
2. Launch the stack.
3. Upon success, the Outputs tab will display the load balancer URL. Kill Bill is available on port 80 while Kaui on port 9090.

You can log-in to Kaui by going to http://<LOAD_BALANCER_URL>:9090 (make sure your IP address can access the load balancer, as defined by the parameter `HTTPLocation`, or add it to the security group as needed). Default credentials are: admin/password.

=== Upgrade steps

The Kill Bill core team will provide new AMIs whenever necessary.

Because the CloudFormation from AWS Marketplace will always reflect the latest AMI ids, you can simply update the stack with the latest CloudFormation template and the instances in the AutoScaling groups will be updated automatically.

We strongly recommend to always test the upgrade in a test environment first.

== Stripe integration

Kill Bill on AWS comes pre-bundled with our Stripe plugin.

=== Configuration

Go to https://dashboard.stripe.com/test/apikeys and copy your `Secret key`.

Then, go to the Kaui plugin configuration page (`/admin_tenants/1?active_tab=PluginConfig`), and configure the `stripe-pro` plugin with your key:

[source,bash]
----
com.killbill.billing.plugin.stripe.apiKey=sk_test_XXX
----

=== Payment Method flow

To charge a payment instrument (card, bank account, etc.), you first need to collect the payment instrument details in Stripe and create an associated payment method in Kill Bill.

==== Using Stripe Checkout

_Use this method if you don't want to generate your own form to tokenize cards._

To save credit cards using https://stripe.com/docs/payments/checkout[Stripe Checkout]:

1. Create a Kill Bill account
2. Call `/plugins/killbill-stripe-pro/checkout` to generate a Session:
+
[source,bash]
-----
curl -v \
     -X POST \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -H "X-Killbill-Reason: demo" \
     -H "X-Killbill-Comment: demo" \
     "http://<ELB_ADDRESS>/plugins/killbill-stripe-pro/checkout?kbAccountId=<KB_ACCOUNT_ID>"
-----
3. Redirect the user to the Stripe checkout page. The `sessionId` is returned as part of the `formFields` (`id` key):
+
[source,javascript]
-----
stripe.redirectToCheckout({ sessionId: 'cs_test_XXX' });
-----
4. After entering the credit card, a $1 authorization will be triggered. Call `addPaymentMethod` to create the Stripe payment method and pass the `sessionId` in the plugin properties. This will void the authorization (if successful) and store the payment method in Kill Bill:
+
[source,bash]
-----
curl -v \
     -X POST \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -H "X-Killbill-Reason: demo" \
     -H "X-Killbill-Comment: demo" \
     -d "{ \"pluginName\": \"killbill-stripe-pro\"}" \
     "http://<ELB_ADDRESS>/1.0/kb/accounts/<KB_ACCOUNT_ID>/paymentMethods?pluginProperty=sessionId=cs_test_XXX"
-----

==== Other methods

If you are using https://stripe.com/docs/stripe-js/elements/quickstart[Stripe Elements] or storing payment methods in Stripe via any other way (or if you want to migrate from another billing system and already have customers in Stripe), the flow to setup Kill Bill accounts is as follows:

1. Create a Kill Bill account
2. Attach the custom field `STRIPE_CUSTOMER_ID` to the Kill Bill account. The custom field value should be the Stripe customer id
+
[source,bash]
-----
curl -v \
     -X POST \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -H "X-Killbill-Reason: demo" \
     -H "X-Killbill-Comment: demo" \
     -d "[ { \"objectType\": \"ACCOUNT\", \"name\": \"STRIPE_CUSTOMER_ID\", \"value\": \"cus_XXXXX\" }]" \
     "http://<ELB_ADDRESS>/1.0/kb/accounts/<ACCOUNT_ID>/customFields"
-----
3. Sync the payment methods from Stripe to Kill Bill:
+
[source,bash]
-----
curl -v \
     -X PUT \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -H "X-Killbill-Reason: demo" \
     -H "X-Killbill-Comment: demo" \
     "http://<ELB_ADDRESS>/1.0/kb/accounts/<ACCOUNT_ID>/paymentMethods/refresh"
-----
