= Kill Bill Database Migrations

== Overview

Kill Bill and individual plugins assume specific tables, functions, etc. are installed in your database. The source of truth for DDL files are:

* In individual modules for Kill Bill, under `\*/src/main/resources/org/killbill/billing/*/ddl.sql` (for example https://github.com/killbill/killbill/tree/master/account/src/main/resources/org/killbill/billing/account/ddl.sql[account/src/main/resources/org/killbill/billing/account/ddl.sql]).
* Under `src/main/resources/ddl.sql` for Java plugins (https://github.com/killbill/killbill-adyen-plugin/tree/master/src/main/resources/ddl.sql[Adyen example]).
* Under `db/ddl.sql` for Ruby plugins (https://github.com/killbill/killbill-cybersource-plugin/tree/master/db/ddl.sql[CyberSource example]).

These files always contain the latest version, matching the latest code in that specific branch.

To access a specific version:

* For Kill Bill itself, we publish a full DDL file per major version, available from our http://killbill.io/downloads/[downloads page] (http://docs.killbill.io/0.16/ddl.sql[0.16 example]).
* For individual plugins, you can get the DDL file of a given version on GitHub by looking-up the specific tag (for v4.0.2 of the CyberSource plugin, it would be at https://github.com/killbill/killbill-cybersource-plugin/tree/v4.0.2/db/ddl.sql).

== Migrations

=== Kill Bill

Starting with Kill Bill 0.16.4, SQL migrations files for https://flywaydb.org/[Flyway] are provided. They can be found on a per-module basis under `\*/src/main/resources/org/killbill/billing/*/migration/`. The versioning is based on the creation timestamp (i.e. `date +'%Y%M%d%H%M%S'`).

If you are familiar with the tool, Flyway will work out-of-the-box with these files. If you don't know Flyway and/or don't want to use it, you can apply the migrations manually (they are just SQL files), although this can be error prone and isn't recommended.

=== Java plugins

Java plugins migrations also rely on https://flywaydb.org/[Flyway] and follow a similar workflow than Kill Bill itself. 

=== Ruby plugins

Ruby plugins migrations rely on http://edgeguides.rubyonrails.org/active_record_migrations.html[Active Record migrations]. Migrations are located under `db/migrate/`.

=== KPM

KPM exposes the command `migrations` which can download migration files for Kill Bill or any plugins, between specific versions.

Usage:

```
kpm migrations github_repository from_tag to_tag
```

For example, to download all migration files for Kill Bill between 0.16.3 and 0.16.4:

```
kpm migrations killbill killbill-0.16.3 killbill-0.16.4
```

Similar examples for Java and Ruby plugins:

```
kpm migrations killbill-analytics-plugin analytics-plugin-3.0.0 analytics-plugin-3.0.1
kpm migrations killbill-cybersource-plugin v4.0.1 v4.0.2
```

Because the implementation relies on the https://developer.github.com/[GitHub API], unauthenticated requests are subject to https://developer.github.com/v3/#rate-limiting[rate limiting]. To work around it, go to https://github.com/settings/tokens to generate a token (default public, read-only, permissions will work) and specify it to KPM:

```
kpm migrations killbill killbill-0.16.3 killbill-0.16.4 --token=XXX
```

=== SQL output

In production environments, database access is often restricted and developers don't necessarily have rights to execute DDL commands (i.e. `CREATE`, `ALTER`, `DROP`, etc. statements). To get around this, we provide scripts to get access to the SQL that needs to be run for the migrations, including the `INSERT` statements to update the metadata table(s).

==== Java

For Java code (Kill Bill and Java plugins), we publish a `killbill-flyway.jar` binary which is a wrapper around the `flyway` utility and exposes a `dryRunMigrate` command. Simply run it against your production database (read-only credentials are sufficient) to get the raw SQL.

==== Ruby

For Ruby code, we provide a `killbill-migration` script with the `killbill` gem (JRuby is recommended, see our http://docs.killbill.io/0.16/payment_plugin.html#_building_ruby_plugins[installation instructions]).

Usage examples:

```
killbill-migration current_version cybersource
killbill-migration sql_for_migration cybersource
killbill-migration migrate cybersource
killbill-migration ruby_dump cybersource
killbill-migration sql_dump cybersource
```

