= Kill Bill Database Migrations

== Overview

Kill Bill and individual plugins assume specific tables, functions, etc. are installed in your database. The source of truth for DDL files are:

* In individual modules for Kill Bill, under `\*/src/main/resources/org/killbill/billing/*/ddl.sql` (for example https://github.com/killbill/killbill/tree/master/account/src/main/resources/org/killbill/billing/account/ddl.sql[account/src/main/resources/org/killbill/billing/account/ddl.sql]).
* Under `src/main/resources/ddl.sql` for Java plugins (https://github.com/killbill/killbill-adyen-plugin/tree/master/src/main/resources/ddl.sql[Adyen example]).
* Under `db/ddl.sql` for Ruby plugins (https://github.com/killbill/killbill-cybersource-plugin/tree/master/db/ddl.sql[CyberSource example]).

These files always contain the latest version, matching the latest code in that specific branch.

To access a specific version:

* For Kill Bill itself, we publish a full DDL file per major version, available from our http://killbill.io/downloads/[downloads page] (http://docs.killbill.io/0.16/ddl.sql[0.16 example]).
* For individual plugins, you can get the DDL file of a given version on GitHub by looking-up the specific tag (for v4.0.2 of the CyberSource plugin, it would be at https://github.com/killbill/killbill-cybersource-plugin/tree/v4.0.2/db/ddl.sql).

== Migrations

=== Kill Bill

Starting with Kill Bill 0.16.4, SQL migrations files for https://flywaydb.org/[Flyway] are provided. They can be found on a per-module basis under `\*/src/main/resources/org/killbill/billing/*/migration/`. The versioning is based on the creation timestamp (i.e. `date +'%Y%M%d%H%M%S'`).

If you are familiar with the tool, Flyway will work out-of-the-box with these files.

Additionally, we provide a convenient wrapper integrated with our https://github.com/killbill/killbill/blob/master/bin/db-helper[db-helper] script, which:

* Takes care of aggregating all `migration` directories, across all Kill Bill modules
* Provides a `dryRunMigrate` command

The `dryRunMigrate` command is especially useful in production environments, where database access is restricted and where developers don't have rights to execute DDL commands (i.e. `CREATE`, `ALTER`, `DROP`, etc. statements). Running `dryRunMigrate` against your production database (read-only credentials are sufficient) will output the SQL that needs to be run to migrate it, including the `INSERT` statements to update Flyway's `schema_version` table.

To run this wrapper:

* Clone https://github.com/killbill/killbill[Kill Bill]
* Checkout the tag corresponding to your specific version (e.g. `git checkout killbill-0.16.5`) to get the migration files for that specific Kill Bill version
* Build `util` (`cd util ; mvn clean install -DskipTests=true`)

You can then run the `db-helper` script:

* `./bin/db-helper -a info`
* `./bin/db-helper -a dryRunMigrate`

=== Java plugins

Java plugins migrations also rely on https://flywaydb.org/[Flyway] and follow a similar workflow than Kill Bill itself. Note that while there is no specific `db-helper` script for each plugin, the wrapper tool for Kill Bill (available under `util/target/killbill-flyway.jar`) can be used for plugins.

For more help, see the Flyway documentation or the output of `java -jar util/target/killbill-flyway.jar`.

=== Ruby plugins

Ruby plugins migrations rely on http://edgeguides.rubyonrails.org/active_record_migrations.html[Active Record migrations]. Migrations are located under `db/migrate/`.

Similar to the Java code, we provide a wrapper to get access to the SQL for the migration (i.e. dry run mode).

To run this wrapper:

* Clone the plugin tree
* Checkout the tag corresponding to your specific version to get the migration files for that specific version of the plugin
* Download the plugin dependencies:
```
rm -f Gemfile.lock Jarfile.lock .jbundler/classpath.rb
bundle install
jbundle install
```

You can then run the wrapper in an irb console (JRuby is recommended):

```
$> bundle exec irb
jruby-1.7.20 :001 > require 'killbill/migration'
 => true
jruby-1.7.20 :002 > migration = Killbill::Migration.new('cybersource', {:username => 'killbill', :password => 'killbill', :database => 'killbill'})
 => #<Killbill::Migration:0x3e1f3387 @config={"adapter"=>:mysql, "driver"=>"org.mariadb.jdbc.Driver", "username"=>"killbill", "password"=>"killbill", "database"=>"killbill", "host"=>"127.0.0.1"}>
jruby-1.7.20 :003 > #puts migration.current_version
jruby-1.7.20 :004 > #puts migration.sql_for_migration
jruby-1.7.20 :005 > migration.migrate
jruby-1.7.20 :006 > #puts migration.ruby_dump.string
jruby-1.7.20 :007 > #puts migration.sql_dump.string
```
