= Kill Bill Database Migrations

== Overview

Kill Bill and individual plugins assume specific tables, functions, etc. are installed in your database. The source of truth for DDL files are:

* In individual modules for Kill Bill, under `\*/src/main/resources/org/killbill/billing/*/ddl.sql` (for example https://github.com/killbill/killbill/tree/master/account/src/main/resources/org/killbill/billing/account/ddl.sql[account/src/main/resources/org/killbill/billing/account/ddl.sql]).
* Under `src/main/resources/ddl.sql` for Java plugins (https://github.com/killbill/killbill-adyen-plugin/tree/master/src/main/resources/ddl.sql[Adyen example]).
* Under `db/ddl.sql` for Ruby plugins (https://github.com/killbill/killbill-cybersource-plugin/tree/master/db/ddl.sql[CyberSource example]).

These files always contain the latest version, matching the latest code in that specific branch.

To access a specific version:

* For Kill Bill itself, we publish a full DDL file per major version, available from our http://killbill.io/downloads/[downloads page] (http://docs.killbill.io/0.16/ddl.sql[0.16 example]).
* For individual plugins, you can get the DDL file of a given version on GitHub by looking-up the specific tag (for v4.0.2 of the CyberSource plugin, it would be at https://github.com/killbill/killbill-cybersource-plugin/tree/v4.0.2/db/ddl.sql).

== Migrations

=== Kill Bill

Starting with Kill Bill 0.16.4, SQL migrations files for https://flywaydb.org/[Flyway] are provided. They can be found on a per-module basis under `\*/src/main/resources/org/killbill/billing/*/migration/`. The versioning is based on the creation timestamp (i.e. `date +'%Y%M%d%H%M%S'`).

If you are familiar with the tool, Flyway will work out-of-the-box with these files.

Additionally, we provide a convenient wrapper integrated with our https://github.com/killbill/killbill/blob/master/bin/db-helper[db-helper] script, which:

* Takes care of aggregating all `migration` directories, across all Kill Bill modules
* Provides a `dryRunMigrate` command

The `dryRunMigrate` command is especially useful in production environments, where database access is restricted and where developers don't have rights to execute DDL commands (i.e. `CREATE`, `ALTER`, `DROP`, etc. statements). Running `dryRunMigrate` against your production database (read-only credentials are sufficient) will output the SQL that needs to be run to migrate it, including the `INSERT` statements to update Flyway's `schema_version` table.

To run this wrapper:

* Clone https://github.com/killbill/killbill[Kill Bill]
* Checkout the tag corresponding to your specific version (e.g. `git checkout killbill-0.16.5`), to get the migration files for that specific Kill Bill version
* Build `util` (`cd util ; mvn clean install -DskipTests=true`)

You can then run the `db-helper` script:

* `./bin/db-helper -a info`
* `./bin/db-helper -a dryRunMigrate`

=== Java plugins

Java plugins migrations also rely on https://flywaydb.org/[Flyway].

=== Ruby plugins

Ruby plugins migrations rely on http://edgeguides.rubyonrails.org/active_record_migrations.html[Active Record migrations].
