= Kill Bill development

== Environment setup

Pre-requisites:

* JDK 7 or later installed
* Maven 3.5.2 or later installed
* Git 2.15.1 or later installed

== Build

Kill Bill is a standard Maven project. Simply run the following command from the https://github.com/killbill/killbill[project] root directory:

[source,bash]
----
mvn clean install -DskipTests
----

On the first build, Maven will download all the dependencies from the internet and cache them in the local repository (`~/.m2/repository`), which can take a considerable amount of time. Subsequent builds will be faster.

Once built, you can start Kill Bill by running:

[source,bash]
----
./bin/start-server -s
----

=== Dependencies

The base `pom.xml` (`org.kill-bill.billing:killbill-oss-parent`) defines all of the dependencies required by Kill Bill. If a `-SNAPSHOT` version is specified (e.g. `0.141.74-SNAPSHOT`), this means some dependencies haven't been released yet and you need to build them locally, before being able to build Kill Bill.

Typically, the following repositories need to be built in order:

1. https://github.com/killbill/killbill-oss-parent[killbill-oss-parent]
2. https://github.com/killbill/killbill-commons[killbill-commons]
3. https://github.com/killbill/killbill-platform[killbill-platform]