= Invoice Examples

Whenever there is a change in the system (a recurring subscription billing, an external charge, a change in plan, and so on), Kill Bill generates an invoice. An invoice consists of one or more invoice items of different types. In addition, an invoice has the `balance` and `chargedAmount` attributes which are computed each time an invoice is generated. This document aims to explain these computations in different invoicing scenarios.

== Prerequisites

* Ensure that you have gone through the https://docs.killbill.io/latest/userguide_subscription.html#components-invoicing[_Subscription User Guide_] and are familiar with the basic invoicing concepts. 

* Ensure that you are familiar with the invoice related terminology explained in the https://docs.killbill.io/latest/Kill-Bill-Glossary.html[_Kill Bill Glossary_].  

== More about Charged Amount and Balance

Before we look at each scenario, let us understand how `charged amount` and `balance` are calculated. 

=== Charged Amount/Invoice Amount/Amount

The `charged amount` (also known as `invoice amount` or simply `amount`) specifies the amount that the customer is charged as part of an invoice. It is computed by adding up the amounts on invoice items of type `FIXED`, `RECURRING`, `EXTERNAL_CHARGE`, `USAGE`, `TAX`, `ITEM_ADJ`, `REPAIR_ADJ`, `PARENT_SUMMARY` and `CREDIT_ADJ`. Note that `PARENT_SUMMARY` invoice items are only applicable in the case of https://docs.killbill.io/latest/ha.html[hierarchical accounts] and will be skipped in the rest of this document.

So, `charged amount` can be expressed as follows:

[source,java]
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ + CREDIT_ADJ

[NOTE]
*Note:* In the case of an invoice credit, the `CREDIT_ADJ` invoice items are not taken into account while calculating the charged amount. This is to prevent getting a negative amount as explained in the invoice credit scenario below.

=== Invoice Balance

`Invoice balance` specifies the amount that the customer owes as part of an invoice. It is positive if the customer owes something or zero otherwise. It is calculated by subtracting paid amount, refunded amount and internal credit adjustment (`CBA_ADJ` items) amount from the charged amount. 

So, `Invoice Balance` can be expressed as follows:

[source,java]
INVOICE BALANCE = CHARGED AMOUNT - AMOUNT PAID - AMOUNT REFUNDED - SUM(CBA_ADJ)

[NOTE]
*Note:* In the case of an invoice credit, the sum of the `CREDIT_ADJ` items is also added. This is done to keep the invoice balance `0` as explained in the invoice credit scenario below.


The invoice balance is *always* 0 if:

* The invoice is in a `DRAFT` or `VOID` status
* The invoice is tagged as `WRITTEN_OFF` specifying that its balance should be `0`
* The invoice is a migration invoice (imported from a different billing system into Kill Bill)
* The invoice corresponds to a child account and has a zero parent invoice balance

Let us now understand how the `charged amount` and `invoice balance` are computed in various scenarios.

== Creating a recurring subscription

When a recurring subscription is billed, the system generates an invoice corresponding to it. For example, consider the https://github.com/killbill/killbill-docs/blob/4671dcd9da1cf021e85629ab67e3ffb6fb553bb1/catalogs/monthly-with-trial.xml[monthly-with-trial] catalog. It has a `standard-monthly` plan with a `TRIAL` phase of `10` days followed by an `EVERGREEN` phase with a monthly recurring charge of `$24.95`. Let us understand what happens in this scenario. 

. As soon as a subscription is created, it is in `TRIAL` phase. An invoice is generated with one invoice item of type `FIXED` and amount `0`. 

So, `CHARGED AMOUNT` and `BALANCE` are calculated as follows:

[source,java]
----
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ + CREDIT_ADJ
               = 0 + 0 + 0 + 0 + 0 + 0 + 0
               = 0
               
INVOICE BALANCE = CHARGED AMOUNT - AMOUNT PAID - AMOUNT REFUNDED - SUM(CBA_ADJ)
                = 0 - 0 - 0 - 0
                = 0                
----

[start=2]
. Once the `TRIAL` phase ends, the subscription moves to the `EVERGREEN` phase. An invoice is generated with one invoice item of type `RECURRING` and amount `24.95`.

So, `CHARGED AMOUNT` and `BALANCE` are calculated as follows:

[source,java]
----
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ + CREDIT_ADJ
               = 0 + 24.95 + 0 + 0 + 0 + 0 + 0 + 0
               = 24.95
               
INVOICE BALANCE = CHARGED AMOUNT - AMOUNT PAID - AMOUNT REFUNDED - SUM(CBA_ADJ)  
                = 24.95 - 24.95 - 0 - 0   // assuming the account has a valid default payment method, AMOUNT PAID=24.95
                = 0
----
             
== Adding an invoice credit

Whenever a https://killbill.github.io/slate/#credit-create-credits[credit is added], the system generates an invoice credit. An invoice credit is nothing but an invoice with a `CREDIT_ADJ` and a `CBA_ADJ` item. When such a credit is added, it is adjusted against the amount/balance in other unpaid invoices (if any). 

Let us understand what happens in this scenario:

. When a credit is added (let's say for $20), an invoice is generated with two invoice items: `Type=CREDIT_ADJ, Amount=-20`, and `Type=CBA_ADJ, Amount=20`. The `CREDIT_ADJ` invoice item corresponds to the credit and is negative while the `CBA_ADJ` item is positive and is automatically inserted by the system to bring the invoice balance to `0`.

So, `CHARGED AMOUNT` and `BALANCE` are calculated as follows:

[source,java]
----
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ // CREDIT_ADJ not taken into account for invoice credit
               = 0 + 0 + 0 + 0 + 0 + 0 + 0 
               = 0
               
INVOICE BALANCE = CHARGED AMOUNT - AMOUNT PAID - AMOUNT REFUNDED - SUM(CBA_ADJ)  + SUM(CREDIT_ADJ) //CREDIT_ADJ taken into account for invoice credit
                = 0 - 0 - 0 + 20 + (-20)
                = 0               
----             

[start=2]
. When the account is charged (either due to a recurring subscription or an external charge), the credit added is adjusted. So, for example, if an external charge is created for `$100`, it will have an invoice item of type `EXTERNAL_CHARGE` and amount `100`. In addition, it will also have an invoice item of type `CBA_ADJ` and amount `20` automatically generated by the system corresponding to the credit adjustment.

So, `CHARGED AMOUNT` and `BALANCE` are calculated as follows:

[source,java]
----
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ + CREDIT_ADJ
               = 0 + 0 + 100 + 0 + 0 + 0 + 0 + 0
               = 100
               
INVOICE BALANCE = CHARGED AMOUNT - AMOUNT PAID - AMOUNT REFUNDED - SUM(CBA_ADJ)  
                = 100 - 0 - 0 - 20 // assuming the account DOES NOT have a valid default payment method, AMOUNT PAID=0
                = 80               
----

== Invoice Adjustment

An invoice can also be adjusted by adding a credit to it.  (Note that the invoice needs to be in `DRAFT` status for this). In such a case, an invoice item of type `CREDIT_ADJ` is created and the `charged amount` is adjusted against it.

Let us understand what happens in this scenario:

. Let us assume that a DRAFT invoice is created corresponding to an `EXTERNAL CHARGE` of `$100`. It will have a single invoice item of type `EXTERNAL_CHARGE` and amount `100`. 

So, `CHARGED AMOUNT` and `BALANCE` are calculated as follows:

[source,java]
----
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ + CREDIT_ADJ
               = 0 + 0 + 100 + 0 + 0 + 0 + 0 + 0
               = 100   
               
INVOICE BALANCE = 0  // since invoice is in DRAFT status               
----
                
[start=2]
. Next, when a CREDIT is added to the invoice (say $20), the invoice is modified.  A new invoice item is added of type `CREDIT_ADJ` and amount `-20`.

So, `CHARGED AMOUNT` and `BALANCE` are calculated as follows:

[source,java]
----
CHARGED AMOUNT = FIXED + RECURRING + EXTERNAL_CHARGE + USAGE + TAX + ITEM_ADJ + REPAIR_ADJ + CREDIT_ADJ
               = 0 + 0 + 100 + 0 + 0 + 0 + 0 + (-20)
               = 80   
               
INVOICE BALANCE = 0  //since invoice is still in DRAFT status               
----

[start=3]
. Finally, when the invoice is committed, the balance is updated:

[source,java]
----
INVOICE BALANCE = CHARGED AMOUNT - AMOUNT PAID - AMOUNT REFUNDED - SUM(CBA_ADJ)  
                = 80 - 0 - 0 - 0  // assuming the account DOES NOT have a valid default payment method, AMOUNT PAID=0
                = 80
----

== Additional Information

https://docs.killbill.io/latest/invoice_subsystem.html[_Invoice Subsystem_]



