= Invoice Examples

This document provides examples of different invoice scenarios. 

== Prerequisites

Ensure that you have gone through the https://docs.killbill.io/latest/userguide_subscription.html#components-invoicing[_Subscription User Guide_] and are familiar with the basic invoicing concepts.


== Invoice Terminology - work in progress

Whenever there is a change in the system (a recurring subscription billing, an external charge, a change in plan, and so on), the system generates an invoice. An invoice consists of one or more invoice items of different types. In addition, an invoice consists of several components like `balance`, `chargedAmount`, `paidAmount` and so on. Let us first understand some of these terms. 


* *Invoice Item*: Represents an amount corresponding to a type of charge, credit or adjustment. The different types of invoice items are `RECURRING`, `FIXED`, `EXTERNAL_CHARGE`, `USAGE`, `TAX`, `ITEM_ADJ`, `CREDIT_ADJ`, `REPAIR_ADJ` and `CBA_ADJ` as  explained in the https://docs.killbill.io/latest/userguide_subscription.html#components-invoicing[subscription billing] document. 

* *Invoice Payment*: Represents a payment corresponding to an invoice. It has a `type` and an `amount`. The different types of invoice payments are `ATTEMPT` (represents successful payment), `CHARGED_BACK` (represents a chargeback) and `REFUND` (represents a refund) 


* *chargedAmount*: The amount that the customer is charged. It is computed by adding up the amounts on invoice items of type `FIXED`, `RECURRING`, `EXTERNAL_CHARGE`, `REPAIR_ADJ`, `ITEM_ADJ`, `USAGE` and `TAX`. So, `chargedAmount=FIXED + RECURRING + EXTERNAL_CHARGE + REPAIR_ADJ + ITEM_ADJ + USAGE + TAX`  
//TODO, add about including CREDIT_ADJ in case of DRAFT invoice?

* *amountPaid*: The amount that the customer has paid. Is calculated by subtracting invoice payments of type `REFUND` and `CHARGEBACK` from invoice payments of type `ATTEMPT`. In other words, `amountPaid=attempt - (refund + chargeback)`

* *invoiceBalance*: The amount that the customer owes or zero (in case the invoice corresponds to a credit).  It is calculated by subtracting credits, adjustments and the `amountPaid` from the `chargedAmount`. In other words, invoiceBalance = chargedAmount - amountPaid -amountRefunded - SUM(CBA_ADJ)  - SUM(ITEM_ADJ). The invoice balance is always 0 if the invoice is in a `DRAFT` or `VOID` status or if it is writtenoff, is a migration invoice or has a zero parent invoice balance (in case the invoice corresponds to a child account). 

* *creditAdj*: The credit amount on an invoice. It is calculated as the sum of all the CBA_ADJ items on an invoice.

* *refundAdj*: The amount refunded on the payments corresponding to the invoice. It is the sum of invoice payments of type `REFUND` and `CHARGEBACK`. In other words,  refundAdj = refund + chargeback

* *status* : Status of the invoice. Can be one of `DRAFT`, `COMMITTED` or `VOID` 

Let us take a look at the various invoice scenarios. 


== Create subscription with Trial and Recurring Phase

This scenario explains what happens when a recurring subscription is created.

. Upload the https://github.com/killbill/killbill-docs/blob/4671dcd9da1cf021e85629ab67e3ffb6fb553bb1/catalogs/monthly-with-trial.xml[monthly-with-trial] catalog. It has a `standard-monthly` plan with a `TRIAL` phase of `10` days followed by an `EVERGREEN` phase with a monthly recurring charge of `$24.95`.

. Create an account with a payment method that works (You can use __EXTERNAL_PAYMENT__ for testing). Set this payment method as the default payment method.

. Perform actions as explained in the table below:

[options="header",cols="1,1,1,1,1"]
|===
|Action   |System Behavior |Invoice Amount/Balance |Invoice Item Type/Amount  |Explanation    
//----------------------------------------
|Create a subscription to the `standard-monthly` plan   |Invoice generated   |`amount=0`,`balance=0`   |`Type=FIXED`, `Amount=`0`   |Subscription is in `TRIAL` phase so `balance` is `0`  
|Move clock by `10` days (end of the `TRIAL` phase)    |Invoice generated    |`amount=24.95`,`balance=0`   |`Type=RECURRING`, `Amount=24.95`   |Trial period ends, so invoice is generated for `24.95`. Since we have a working payment method, this invoice gets paid and so `balance` is `0`  
|Delete payment method and move clock by 1 month    |Invoice generated   |`amount=24.95,balance=24.95`   |`Type=RECURRING, Amount=24.95`   |Since a payment method is not present, invoice is not paid, so balance is `24.95`   
|===

== Add Credit

This scenario explains what happens when a credit is added.

. Create an account without a payment method. 

. Perform actions as explained in the table below:


[options="header",cols="1,1,1,1,1,1"]
|===
|Number|Action   |System Behavior |Invoice Amount/Balance |Invoice Item Type/Amount  |Explanation      
//----------------------------------------
|1|Create an external charge of `$100`   |Invoice generated   |`amount=100,balance=100`    |`Type=EXTERNAL_CHARGE, Amount=100`   |Since a payment method is not present, invoice is not paid, so balance is `100`     
|2|Add credit of `$20`   |Invoice generated   |`amount=0,balance=0`    |
`Type=CREDIT_ADJ, Amount=-20`, 

`Type=CBA_ADJ, Amount=20` |Whenever a credit is added, the system automatically inserts an invoice item of type `CBA_ADJ` to bring the invoice balance to `0`   
||   |Invoice generated at step 1 modified  |`amount=100,balance=80`   |`Type=EXTERNAL_CHARGE, Amount=100` (Generated at step 1), 

`Type=CBA_ADJ, Amount=20` (new)    |Invoice is modified by creating a new item of type `CBA_ADJ` to adjust credit. Since a credit of `20` is added, the balance is `80`  
|3|Add Credit of `$50`   |Invoice generated   |`amount=0,balance=0`   |`Type=CREDIT_ADJ, Amount=-50`, 

`Type=CBA_ADJ, Amount=50`   |Whenever a credit is added, the system automatically inserts an invoice item of type `CBA_ADJ` to bring the invoice balance to 0.    
||   |Invoice generated at step 1 modified    |`amount=100,balance=30`   |`Type=EXTERNAL_CHARGE, Amount=100` (Generated at step1), 

`Type=CBA_ADJ, Amount=20` (Generated at step 2), 

`Type=CBA_ADJ, Amount=50` (new)   |Invoice is modified by creating a new item of type `CBA_ADJ` to adjust credit. Since a credit of `50` is added, the balance is now `30`  
|4|Add Credit of `$60`   |Invoice generated   |`amount=0,balance=0`   |`Type=CREDIT_ADJ, Amount=-60`, 

`Type=CBA_ADJ, Amount=60`   |Whenever a credit is added, the system automatically inserts an invoice item of type `CBA_ADJ` to bring the invoice balance to `0`   
| |  |Invoice generated at step 1 modified     |`amount=100,balance=0`   |`Type=EXTERNAL_CHARGE, Amount=100` (Generated at step 1), 

`Type=CBA_ADJ, Amount=20` (Generated at step 2), 

`Type=CBA_ADJ, Amount=50` (Generated at step 3),  

`Type=CBA_ADJ, Amount=30` (new) |Invoice is modified by creating a new item of type `CBA_ADJ` to adjust credit. Only `$30` of the credit is used since the balance was only `$30`      
|===

== Adjust Invoice Item

This scenario explains what happens when an invoice item is adjusted.

. Create an account without a payment method. 

. Perform actions as explained in the table below:

[options="header",cols="1,1,1,1,1"]
|===
|Action   |System Behavior |Invoice Amount/Balance |Invoice Item Type/Amount  |Explanation   
//----------------------------------------
|Create an external charge of `$100`   |Invoice generated   |`Amount=100, Balance=100`   | `Type=EXTERNAL_CHARGE, Amount=100`  |   Since a payment method is not present, invoice is not paid, so balance is `100`  
|Adjust invoice item (Amount=60)   |Invoice modified   |`Amount=40, Balance=40`    |`Type=EXTERNAL_CHARGE, Amount=100` (existing), 

`Type=ITEM_ADJ, Amount=60` (new)   |The adjustment amount is adjusted in the invoice   
|===


== Cancel Subscription

== Change subscription plan

== Usage Billing

== Overdue flow 



== Additional Information

https://docs.killbill.io/latest/userguide_subscription.html#components-invoicing[_Subscription Billing User Guide_]

https://docs.killbill.io/latest/invoice_subsystem.html[_Invoice Subsystem_]



