= Logo Customisation

The default logo image that is displayed on the left hand side of the Kaui navigation bar may be
customised using the following approach;

== Steps

* Check out the killbill-admin-ui project from github.

* The default logo image file is located at app/assets/images/kaui/logo.png. This PNG image has a
resolution of 148 x 37. Copy and rename this file in case you wish to revert at a later date.

* Copy your logo image file into the app/assets/images/kaui and name it logo.png.

* Build the kaui gem by running the rake build command

----
   rake build
----

The newly built gem is located in pkg/kaui-x.y.z.gem (currently 1.4.1)

* Check out the killbill-admin-ui-standalone project from github and navigate to the top level directory
of the project.

* Open the Gemfile in your favourite IDE editor and change;
----
    gem 'kaui', '~> 1.0'
    #gem 'kaui', :path => '../killbill-admin-ui'
    #gem 'kaui', :github => 'killbill/killbill-admin-ui', :ref => 'master'
----
to
----
    #gem 'kaui', '~> 1.0'
    gem 'kaui', :path => '../killbill-admin-ui'
    #gem 'kaui', :github => 'killbill/killbill-admin-ui', :ref => 'master'
----

i.e. disable the default kaui gem reference and specify explicitly the newly built gem from the killbill-admin-ui
project.

* Run bundle update
----

    bundle update
----

* Run bundle info to verify that the kaui gem is correctly referenced from the killbill-admin-up project
----
    bundle info kaui
----

This should output something similar to;

----
  kaui (1.4.1)
        Summary: Killbill Admin UI mountable engine
        Homepage: http://www.killbill.io
        Path: /root/IdeaProjects/killbill-admin-ui

* Start or restart your Rails server

    rails s
----
