= Managing Metrics with New Relic

include::{sourcedir}/aws/includes/aws-card.adoc[]

== Overview

Several third-party tools are available to manage and display the metrics produced by Kill Bill. One popular tool is https://www.newrelic.com/[New Relic]. This
package offers a low-cost option to monitor and display whatever metrics
you may find useful from the Kill Bill collection, including metrics
that show the performance and resource use of Kill Bill and Kaui
themselves, and metrics describing the infrastructure on which these
systems run.

New Relic can be integrated with several types of Kill Bill installations. In this guide we discuss the use of New Relic to manage metrics produced
by single-tier and multi-tier implementations on Amazon Web Services (AWS). The latest Amazon Machine Image (AMI)
for Kill Bill is preconfigured to direct the Kill Bill metrics to
New Relic and work with them in the way that best suits your needs. These instructions apply to the Kill Bill AMI version 2021.9 or later.

To set up New Relic to manage the metrics available from Kill Bill, there
are just two steps:

1. Setup a New Relic account
2. Edit a configuration file to enable the transfer of the complete Kill Bill metrics.

== Set Up New Relic

You may already be familiar with New Relic. If not, this section will
explain how to get started.

First, go to the https://www.newrelic.com/[New Relic website]. New Relic
offers a free account as long as your usage does not exceed certain limits. Provide a name and email address to sign up.

You should see the New Relic main page. To get back to this page at a future time you can click the words *New Relic One* in the upper left corner.



== Set Up the Authorization

To authorize the sending of the Kill Bill metrics, it is necessary to
edit two lines in this file:

```
/var/lib/tomcat/bin/setenv2.sh
```

This file contains configuration information for `tomcat`, which manages the
KillBill web applications.

This is a small file. The two lines to be edited are:

```
-Dcom.killbill.newrelic.enable=false
-Dcom.killbill.newrelic.apiKey=
```

These should be changed to:

```
-Dcom.killbill.newrelic.enable=true
-Dcom.killbill.newrelic.apiKey=Your-API-Key
```

New Relic provides several types of keys. The API key to be added is called the *Insights Insert Key.*
To find the Insights Insert Key:

. Close any overlay panes on the New Relic page by clicking on the `X` in the upper right corner.
. Click the symbol at the far upper right to open your account menu, then select *API keys*.
. On the page that appears, select *Insights Insert keys* at the lower right.
. In the *Insert Keys* column on the left, under the word *key* at the bottom, click *Show*.
. Manually copy the key to your clipboard, then paste it to the configuration file.

After editing the file, go to your AWS EC2 dashboard and *reboot the
instance* so the new configuration file will be read. If you have more
than one instance, follow the same procedure for each one.

== Test the Installation

To test your installation, follow these simple steps:

. Go to the New Relic main page
. Select *Browse Data* from the top menu
. Select *Metrics* from the dropdown

After a short delay, you
should see a long list of metrics; well over 1,000 in your list.

Congratulations. Your New Relic integration is complete!

== Using New Relic

The New Relic site has lots of https://docs.newrelic.com/[documentation], so we won't
repeat any of that here. We will just suggest a few quick steps to get
started:

1. Close any overlay panes on the New Relic page by clicking on the `X` in the upper right corner.
2. Select *Browse Data* in the menu and *Metrics* in the submenu. A list of available metrics will appear on the left.
3. Select some metrics to see the graph (chart) they produce. Identify the ones you would like to see together in a dashboard.
4. To create a dashboard, close the metrics page, select *Dashboards* in the menu, and click *+ Create a Dashboard*.
5. Select *Create New Dashboard*, give it a name, and click *Create*.

You can add charts to your dashboard for any metrics you choose. The charts can be edited, deleted, and rearranged. Your dashboard will appear under the *Dashboards* menu item. Have fun and good luck!




