= Kill Bill Migration Guide

== Overview

This guide is intended to provide some guidelines for running migrations from an **existing billing system** to **Kill Bill**.
It is by no mean an exact recipe book to follow, but it provides some recommendations on how to do things (based on previous experiences) and highlight some specific areas of concern.

The assumption is there is already an internal or third party billing system in place:
* It receives some live traffic, and migration should not cause any downtime
* It contains existing state (subscriptions, invoices, ...) that need to be migrated without impacting customers
* It provides a UI that services like customer support (CS) use to handle customer tickets
* It provides state/data that is used by accounting/financial departments
* One or several system in the company are interracting with that system through API calls

The end goal of the migration is to make sure that we can unplug completely the old billing system and yet provide the same level of service (or better) for the customers and the various departments in the organization.
This is a fairly ambitious goal, which may require a potentially a gradual shutdwon of the old system.

== Strategy





== Stage 1: Setting up Kill Bill


== Stage 2: Behavioral Analysis


== Stage 3: Behavioral Analysis

== Stage 4: Running the Migration




