= Overview

In the Kill Bill model, `Subscriptions` are associated to a `Plan` (defined in the catalog), and `Plans` are made of several `PlanPhases`.
The idea behind the model is to accurately represent the transitions from different phases (e.g `TRIAL` -> `EVERGREEN`) without having the system/user to take any actions:
Subscriptions automatically transition from one `PlanPhase` to the next, as defined by the shape of the `Plan` and the clock moving forward.

When changing the `Plan` associated to a subscription (e.g upgrade), the system needs to understand how to align phases from original `Plan` to new `Plan` to make sure the user ends up in the right phase.
Let's consider the following example with two similar `Plans` (`Silver` and `Gold`) both containing two phases, namely a 7 days `TRIAL` phase, followed by a monthly `EVERGREEN` (recurring forever until cancelled) phase.

* On january 1st, subscription is initially created with a `Silver` `Plan`, and starts with the 7 days `TRIAL` period.
* On january 4th, while the subscription is still in `TRIAL`, the user upgrades to a `Gold` plan.

As a company offering those plans, you have the choice to define the behavior of such operation:

1. You may want to restart a full 7 days `TRIAL` period (the `Plan` being different, one way want the user to have a fully 7 days period to experiment)
2. You may want to offer the remaining of the `TRIAL` period (4 days left)
3. You may want to skip the `TRIAL` altogether (The user already made up his mind he liked the product and upgraded to `Gold` so he is already committed).

In order to provide this level of flexibility, the catalog contains alignement rules to specify such behaviors.

Such alignement rules exist both for operations that create `Subscription` (to decide on how to align Add-On `Plan` with respect to the `Base` `Plan`) and also, as mentionned in the previous example for change `Plan` operations.
The http://docs.killbill.io/latest/userguide_subscription.html#_subscription_alignment_rules[Kill Bill Subscription Guide] provides an overview of such alignments.







