= Plugin Management APIs

[[overview]]
== Overview

Started with Kill Bill 0.16.0, it is now possible to go through all the lifecycle (install, start, stop, uninstall and list status) of a plugin using apis.
The apis have been designed to work on a killbill deployment that consists of several instances.

The feature relies on the following pieces:
* A running version of a (or several) killbill server(s)
* A running https://github.com/killbill/killbill-kpm-plugin[KPM plugin] on each killbill instance.

Obviously installing the KPM plugin will first need to happen using https://github.com/killbill/killbill-cloud/tree/master/kpm [KPM] itself.


== APIs

Each of the API refers to a plugin using a `pluginKey`. A `pluginKey` can be one of the following:
* An entry in the official Kill Bill https://github.com/killbill/killbill-cloud/blob/master/kpm/lib/kpm/plugins_directory.yml [plugin reporsitory],
* A user provided key that will be used to identify this plugin when using the APIs. The user provided key must be unique and must contain a namespace (e.g MY_NAMESPACE:myKey). 
  During the installation phase, and when using a user provided key, one must also specify additonal properties to specify the location of that plugin.


=== Installation

Example of installing a `paypal plugin` with a specified version of `4.0.0`:
[source,bash]
----
curl -v \
-u admin:password \
-H "X-Killbill-ApiKey: bob" \
-H 'X-Killbill-ApiSecret: lazar' \
-H "Content-Type: application/json" \
-H 'X-Killbill-CreatedBy: stephane' \
-X POST \
--data-binary '{"systemCommandType":"true","nodeCommandType":"INSTALL_PLUGIN","nodeCommandProperties":[{"key":"pluginKey", "value":"paypal"}, {"key":"pluginVersion","value":"4.0.0"} ]}' \
"http://127.0.0.1:8080/1.0/kb/nodesInfo"
----





