include::{sourcedir}/common/five-minutes.adoc[]

[[five-minutes-create-authorization]]
==== Create an authorization

Let's try to authorize the payment method:

[source,bash]
----
curl -v \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -X POST \
     --data-binary '{"transactionType":"AUTHORIZE","amount":"10","currency":"USD","transactionExternalKey":"INV-001-AUTH"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/payments"
----

This will return a direct payment object. We will assume its uuid is `078a4500-d15e-11e3-9c1a-0800200c9a66` in the examples below.


[[five-minutes-create-capture]]
==== Capture this authorization

[source,bash]
----
curl -v \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -X POST \
     --data-binary '{"amount":"5","currency":"USD","transactionExternalKey":"INV-001-CAPTURE"}' \
     "http://127.0.0.1:8080/1.0/kb/payments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

[[five-minutes-payments-combo]]
==== Alternative with call (also referred to as payment combo call)

In order to create the account, add the payment method and then proceed with the payment (auth, purchase, ..), we added a 'combo' payment call that will create the various states (acccount, payment method) if they don't already exist.
The call is provided as a convenience to avoid making multiple calls. It does not offer transactional properties, for instance if creating the account works but somehow adding the payment method fails, the call would fail and yet the account would end up being created.
However, the call is idempotent, so retrying the call for the same account would resume the steps and thefeore not re-create the account which already exists.

[source,bash]
----
curl -v \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H 'X-Killbill-CreatedBy: demo' \
     -X POST \
     --data-binary '{
     "account": {
         "name":"My Name",
         "currency":"USD"
     },
     "paymentMethod": {
         "pluginName":"__EXTERNAL_PAYMENT__",
	     "pluginInfo":{}
	 },
	 "transaction": {
	     "transactionType":"AUTHORIZE",
	     "amount":12.5,
	     "currency":"USD"
	 }
}' \
"http://127.0.0.1:8080/1.0/kb/payments/combo"

----