=== API Overview

Kill Bill's payment related APIs can mainly be classified as follows:

* *Payment Methods APIs* - Used for operations related to payment methods like adding/deleting a payment method, etc.
* *Payment APIs* - Used for payment related operations. These are used by:
** The Kill Bill core billing engine to charge for subscriptions
** Kaui (the Kill Bill Admin UI) to handle refunds, chargebacks, adjustments, etc. for invoices and payments associated with such subscriptions.
** Directly by an e-commerce application to trigger payments for one-off charges or to create payment forms and redirect URLs in case of hosted payment pages.

=== Plugin Properties

The Payment Method and Payment APIs have been built to be as generic as possible. Because each plugin/gateway has its own specificities, you can pass extra data by using plugin properties:

* For each API, one can specify custom properties by using query parameters -- those query parameters should be URL encoded
* Kill Bill will deserialize the query parameters and pass them straight to the plugin

This mechanism allows to pass information from the client of the API to the plugin, while being opaque to Kill Bill; for instance, in order to specify the following two plugin properties:

[source,bash]
----
{ "city" => "San Francisco", "billing_address" => "address[postcode]=94114" }
----

One would have to add the following query parameters (note that this needs to be URL encoded):

[source,bash]
----
pluginProperty=San%3DFrancisco&pluginProperty=billing_address%3Daddress%5Bpostcode%5D%3D94114
----

The mechanism also works for receiving information back from the plugin; the plugin can return a piece of json that will be embedded in the json response; for instance, the plugin could return a specific key:

[source,bash]
----
       "pluginInfo": {
         "properties": [{
           "key": "pluginSpecificKey",
           "value": "9876543210"
         }]
----
