=== Direct Payments APIs

A payment object is associated with a set of transactions (authorization, multiple captures, etc.). You can retrieve that object via:

[source,bash]
----
curl -v \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     "http://127.0.0.1:8080/1.0/kb/payments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

The calls below describe how to create payments. For each call, you can specify in the body a *transactionExternalKey* string to tag your payments (it represents a unique identifier in an external system).

==== Authorization

To create an authorization on the default payment method of the account:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"AUTHORIZE","amount":"10","currency":"USD","transactionExternalKey":"INV-001-AUTH"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/payments"
----

This will return a direct payment object. We will assume its uuid is `078a4500-d15e-11e3-9c1a-0800200c9a66` in the examples below.

Notes:

* For multi-steps authorization (e.g. 3DS), you can specify a `paymentId` field in the body for subsequent calls
* You can specify another payment method (other than the default one) via the `paymentMethodId` query parameter

==== Capture

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"amount":"5","currency":"USD","transactionExternalKey":"INV-001-CAPTURE"}' \
     "http://127.0.0.1:8080/1.0/kb/payments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

Notes:

* You can call this endpoint multiple times for partial captures (all of these captures will share the same direct payment id)

==== Purchase

This call is similar to the authorization one:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"PURCHASE","amount":"10","currency":"USD","transactionExternalKey":"INV-001-PURCHASE"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/payments"
----

Notes:

* You can specify another payment method (other than the default one) via the `paymentMethodId` query parameter

==== Void

[source,bash]
----
curl -v \
     -X DELETE \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionExternalKey":"INV-001-VOID"}' \
     "http://127.0.0.1:8080/1.0/kb/payments/078a4500-d15e-11e3-9c1a-0800200c9a66"
----

==== Refund

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"amount":"5","currency":"USD","transactionExternalKey":"INV-001-REFUND"}' \
     "http://127.0.0.1:8080/1.0/kb/payments/078a4500-d15e-11e3-9c1a-0800200c9a66/refunds"
----

==== Credit

This call is similar to the authorization one:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"transactionType":"CREDIT","amount":"10","currency":"USD","transactionExternalKey":"INV-001-CREDIT"}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/payments"
----

Notes:

* You can specify another payment method (other than the default one) via the `paymentMethodId` query parameter

=== Hosted pages helpers

[[build-form-descriptor]]
==== Build form descriptor

The `buildFormDescriptor` call is used when you need to prepare a payment form. There are two main scenarii:

* The payment form is hosted on your own website. The exact fields to add in this form are returned by the plugin. These can be:
** required visible fields, such as the amount of the payment. The plugin will return the name expected by the gateway (e.g. `Sum` instead of `amount`)
** hidden fields (e.g. `merchantId` value)
* The payment form is hosted on the gateway website. In that case, the plugin builds a unique URL to redirect the user to by either:
** submitting the order information (amount, etc.) to the gateway which returns the location of the hosted payment form
** constructing the special URL via query parameters

Given an order of $10, here is how you can get the HTML fields to build the form:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{ "formFields": [{ "key": "order_id", "value": "1234" }, { "key": "amount", "value": "10" }, { "key": "currency", "value": "USD" }]}' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/hosted/form/268983f2-5443-47e4-a967-b8962fc699c5"
----

Notes:

* Replace _268983f2-5443-47e4-a967-b8962fc699c5_ with the account id
* You can specify another payment method (other than the default one) via the `paymentMethodId` query parameter

[[gateway-notification]]
==== Process gateway notifications

Gateway notifications (Recurly push notifications, PayPal or BitPay IPN, etc.) can be processed through this API:

[source,bash]
----
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     "http://127.0.0.1:8080/1.0/kb/paymentGateways/notifications/pluginName?customKey=value
----

Make sure to replace `pluginName` with your plugin name (e.g. killbill-bitpay).

The plugin will deserialize either the request body and/or the url query parameters to process the notification and return a properly formatted HTTP response object for the gateway (some gateways require specific response codes or headers to consider the notification processed and prevent retries).

Because this endpoint needs to be on a public IP (to be accessible from the gateway), we recommend using the https://github.com/killbill/killbill-notifications-proxy[Kill Bill Notifications Proxy] to avoid exposing the entire Kill Bill server.

=== Examples of hosted pages flows

The implementation of the `buildFormDescriptor` and `processNotification` APIs described above will vary from gateway to gateway.
While the internal mechanics of completing the payment vary for each plugin, the overall steps are usually the same:

. Your website calls `buildFormDescriptor` and interprets the result
. The customer is then either shown a payment form or redirected to an external page
. The customer is then either shown a payment form or redirected to an external page
. The customer completes the payment

Here are a couple of example flows:

==== Gateway notifies Kill Bill of the payment

In this scenario, no payment has been created in Kill Bill after the `buildFormDescriptor` call. Upon completion of the payment, either the gateway will pass information about the payment in the redirect url parameters or it will send an out-of-band notification.

In the first case, you will need to create the payment using the `purchase` call during the redirect. The plugin will then query the gateway to verify the payment (for security purposes).

In the second case, the plugin will create the payment during the `processNotification` call (see the https://github.com/killbill/killbill-bitpay-plugin/[BitPay] plugin for an example).

In both cases, the payment will end up in a terminal state (either succeeded or failed).
 
==== Kill Bill polls the gateway

In this scenario, during the `buildFormDescriptor` call, the plugin will most likely create state in the gateway (e.g. the generated redirect url points to a unique voucher) and will also create a matching payment in Kill Bill (in a pending state).

Kill Bill will then automatically start polling the plugin for that payment, which will in turn query the gateway for the latest payment status. See the https://github.com/killbill/killbill-payu-latam-plugin[PayU Latam] plugin for an example.
