=== Payment Methods and plugin names

By default, each plugin has a *name* which is specific to the plugin and configured in the plugin code. On start-up, Kill Bill detects all the plugins and starts them. When a plugin is started, it gets *registered* with Kill Bill with its name. 

When a merchant application invokes the `KillBill#addPaymentMethod`, the name of the plugin corresponding to the payment method needs to be specified. This gets saved in the Kill Bill database as part of the payment method record. 

Kill Bill then uses the plugin name to route the payment processing to the appropriate plugin. So, when it is time to charge the customer against the default payment method, the plugin name corresponding to the payment method is retrieved from the Kill Bill database. Kill Bill then routes the payment to the appropriate plugin. 

Suppose there are two payment plugins named *PluginA* and *PluginB*. When Kill Bill is started, it starts both plugins which register themselves with Kill Bill as *PluginA* and *PluginB* respectively. Now suppose an end user enters payment method details corresponding to *PluginA*. When the merchant application invokes `KillBill#addPaymentMethod`, *PluginA* needs to be specified along with the payment method details for *PluginA*. Assuming that *PluginA* is the default payment method, Kill Bill then retrieves the corresponding plugin name (*PluginA*) from the database and routes the payment processing to the *PluginA* code. Thus, it uses the plugin name to determine which plugin should process a particular payment.





