=== Plugin Properties

In the sections below, we are presenting APIs to manage payment methods and payments operations. Those APIs have been built to be as generic as possible. Because each plugin/gateway has its own specificities, you can pass extra data by using plugin properties:

* For each API, one can specify custom properties by using query parameters -- those query parameteres should be URL encoded
* Kill Bill will deserialize the query parameters and pass them straight to the plugin

This mechanism allows to pass information from the client of the API to the plugin, while being opaque to Kill Bill; for instance, in order to specify the following two plugin properties:

[source,bash]
----
{ "city" => "San Francisco", "billing_address" => "address[postcode]=94114" }
----

One would have to add the following query parameters (note that this needs to be URL encoded):

[source,bash]
----
pluginProperty=San%3DFrancisco&pluginProperty=billing_address%3Daddress%5Bpostcode%5D%3D94114
----

The mechanism also works for receiving information back from the plugin; the plugin can return a piece of json that will be embedded in the json response; for instance, the plugin could return a specific key:

[source,bash]
----
       "pluginInfo": {
         "properties": [{
           "key": "pluginSpecificKey",
           "value": "9876543210"
         }]
----