=== Payment States

A payment consists of multiple payment transactions. Also, a payment has a state which determines the set of possible subsequent operations available.

Initially a client of the api can make either an *authorization*, a *purchase*, or a *credit* call (all other operations such as refund would require an initial payment to have already existed).
That initial operation will create a https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/payment/api/Payment.java[Payment] and an initial https://github.com/killbill/killbill-api/blob/c243233be112165bf04a89a715b79112c6c5d1f7/src/main/java/org/killbill/billing/payment/api/PaymentTransaction.java[PaymentTransaction].
The user can then submit additional requests for the same payment (capture, refund, ...) and each of those calls will result in additional `PaymentTransaction` attached to the same payment.
The payments have a state which will drive the set of possible subsequent operations available. For instance, it is possible to make a capture call against a payment in a state `AUTH_SUCCESS` but it is not possible to make such an operation against a payment in an `AUTH_ERRORED` state.

The set of payment state transitions are configured in an https://github.com/killbill/killbill/blob/master/payment/src/main/resources/org/killbill/billing/payment/PaymentStates.xml[xml file] and the Kill Bill payment subsystem is in charge to enforce the transitions. The following diagram below shows all the possible transitions:

image::../assets/payment_states2.svg[align="center"]

//graphviz::assets/payment_states.dot[format=svg,align=center]

In addition to the payment state transitions, each `PaymentTransaction` has a status to reflect the result of the operation. The `PaymentTransaction` status depends on the plugin result and it can be summarized below:

|===
|plugin result | payment transaction status | payment state | http response | description

|PROCESSED
|SUCCESS
|{AUTH,CAPTURE,..}_SUCCESS
| 201 - Created
|The payment transaction went through and was successful

|PENDING
|PENDING
|{AUTH,CAPTURE,..}_PENDING
| 201 - Created
|Successful asynchronous operation (e.g. ACH transfer) or multi-step call (e.g. 3D-Secure authorization)

|ERROR
|PAYMENT_FAILURE
|{AUTH,CAPTURE,..}_FAILED
| 402 - Payment Required
|The payment transaction went through but failed (e.g insufficient funds)

|CANCELED
|PLUGIN_FAILURE
|{AUTH,CAPTURE,..}_ERRORED
| 502 - Bad Gateway
|The payment transaction did not happen (e.g unable to connect to the provider, error in plugin, etc)

|UNDEFINED, timeout or any exception
|UNKNOWN
|{AUTH,CAPTURE,..}_ERRORED
| 503 - Service Unavailable
504 - Gateway Timeout
|The payment transaction may or not have succeeded, manual review needed

|===

Note that the first 3 cases are normal cases but the last 2 are errors that are unrelated to the user being able to make the payment operation:

* in the case of a hard plugin failure (CANCELED result code), the gateway was probably down and the payment wasn't attempted: there is no attempt to fix those.
* in the case of a plugin timeout (or UNDEFINED result code), the operation might actually have completed; Kill Bill will run a background task to detect those cases and will query the plugin to verify if the state is actually known and when it is, it will update the *transaction status* and move the payment to its appropriate state. If the plugin cannot tell if the payment went through, the transaction will stay in an UNKNOWN state. It is advisable to check that those are rare instances and fix the data appropriately (by checking manually the status in the gateway for example). See the section Janitor below for more details.

If a payment is aborted by a control plugin, a payment attempt row is recorded with a state of ABORTED (no payment nor payment transaction is created). Kill Bill will return a 422 HTTP code.

[[Janitor]]
=== Janitor

PENDING and UNKNOWN transaction states should be temporary; the payment plugin needs to eventually tell Kill Bill what the final state of these transactions should be. This can be done explicitly by the plugin by calling the https://github.com/killbill/killbill-api/blob/4ae1c343a593de937415e21feecb9f5405037fa3/src/main/java/org/killbill/billing/payment/api/PaymentApi.java#L402[`PaymentApi.notifyPendingTransactionOfStateChanged`] (for instance, when receiving a webhook event from the gateway) or implicitly by the Janitor.

The Janitor refers to a set of internal Kill Bill features to help ensure transactions end up in a terminal state; these are the Janitor notification queue and the on-the-fly Janitor. They both work by calling the plugin (via https://github.com/killbill/killbill-plugin-api/blob/d9eca5af0e37541069b1c608f95e100dbe13b301/payment/src/main/java/org/killbill/billing/payment/plugin/api/PaymentPluginApi.java#L144[`PaymentPluginApi.getPaymentInfo`]) and updating the state owned by Kill Bill if it has changed. For this mechanism to work, it is *imperative* that payment plugin developers take great care when implementing this API (see our https://docs.killbill.io/latest/payment_plugin.html[_Payment Plugin_] developer documentation for more details).

==== Janitor Notification Queue

A Janitor notification entry is inserted whenever a payment results in a non terminal state (whether the payment was initiated internally by Kill Bill or externally via our payment APIs). Kill Bill will then periodically poll the plugin to attempt to fix the state.

The polling delay is configured via the  `org.killbill.payment.janitor.unknown.retries` property for UNKNOWN transactions (default `5m,1h,1d,1d,1d,1d,1d`) and the `org.killbill.payment.janitor.pending.retries` property for PENDING transactions (default `1h,1d`). You can configure these properties as explained in the https://docs.killbill.io/latest/userguide_configuration.html[_Configuration Guide_]. Companies that rely on PENDING for offline payment methods (ACH, Boleto, etc.) should increase the number of attempts, as such payments can be slow (i.e., take multiple days to execute).

==== On-The-Fly Janitor

The on-the-fly Janitor is invoked:

* Whenever a payment (or set of payments) is https://github.com/killbill/killbill-api/blob/4ae1c343a593de937415e21feecb9f5405037fa3/src/main/java/org/killbill/billing/payment/api/PaymentApi.java#L439[retrieved via API] and the flag `withPluginInfo` is set. In this case, a `GET` operation might result in data being written to disk (but it's not really a new state, it's just an existing state being updated that was incomplete).
* Whenever an operation is performed on an existing payment (either initiated internally by Kill Bill or externally via our payment APIs): the Janitor is invoked first to get the latest state to ensure the internal state machine prevents disallowed transitions in case the state couldn't be fixed (or if it's already in a final state). For example, if an authorization state is currently UNKNOWN and you attempt to capture it, the Janitor will ask the plugin first to fix the state and either let the capture go through (if the authorization is fixed as SUCCESS) or disallow it (if the authorization couldn't be fixed or was unsuccessful).

Note however that the `notifyPendingPaymentOfStateChanged` operation will not invoke the Janitor (as this API is often called from payment plugins, we don't want the state to be fixed twice).

==== Janitor and Control Plugins

When the Janitor fixes a payment, it will re-run the Payment Control state machine (i.e. go through Payment Control plugins) if needed. For instance, invoice payments that were created as part of a RECURRING invoice may end up being fixed automatically by the Janitor, and the balance associated with the invoice would then be correctly reflected.

Any invoice payment triggered by API and fixed by the Janitor would not be retried, in order to leave full control to the caller to decide what to do and whether to retry. Invoice payments triggered automatically by the system and fixed by the Janitor would however be retried as configured.
