== HTTPS and Certificates

The HTTP protocol, commonly used for message exchange over the internet, does not provide encryption or authentication.
As a result messages exchanged with this protocol may be insecure and subject to eavesdropping, and their source may be uncertain.
To avoid this problem, HTTP is frequently combined with an encryption scheme known as SSL, or more recently TLS,
that can be used to keep messages safe from unauthorized access, and verify that the sender is who they claim to be. This secure protocol is called HTTPS.

HTTPS is based on the use of a verification document called a *certificate*. the certificate serves two purposes:

1. It provides the keys necessary for a highly secure encryption.
2. It provides the electronic signature of a *certificate authority (CA)* who guarantees the identity of the sender.

Increasingly, modern browsers require valid certificates when accessing sites using the HTTPS protocol. It may be difficult or impossible to access these sites if a valid certificate is not found.

The structural details of certificates are defined by international standards; for more details see the https://en.wikipedia.org/wiki/X.509[Wikipedia article]. The certificate authority is either an organization that is intrinsically well-known and trusted, such as DigiCert or GlobalSign (called a *root* CA), or an organization in the *trust hierarchy* derived from a root. A CA in a trust hierarchy must be itself certified by another CA in a chain which eventually leads to the root CA. Your CA, in turn, must be able to certify that *you* are who you say you are!

For temporary use, you can sometimes create a *self-signed* certificate, in which you are your own CA. Most browsers will frown on this, since you are simply vouching for yourself, but it may allow you to get started with security.

