==== Download the Tomcat container

If you don't have it yet, you can download the Tomcat container http://tomcat.apache.org/download-80.cgi[here]. The documentation is available http://tomcat.apache.org/tomcat-8.0-doc/index.html[here].

==== Deploy Kill Bill in Tomcat

We will assume you have installed Tomcat in a directory called *CATALINA_HOME*.

The Kill Bill system properties need to be added at the end of *CATALINA_HOME/conf/catalina.properties*. The minimal set of system properties that need to added are the ones for the jdbc parameters:

[source,java]
----
# Kill Bill properties
org.killbill.dao.url=jdbc:mysql://127.0.0.1:3306/killbill
org.killbill.dao.user=killbill
org.killbill.dao.password=killbill
org.killbill.billing.osgi.dao.url=jdbc:mysql://127.0.0.1:3306/killbill
org.killbill.billing.osgi.dao.user=killbill
org.killbill.billing.osgi.dao.password=killbill
----

A new entry must be added to let tomcat know about the location of the Kill Bill war. That file is called *Root.xml* and it must located under *CATALINA_HOME/conf/Catalina/localhost* (create the directories if they don't exist). Its content must be:

[source,xml]
----
<Context docBase="path_to_killbill-server.war">
</Context>
----

Once this is setup, you can start the tomcat container using the script *CATALINA_HOME/bin/startup.sh*. The server will be started in the background but logs can be followed at *CATALINA_HOME/logs/catalina.out*.
