==== Download the Jetty container

If you don't have it yet, you can download the Jetty container http://download.eclipse.org/jetty/[here]. If you're unsure which version to use, we recommend *8.1.7.v20120910*. Make sure you can unpack and start Jetty as described http://wiki.eclipse.org/Jetty/Howto/Install_Jetty[here].

Jetty ships with examples you can safely remove:

* contexts/javadoc.xml
* contexts/test.d/override-web.xml
* contexts/test.xml
* webapps/spdy.war
* webapps/test.war

==== Deploy Kill Bill in Jetty

Place the downloaded Kill Bill war under *webapps/root.war* in the Jetty folder.

Update the *start.ini* file with Kill Bill specific configuration. Here is a working example (make sure to adapt the jdbc properties):

[source,java]
----
# Kill Bill properties
-Dorg.killbill.dao.url=jdbc:mysql://127.0.0.1:3306/killbill
-Dorg.killbill.dao.user=killbill
-Dorg.killbill.dao.password=killbill
-Dorg.killbill.billing.osgi.dao.url=jdbc:mysql://127.0.0.1:3306/killbill
-Dorg.killbill.billing.osgi.dao.user=killbill
-Dorg.killbill.billing.osgi.dao.password=killbill

# Start classpath OPTIONS
OPTIONS=Server,resources,ext,plus,annotations

# Configuration files
etc/jetty.xml
etc/jetty-annotations.xml
etc/jetty-deploy.xml
etc/jetty-webapps.xml
----

You should now be all set! Kill Bill can be started via the command

[source,bash]
----
java -jar start.jar
----

==== Enable SSL

The following command generates a key pair and certificate directly into a keystore:

[source,bash]
----
keytool -keystore keystore -alias jetty -genkey -keyalg RSA
----

Save the keystore file under the *etc/* directory of the Jetty distribution.

In your *start.ini* file, add the *etc/jetty-ssl.xml* configuration file and edit this file to update the *KeyStorePassword*, *KeyManagerPassword* and *TrustStorePassword* directives with the passwords you specified when you ran the keytool command.

Kill Bill should now be available over SSL. For more details, see the Jetty guide http://wiki.eclipse.org/Jetty/Howto/Configure_SSL[here].
