=== Overview

Kill Bill (whether used as a Billing System or Payment System) is fundamentally a backend system and so the following consideration should apply:

* Don't make the system visible to the outside world, you should have a front end system, or a reverse proxy in front of it; if you need to handle some IPN (Internal Payment Notification), we also developed an https://github.com/killbill/killbill-notifications-proxy[app] for that specific purpose.
* Always deploy at least 2 instances (for reliability purpose) in front of a load balancer.
* Setup your database with a master and a slave instances (or more exotic setup if required), and configure it to take regular snapshot
* Aggregate your logs (for example using http://logstash.net/[LogStash], https://www.graylog.org/[GrayLog2], ...) and take a look at our https://github.com/killbill/killbill/wiki/Logback-recipes[logback recipes]
* Look at the all the existing Kill Bill JMX metrics (using VisualVM, jconsole, ...) and set some alerts (for instance by using the following https://github.com/killbill/nagios-jmx-plugin[script])
* Configure your system properly, especially when it comes to the https://github.com/killbill/killbill/wiki/Kill-Bill-Notification-Configuration[settings of the bus and notification queue].


When deploying Kill Bill, the following pieces will need to be deployed in addition to your OS, VM, or container (Docker,...):

* A web container (jetty, tomcat, ...)
* The killbill war
* The plugins
* The configuration files and system properties
* The database along with the various schemas: The Kill Bill schema is available from our http://killbill.io/downloads[download page] and each stateful plugin will/should expose such a schema (for example, here is the https://github.com/killbill/killbill-adyen-plugin/blob/master/src/main/resources/ddl.sql[schema] for the Adyen plugin)

In order to ease the deployment we first created https://github.com/killbill/killbill-cloud/tree/master/kpm[KPM], the Kill Bill Package Manager.
KPM will allow to fetch existing (signed) artifacts for the main killbill war and also for each of the plugins, and deploy them at the right place.
KPM will *not* take care of deploying the web container and the various configuration files or properties.

So, in addition to KPM, we also provide https://registry.hub.docker.com/u/killbill/killbill[Docker images]. Those images internally rely on KPM for fetching the
various artifacts and install them at the right location on the image. The docker `run` command allows to override existing Kill Bill system properties and mount
volumes where configuration files can be accessed.

Note that one can decide to only use KPM for fetching and installing artifacts, and bypass docker to deploy on VMs or bare metal.
Or alternatively one can use other tools, manual steps to fetch those artifacts from http://search.maven.org/[Maven Central], or by using our convenient http://killbill.io/downloads[download page].

The following sections below will give manual instructions on how to deploy on various containers.
