=== Database Properties
[options="header",cols="1,1,1"]
|===
|Property Name/Environment Variable Name   |Description   |Default Value
//-------------------------------------------------
|kaui.db.adapter/

KAUI_DB_ADAPTER   |Specifies the Kaui Database Adapter   |mysql2
|kaui.db.encoding/

KAUI_DB_ENCODING   |Specifies the Kaui Database Encoding   |utf8
|kaui.db.database/

KAUI_DB_DATABASE   |Specifies the Kaui Database Encoding (only applicable if `kaui.db.adapter=sqlite3`)   |/var/tmp/kaui.sqlite3
|kaui.db.url/

KAUI_DB_URL   |Specifies the Kaui Database URL   |jdbc:mysql://localhost:3306/kaui?useUnicode=true&useJDBCCompliantTimezoneShift=true&
useLegacyDatetimeCode=false&serverTimezone=UTC
|kaui.db.username/

KAUI_DB_USERNAME   |Specifies the Kaui Database Username   |root
|kaui.db.password/

KAUI_DB_PASSWORD   |Specifies the Kaui Database Password   |root
|kaui.db.host/

KAUI_DB_HOST   |Specifies the Kaui Database Host   |None
|kaui.db.port/
KAUI_DB_PORT   |Specifies the Kaui Database Port   |None
|kaui.db.pool/

KAUI_DB_POOL   |Specifies the Kaui Database thread pool   |50
|kaui.db.timeout/

KAUI_DB_TIMEOUT   |Specifies the Kaui Database connection timeout   |5000

|===

=== Kill Bill Client Properties
[options="header",cols="1,1,1"]
|===
|Property Name/Environment Variable Name   |Description   |Default Value
//-------------------------------------------------
|kaui.url/

KILLBILL_URL/KAUI_KILLBILL_URL   |Specifies the Kill Bill URL   |http://127.0.0.1:8080
|kaui.disable_ssl_verification/

KILLBILL_DISABLE_SSL_VERIFICATION/

KAUI_KILLBILL_DISABLE_SSL_VERIFICATION   |Whether to ignore SSL certificates checks   |false
|kaui.read_timeout/

KILLBILL_READ_TIMEOUT/

KAUI_KILLBILL_READ_TIMEOUT   |Specifies the time KAUI waits to receive response from Kill Bill server   |60000
|kaui.connection_timeout/

KILLBILL_CONNECTION_TIMEOUT/

KAUI_KILLBILL_CONNECTION_TIMEOUT   |Specifies the time KAUI waits to establish connection with Kill Bill server    |60000

|===

=== Kaui Properties
[options="header",cols="1,1,1"]
|===
|Property Name/Environment Variable Name   |Description   |Default Value
//-------------------------------------------------
|kaui.demo/

KAUI_DEMO_MODE   |Whether to run Kaui in demo mode   |false
|kaui.plugins_whitelist/

KAUI_PLUGINS_WHITELIST   |Kaui plugins to be shown in the installed plugins list   |None (shows all installed plugins)
|kaui.root_username/

KAUI_ROOT_USERNAME   |Specifies the root username   |admin
|kaui.disable_sign_up_link/

KAUI_DISABLE_SIGN_UP_LINK   |Whether to disable the sign up link   |false
|kaui.chargeback_reason_codes/

KAUI_CHARGEBACK_REASON_CODES   |Default reason codes for chargebacks   |None
|kaui.credit_reason_codes/

KAUI_CREDIT_REASON_CODES   |Default reason codes for credits   |None
|kaui.invoice_item_reason_codes/

KAUI_INVOICE_ITEM_REASON_CODES   |Default reason codes for item adjustments   |None
|kaui.invoice_payment_reason_codes/

KAUI_INVOICE_PAYMENT_REASON_CODES   |Default reason codes for invoice payments   |None
|kaui.payment_reason_codes/

KAUI_PAYMENT_REASON_CODES  |Default reason codes for payments  |None
|kaui.refund_reason_codes/

KAUI_REFUND_REASON_CODES   |Default reason codes for refunds  |None
|===

=== Encryption Properties
[options="header",cols="1,1,1"]
|===
|Property Name/Environment Variable Name   |Description   |Default Value
//-------------------------------------------------
|kaui.encryption.filename/

KAUI_ENCRYPTION_FILENAME   |File containing the encryption keys   |config/symmetric-encryption.yml
|kaui.secret_key_base/

KAUI_SECRET_KEY_BASE   |Secret key base used for securing session data and other sensitive information.   |Any string value (A long randomly generated string of characters is recommended)
|===

