=== Kill Bill Platform

At its core, Kill Bill offers a flexible platform on which applications that require a high level of integrity, audit traces, and robustness can be developed. Currently there are two kind of applications that have been developed:

* http://killbill.io/subscription-billing[Billing Systems] to manage recurring/usage based subscriptions
* http://killbill.io/payments-platform/[Payment systems] that integrate with various payment gateways, payment processors, fraud detection systems, ...

The *Billing System* relies on the *Payment System* to make payments but the *Payment System* also offers raw payment apis and therefore can also be run as a standalone application.

Some of the features of the Kill Bill platform include:

* Core Foundations
** A plugin framework where custom plugins can be added to modify the behavior of the system, and or interact with third party systems,
** A robust persistent event bus, that is used both internally and externally (events are visible to plugins)
** An auditing framework that keeps track of all the changes that occurred (who?, when?, what?)
** Authentication and RBAC support
* Core services (account management, invoicing, entitlement, dunning, ...) which are built and packaged as independent jars, each of which with its own api; those core services post a well defined set of events on the persistent bus which are then consumed by other core services or plugins.
* Plugins

// Bug for aligning the caption https://github.com/asciidoctor/asciidoctor/issues/857 [caption="Kill Bill Logical Architecture",align=center]
image::https://docs.google.com/drawings/d/1OCYn6GTrmEbJi9daT8L9xPCgwp7n5FidTWH0nHpCYqE/pub?w=960&amp;h=480[align=center]

Contrary to most billing solutions, Kill Bill is *not* a batch oriented system, but instead, it is driven by events occurring in the system (for e.g: the creation of a new subscription will create a new event that the invoicing core service will process and as result a new invoice may be created along with a new event which the payment code service will now process, ...)

Kill Bill is traditionally packaged as a war and is therefore executed within a web container (for e.g tomcat). It offers REST APIs <TODO LINK> to manage all the state associated to accounts, subscriptions, invoices, payments, ... It also provides lower level (java) APIs and can therefore be embedded as a library within a (java) user application.

=== Documentation

Our documentation is targeted for different types of audience:

* Kill Bill Visitors: Technical or Non technical folks interested to know more about what Kill Bill is about.
* Kill Bill Users: Technical folks that are interested to evaluate the solution or are ready to deploy it.
* Kill Bill Developers: Technical folks that are interested to contribute to the open-source project (often to enhance the platform to suit their own specific needs).

For the *Kill Bill Visitors*, we provide an overview of the product on our http://killbill.io[main web site], and also http://killbill.io/features[some more details about the features].

For the *Kill Bill Users*,  we provide a set of

* http://killbill.io/userguide/platform-userguide[user guides],
* http://killbill.io/tutorials/[tutorials],
* https://www.youtube.com/channel/UChXICgGipKvJbtzKfM1SNoQ[screencasts],
* In addition to that, we also provide documentation for each specific plugin in the github plugin repository using the `Readme.rd` file. An example of such documentation can be seen for the https://github.com/killbill/killbill-avatax-plugin[Avatax plugin].


The user guides are split into 3 different pages:

* http://killbill.io/userguide/platform-userguide[Platform User Guide], that is, *this very page*, which focuses on generic information about the Kill Bill platform (plugin overview, deployment and configuration),
* http://killbill.io/userguide/payments-userguide/[Payment System User Guide]: Focuses on various payment methods, payment flows, ...
* http://killbill.io/userguide/subscriptions-userguide/[Billing System User Guide]: Focuses all the non payment aspects for the billing system.

For the *Kill Bill Developers*, we also provide additional pages on our https://github.com/killbill/killbill/wiki[github wiki].

Also, don't forget to check our http://killbill.io/blog/[blog], which has interesting articles about some of Kill Bill internals, use cases, ...

*Most of our documentation is hosted in a https://github.com/killbill/killbill-docs[github repository], so please either submit a PR when obvious things are missing or wrong, or let us know so we can improve it!*

=== Where To Start?


This obviously depends on the type of audience, and also whether you are looking for a Billing System, or a Payment System.
If your goal is to get a sense of what Kill Bill provides, and assuming you are at least slightly technical, here is a good start:

1. Read through the user guides (all 3)
2. Follow the <TODO:link section 5' minutes tutorials in the ...>

TODO: needs some more thinking
At this stage, you are ready to prototype, and the following section will be especially useful to help you understand how to start, customize a Kill Bill instance for your needs.



